"""Canonical manga artifact paths (relative to series or chapter roots)."""

from __future__ import annotations

STYLE_BIBLE = "series/style_bible.json"
LETTERING_STYLE_BIBLE = "series/lettering_style_bible.json"
GENRE_BLUEPRINT = "series/genre_blueprint.json"
STORY_ARCHITECTURE_INTERNAL = "series/story_architecture_internal.json"
STORY_ARCHITECTURE_HANDOFF = "series/story_architecture_handoff.json"
ASSET_REGISTRY = "series/asset_registry.json"
MANGA_AUTHOR_IDENTITY = "series/manga_author_identity.json"
CHARACTER_MODEL_SHEETS = "series/character_model_sheets.json"
MOTIF_EVOLUTION_MAP = "series/motif_evolution_map.json"
SERIES_MEMORY = "series/series_memory.json"
ANCHOR_PANELS_DIR = "series/anchor_panels"

CHAPTER_REQUEST = "chapter_request.json"
CHAPTER_SCRIPT_WRITER_HANDOFF = "chapter_script_writer_handoff.json"
CHAPTER_SCRIPT_INTERNAL_RECORD = "chapter_script_internal_record.json"
PANEL_PROMPTS = "panel_prompts.json"
PANEL_IMAGES_MANIFEST = "panel_images_manifest.json"
PANEL_IMAGES_DIR = "panel_images"
LETTERING_SPEC = "lettering_spec.json"
BUBBLED_PANELS_DIR = "bubbled_panels"
FINAL_PAGE_COMPOSITE_DIR = "final_page_composite"
REVISION_QUEUE = "revision_queue.json"
SERIES_MEMORY_UPDATE = "series_memory_update.json"
SERIES_MEMORY_SNAPSHOT = "series_memory_snapshot.json"
STAGES_DIR = "stages"
DEBUG_DIR = "debug"
