#!/usr/bin/env python3
"""Translate stillness_press en_US book text -> ja_JP via Qwen on Pearl Star.

Per CLAUDE.md LLM tier policy: ja_JP prose is generated by Qwen on Pearl Star
(Tier 2, free), NOT hand-written by Claude. This calls the Ollama /api/generate
endpoint (QWEN_BASE_URL host) with qwen2.5:14b.

The book text uses section markers the EPUB parser recognizes
(build_epub.py:parse_book_text). This translator:
  1. splits the en_US text into sections on those markers,
  2. translates each section body via Qwen,
  3. rewrites the headers to the Japanese forms the parser detects:
       "CHAPTER N: TITLE"        -> "第N章 <translated title>"
       "A NOTE ON THE TEACHINGS" -> "教導縁起"
       "WHERE TO GO DEEPER"      -> "深入修行"
       the leading all-caps book title -> translated title line
  4. reassembles into ja text ready for build_epub.py --language ja.

Idempotent: skips if the output file already exists and is non-trivial.

Usage:
  eval "$(python3 scripts/ci/load_integration_env_from_keychain.py)"
  python3 translate_book_ja.py \
    --in  ../en_US/books/text/book_<slug>.txt \
    --out books/text/book_<slug>.ja.txt
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
import urllib.request
from pathlib import Path

KANJI_NUM = {1: "一", 2: "二", 3: "三", 4: "四", 5: "五",
             6: "六", 7: "七", 8: "八", 9: "九", 10: "十"}

SYSTEM = (
    "You are a professional Japanese literary translator specializing in "
    "contemplative wellness and self-help prose. Translate the English into "
    "natural, warm literary Japanese (ja_JP) suitable for a published book. "
    "Use appropriate keigo for gentle wellness writing. Preserve the emotional "
    "tone, body-awareness language, and second-person address. Output ONLY the "
    "Japanese translation — no romaji, no English, no commentary, no notes."
)

HEADER_RE = re.compile(
    r"^(CHAPTER\s+\d+\s*:?.*|A NOTE ON THE TEACHINGS|WHERE TO GO DEEPER|"
    r"[A-Z][A-Z0-9 '’:\-—]{6,})$"
)
CHAPTER_RE = re.compile(r"^CHAPTER\s+(\d+)\s*:?\s*(.*)$", re.IGNORECASE)


def _ollama_host() -> str:
    base = os.environ.get("QWEN_BASE_URL", "").rstrip("/")
    if not base:
        sys.exit('QWEN_BASE_URL not set — run: eval "$(python3 scripts/ci/'
                 'load_integration_env_from_keychain.py)"')
    return base[:-3] if base.endswith("/v1") else base


def qwen_translate(text: str, *, model: str = "qwen2.5:14b",
                   timeout: float = 300.0, retries: int = 5,
                   min_len: int = 2) -> str:
    host = _ollama_host()
    payload = json.dumps({
        "model": model,
        "prompt": f"{SYSTEM}\n\n---\n{text}\n---",
        "stream": False,
        "options": {"temperature": 0.3, "num_predict": 4096},
    }).encode()
    last = ""
    for attempt in range(retries + 1):
        try:
            req = urllib.request.Request(
                host + "/api/generate", data=payload,
                headers={"Content-Type": "application/json"})
            with urllib.request.urlopen(req, timeout=timeout) as r:
                out = json.loads(r.read())
            reply = out.get("response", "").strip()
            reply = re.sub(r"<think>.*?</think>", "", reply, flags=re.DOTALL).strip()
            # strip stray code fences / leading labels
            reply = re.sub(r"^```[a-z]*\n?|\n?```$", "", reply).strip()
            if len(reply) >= min_len:
                return reply
            # empty/too-short: model may have been mid-load or contended; back off
            last = f"reply too short ({len(reply)} chars)"
        except Exception as e:  # noqa: BLE001
            last = str(e)
        time.sleep(3 * (attempt + 1))  # linear backoff: 3,6,9,12,15s
    raise RuntimeError(f"Qwen translate failed after {retries+1} tries: {last}")


_EMOJI_RE = re.compile(
    "[\U0001F000-\U0001FAFF\U00002600-\U000027BF\U0001F300-\U0001F9FF←-⇿⌀-⏿]")
_CYRILLIC_RE = re.compile(r"[Ѐ-ӿ]")


def clean_header(h: str) -> str:
    """Strip emoji, parenthetical meta-comments, and stray non-CJK fragments
    from a translated chapter/section header (Qwen sometimes appends notes)."""
    h = _EMOJI_RE.sub("", h)
    h = _CYRILLIC_RE.sub("", h)
    # drop a trailing parenthetical "（建設中：…）" meta comment (full/half width)
    h = re.split(r"[（(]", h, maxsplit=1)[0].strip()
    # drop trailing ASCII-word fragments after Japanese (e.g. "… PERMISSION")
    h = re.sub(r"\s+[A-Za-z][A-Za-z ]+$", "", h).strip()
    return h.strip("「」\"' 　")


def clean_existing_file(path: Path) -> int:
    """Post-clean chapter/section headers in an already-translated .ja.txt.

    Returns number of header lines changed.
    """
    chap = re.compile(r"^(第[一二三四五六七八九十0-9]+章)(.*)$")
    changed = 0
    out = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = chap.match(line.strip())
        if m:
            cleaned = (m.group(1) + " " + clean_header(m.group(2)).strip()).strip()
            if cleaned != line.strip():
                changed += 1
            out.append(cleaned)
        else:
            out.append(line)
    path.write_text("\n".join(out) + ("\n" if not out or out[-1] else ""), encoding="utf-8")
    return changed


def translate_header(line: str) -> str:
    cm = CHAPTER_RE.match(line)
    if cm:
        n = int(cm.group(1))
        title_en = cm.group(2).strip()
        num = KANJI_NUM.get(n, str(n))
        if title_en:
            title_ja = qwen_translate(
                f"Translate this chapter title to a short natural Japanese title. "
                f"Output ONLY the title, no quotes, no notes, no parentheses, "
                f"no emoji, no English: {title_en}")
            title_ja = clean_header(title_ja.splitlines()[0].strip().strip("「」\"' "))
            return f"第{num}章 {title_ja}"
        return f"第{num}章"
    if line.strip() == "A NOTE ON THE TEACHINGS":
        return "教導縁起"
    if line.strip() == "WHERE TO GO DEEPER":
        return "深入修行"
    # all-caps title line (book title / section) -> translate as a heading
    t = qwen_translate(f"Translate this book/section heading to a short natural "
                       f"Japanese heading. Output ONLY the heading, no quotes, "
                       f"no notes, no parentheses, no emoji, no English: {line.strip()}")
    return clean_header(t.splitlines()[0].strip().strip("「」\"' "))


def split_sections(text: str) -> list[tuple[str | None, list[str]]]:
    """Return [(header_or_None, body_lines), ...] preserving order."""
    sections: list[tuple[str | None, list[str]]] = []
    cur_header: str | None = None
    cur_body: list[str] = []
    for raw in text.splitlines():
        line = raw.rstrip("\n")
        if HEADER_RE.match(line.strip()) and len(line.strip()) < 90:
            if cur_header is not None or cur_body:
                sections.append((cur_header, cur_body))
            cur_header = line.strip()
            cur_body = []
        else:
            cur_body.append(line)
    sections.append((cur_header, cur_body))
    return sections


def translate_book(in_path: Path, out_path: Path, model: str) -> Path:
    text = in_path.read_text(encoding="utf-8")
    sections = split_sections(text)
    out_lines: list[str] = []
    n_sec = len(sections)
    for i, (header, body) in enumerate(sections):
        if header is not None:
            ja_header = translate_header(header)
            out_lines.append(ja_header)
            print(f"  [{i+1}/{n_sec}] header: {header[:40]!r} -> {ja_header[:40]!r}")
        body_text = "\n".join(body).strip()
        if body_text:
            # translate the body in <=6000 char chunks on blank-line boundaries
            chunks, cur = [], ""
            for para in body_text.split("\n\n"):
                if len(cur) + len(para) > 6000 and cur:
                    chunks.append(cur)
                    cur = para
                else:
                    cur = (cur + "\n\n" + para).strip()
            if cur:
                chunks.append(cur)
            ja_parts = []
            for j, ch in enumerate(chunks):
                ja_parts.append(qwen_translate(ch, model=model))
                print(f"        body chunk {j+1}/{len(chunks)} ({len(ch)} chars) translated")
            out_lines.append("\n\n".join(ja_parts))
        out_lines.append("")  # blank line between sections
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(out_lines).strip() + "\n", encoding="utf-8")
    return out_path


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="inp", type=Path)
    ap.add_argument("--out", dest="out", type=Path)
    ap.add_argument("--model", default="qwen2.5:14b")
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--clean-existing", type=Path, nargs="+",
                    help="post-clean chapter headers in existing .ja.txt files (no Qwen calls)")
    args = ap.parse_args()
    if args.clean_existing:
        for p in args.clean_existing:
            n = clean_existing_file(p)
            print(f"  cleaned {n} header(s) in {p}")
        return 0
    if not args.inp or not args.out:
        ap.error("--in and --out are required unless --clean-existing is used")
    if args.out.is_file() and args.out.stat().st_size > 200 and not args.force:
        print(f"  [skip] {args.out} exists")
        return 0
    t0 = time.time()
    translate_book(args.inp, args.out, args.model)
    sz = args.out.stat().st_size
    print(f"  wrote {args.out} ({sz} bytes, {time.time()-t0:.0f}s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
