#!/usr/bin/env python3
"""Generate teacher showcase videos: YouTube (5min, 16:9) + Instagram Reels (90s, 9:16).

Descript-style audiobook videos: black background + white text + waveform + audio.
Uses FFmpeg directly — no external API needed.

Formats:
  youtube      — 5 min (300s), 1920×1080, 16:9
  instagram    — 90 s, 1080×1920, 9:16  (Instagram Reels max)

Audio required (generated by ElevenLabs/CosyVoice pipeline):
  artifacts/showcase/audio/{teacher_id}_{audio_topic}.mp3       → YouTube 5-min
  artifacts/showcase/audio/{teacher_id}_{audio_topic}_hook.mp3  → Instagram 90s

Usage:
  python3 scripts/video/generate_teacher_showcase_videos.py
  python3 scripts/video/generate_teacher_showcase_videos.py --teacher ahjan
  python3 scripts/video/generate_teacher_showcase_videos.py --dry-run
  python3 scripts/video/generate_teacher_showcase_videos.py --test-audio  # generate sine-wave placeholder audio
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
AUDIO_DIR = REPO_ROOT / "artifacts" / "showcase" / "audio"
YT_OUTPUT = REPO_ROOT / "artifacts" / "showcase" / "video" / "youtube"
IG_OUTPUT = REPO_ROOT / "artifacts" / "showcase" / "video" / "instagram"

FFMPEG = os.environ.get("FFMPEG", "ffmpeg")
FFPROBE = os.environ.get("FFPROBE", "ffprobe")

# Resolve ffmpeg binary (mirrors _config.py logic)
for _candidate in [FFMPEG, "/opt/homebrew/bin/ffmpeg", "/usr/local/bin/ffmpeg"]:
    if Path(_candidate).is_file() and os.access(_candidate, os.X_OK):
        FFMPEG = _candidate
        break
for _candidate in [FFPROBE, "/opt/homebrew/bin/ffprobe", "/usr/local/bin/ffprobe"]:
    if Path(_candidate).is_file() and os.access(_candidate, os.X_OK):
        FFPROBE = _candidate
        break

# ── Durations ─────────────────────────────────────────────────────────────────
YOUTUBE_MAX_S = 300   # 5 minutes
INSTAGRAM_MAX_S = 90  # Instagram Reels max per platform_compliance.yaml

# ── Topic assignments ──────────────────────────────────────────────────────────
# YT topic: the subject matter of the 5-min educational video
TEACHER_YT_TOPIC = {
    "ahjan": "burnout", "adi_da": "courage", "joshin": "overthinking",
    "junko": "burnout", "maat": "self_worth", "master_feung": "somatic_healing",
    "master_sha": "somatic_healing", "master_wu": "burnout", "miki": "sleep_anxiety",
    "omote": "self_worth", "pamela_fellows": "somatic_healing", "ra": "depression",
    "sai_ma": "compassion_fatigue",
}

# Instagram topic: the hook topic for the 90s Reel
TEACHER_IG_TOPIC = {
    "ahjan": "self_worth", "adi_da": "boundaries", "joshin": "burnout",
    "junko": "courage", "maat": "social_anxiety", "master_feung": "courage",
    "master_sha": "depression", "master_wu": "boundaries", "miki": "anxiety",
    "omote": "social_anxiety", "pamela_fellows": "financial_anxiety", "ra": "courage",
    "sai_ma": "depression",
}

# Audio topic: which audiobook the source audio is drawn from
TEACHER_AUDIO_TOPIC = {
    "ahjan": "depression", "adi_da": "depression", "joshin": "sleep_anxiety",
    "junko": "imposter_syndrome", "maat": "courage", "master_feung": "self_worth",
    "master_sha": "anxiety", "master_wu": "self_worth", "miki": "compassion_fatigue",
    "omote": "imposter_syndrome", "pamela_fellows": "burnout", "ra": "self_worth",
    "sai_ma": "boundaries",
}

TEACHER_NAMES = {
    "ahjan": "Ahjan", "adi_da": "Adi Da", "joshin": "Joshin",
    "junko": "Junko", "maat": "Maat", "master_feung": "Master Feung",
    "master_sha": "Master Sha", "master_wu": "Master Wu", "miki": "Miki",
    "omote": "Omote", "pamela_fellows": "Pamela Fellows", "ra": "Ra",
    "sai_ma": "Sai Ma",
}

TEACHER_BRAND = {
    "ahjan": "Stillness Press", "adi_da": "Awakening Press", "joshin": "Clear Seeing Books",
    "junko": "Bare Form Books", "maat": "Feather & Scale Press", "master_feung": "Root & Meridian Press",
    "master_sha": "Night Architecture Books", "master_wu": "Iron Gate Press", "miki": "Present Tense Books",
    "omote": "Held Ground Press", "pamela_fellows": "Felt Sense Publishing", "ra": "Ember & Ash Publishing",
    "sai_ma": "Open Vessel Press",
}


def _get_audio_duration(audio_path: Path) -> float | None:
    """Return audio duration in seconds, or None on failure."""
    try:
        r = subprocess.run(
            [FFPROBE, "-v", "quiet", "-print_format", "json", "-show_format", str(audio_path)],
            capture_output=True, text=True, timeout=15,
        )
        import json
        data = json.loads(r.stdout)
        return float(data["format"]["duration"])
    except Exception:
        return None


def _esc(text: str) -> str:
    """Escape text for FFmpeg drawtext."""
    return text.replace("\\", "\\\\").replace("'", "\\'").replace(":", "\\:").replace("%", "\\%")


def _render_video(
    audio_path: Path,
    output_path: Path,
    title: str,
    author: str,
    brand: str,
    width: int,
    height: int,
    max_duration: int,
    dry_run: bool = False,
) -> bool:
    """Render Descript-style audiobook video via FFmpeg.

    Single audio input. Black background generated inside filter_complex.
    Waveform + text overlays. No separate lavfi -i (avoids duplicate source bug).
    """
    if dry_run:
        print(f"    [DRY-RUN] → {output_path.name}  ({width}×{height}, max {max_duration}s)")
        return True

    if not audio_path.exists():
        print(f"    SKIP: Audio not found: {audio_path}")
        return False

    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Actual clip duration = min(audio_duration, max_duration)
    audio_dur = _get_audio_duration(audio_path)
    actual_dur = min(audio_dur or max_duration, max_duration)

    # Text sizing
    title_size = max(24, height // 20)
    author_size = max(16, height // 35)
    brand_size = max(12, height // 55)

    waveform_h = height // 8
    waveform_y = height - waveform_h

    # Escape all text tokens
    title_esc = _esc(title)
    author_esc = _esc(author)
    brand_esc = _esc(brand)

    # Find a system font
    font_candidates = [
        "/System/Library/Fonts/Helvetica.ttc",
        "/System/Library/Fonts/SFNSText.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ]
    fontfile = next((f for f in font_candidates if Path(f).exists()), None)
    font_clause = f":fontfile={fontfile}" if fontfile else ""

    # Build filter_complex:
    #   [0:a] → source audio (single input)
    #   color source created inside complex → [bg]
    #   showwaves from [0:a] → [wave]
    #   overlay wave on bg → [base]
    #   drawtext chain → [v]  (named output — required for -map)
    filter_complex = (
        f"color=c=black:s={width}x{height}:r=24:d={actual_dur}[bg];"
        f"[0:a]showwaves=s={width}x{waveform_h}:mode=cline:rate=24:colors=white@0.35[wave];"
        f"[bg][wave]overlay=0:{waveform_y}[base];"
        f"[base]drawtext=text='{title_esc}':fontsize={title_size}:fontcolor=white"
        f":x=(w-tw)/2:y=h*0.18{font_clause}[t1];"
        f"[t1]drawtext=text='{author_esc}':fontsize={author_size}:fontcolor=0xD4A574"
        f":x=(w-tw)/2:y=h*0.55{font_clause}[t2];"
        f"[t2]drawtext=text='{brand_esc}':fontsize={brand_size}:fontcolor=0x888888"
        f":x=(w-tw)/2:y=h*0.65{font_clause}[v]"
    )

    cmd = [
        FFMPEG, "-y",
        "-i", str(audio_path),
        "-t", str(actual_dur),
        "-filter_complex", filter_complex,
        "-map", "[v]",
        "-map", "0:a",
        "-c:v", "libx264", "-preset", "veryfast", "-crf", "27",
        "-c:a", "aac", "-b:a", "128k",
        "-pix_fmt", "yuv420p",
        "-movflags", "+faststart",
        "-shortest",
        str(output_path),
    ]

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)

        if result.returncode == 0 and output_path.exists() and output_path.stat().st_size > 10_000:
            size_mb = output_path.stat().st_size / 1_048_576
            print(f"    OK ({size_mb:.1f} MB, {actual_dur:.0f}s) → {output_path.name}")
            return True

        # Fallback: minimal filter (no waveform) if showwaves fails
        print(f"    WARN: Full filter failed, trying minimal (no waveform)...")
        filter_simple = (
            f"color=c=black:s={width}x{height}:r=24:d={actual_dur}[bg];"
            f"[bg]drawtext=text='{title_esc}':fontsize={title_size}:fontcolor=white"
            f":x=(w-tw)/2:y=h*0.18{font_clause}[t1];"
            f"[t1]drawtext=text='{author_esc}':fontsize={author_size}:fontcolor=0xD4A574"
            f":x=(w-tw)/2:y=h*0.55{font_clause}[t2];"
            f"[t2]drawtext=text='{brand_esc}':fontsize={brand_size}:fontcolor=0x888888"
            f":x=(w-tw)/2:y=h*0.65{font_clause}[v]"
        )
        cmd_simple = [
            FFMPEG, "-y",
            "-i", str(audio_path),
            "-t", str(actual_dur),
            "-filter_complex", filter_simple,
            "-map", "[v]",
            "-map", "0:a",
            "-c:v", "libx264", "-preset", "veryfast", "-crf", "27",
            "-c:a", "aac", "-b:a", "128k",
            "-pix_fmt", "yuv420p",
            "-movflags", "+faststart",
            "-shortest",
            str(output_path),
        ]
        result2 = subprocess.run(cmd_simple, capture_output=True, text=True, timeout=300)
        if result2.returncode == 0 and output_path.exists() and output_path.stat().st_size > 10_000:
            size_mb = output_path.stat().st_size / 1_048_576
            print(f"    OK-fallback ({size_mb:.1f} MB, {actual_dur:.0f}s) → {output_path.name}")
            return True

        print(f"    ERROR: FFmpeg failed:\n{result2.stderr[-500:]}")
        return False

    except subprocess.TimeoutExpired:
        print("    ERROR: FFmpeg timed out (>300s)")
        return False
    except Exception as exc:
        print(f"    ERROR: {exc}")
        return False


def _generate_test_audio(path: Path, duration_s: int) -> bool:
    """Generate a sine wave placeholder MP3 for smoke-testing without real audio."""
    path.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        FFMPEG, "-y",
        "-f", "lavfi", "-i", f"sine=frequency=440:duration={duration_s}",
        "-c:a", "libmp3lame", "-b:a", "128k",
        str(path),
    ]
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    if r.returncode == 0:
        print(f"  Test audio: {path.name} ({duration_s}s sine wave)")
        return True
    print(f"  WARN: Could not generate test audio: {r.stderr[-200:]}")
    return False


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate teacher showcase videos.")
    parser.add_argument("--teacher", default=None, help="Run for one teacher only (e.g. ahjan)")
    parser.add_argument("--dry-run", action="store_true", help="Print plan without rendering")
    parser.add_argument(
        "--test-audio", action="store_true",
        help="Generate sine-wave placeholder audio before rendering (for smoke tests without real TTS)",
    )
    args = parser.parse_args()

    teachers = list(TEACHER_NAMES.keys())
    if args.teacher:
        if args.teacher not in TEACHER_NAMES:
            print(f"ERROR: Unknown teacher '{args.teacher}'. Valid: {', '.join(TEACHER_NAMES)}")
            return 1
        teachers = [args.teacher]

    print(f"Teachers: {teachers}")
    print(f"YouTube format:   {YOUTUBE_MAX_S}s ({YOUTUBE_MAX_S//60}min), 1920×1080, 16:9")
    print(f"Instagram format: {INSTAGRAM_MAX_S}s, 1080×1920, 9:16  (Instagram Reels)")
    print(f"Audio dir: {AUDIO_DIR}")
    print()

    # Optionally generate placeholder audio for smoke tests
    if args.test_audio and not args.dry_run:
        print("=== Generating placeholder audio ===")
        for tid in teachers:
            audio_topic = TEACHER_AUDIO_TOPIC[tid]
            _generate_test_audio(AUDIO_DIR / f"{tid}_{audio_topic}.mp3", YOUTUBE_MAX_S)
            _generate_test_audio(AUDIO_DIR / f"{tid}_{audio_topic}_hook.mp3", INSTAGRAM_MAX_S)
        print()

    ok = 0
    total = 0

    for tid in teachers:
        name = TEACHER_NAMES[tid]
        brand = TEACHER_BRAND[tid]
        audio_topic = TEACHER_AUDIO_TOPIC[tid]
        yt_topic = TEACHER_YT_TOPIC[tid]
        ig_topic = TEACHER_IG_TOPIC[tid]

        full_audio = AUDIO_DIR / f"{tid}_{audio_topic}.mp3"
        hook_audio = AUDIO_DIR / f"{tid}_{audio_topic}_hook.mp3"

        # ── YouTube 5-min (16:9, 1920×1080) ──────────────────────────
        yt_title = yt_topic.replace("_", " ").title()
        yt_out = YT_OUTPUT / f"{tid}_{yt_topic}_youtube_5min.mp4"
        print(f"  [{tid}] YouTube 5min — topic: {yt_topic}")
        total += 1
        if _render_video(full_audio, yt_out, yt_title, name, brand, 1920, 1080, YOUTUBE_MAX_S, args.dry_run):
            ok += 1

        # ── Instagram Reels 90s (9:16, 1080×1920) ────────────────────
        ig_title = ig_topic.replace("_", " ").title()
        ig_out = IG_OUTPUT / f"{tid}_{ig_topic}_instagram_90s.mp4"
        print(f"  [{tid}] Instagram 90s — topic: {ig_topic}")
        total += 1
        if _render_video(hook_audio, ig_out, ig_title, name, brand, 1080, 1920, INSTAGRAM_MAX_S, args.dry_run):
            ok += 1

    print()
    print("=" * 60)
    print(f"Generated: {ok}/{total} videos")
    if ok < total:
        missing_audio = [
            tid for tid in teachers
            if not (AUDIO_DIR / f"{tid}_{TEACHER_AUDIO_TOPIC[tid]}.mp3").exists()
        ]
        if missing_audio:
            print()
            print("Missing audio (run ElevenLabs TTS pipeline first):")
            for tid in missing_audio:
                at = TEACHER_AUDIO_TOPIC[tid]
                print(f"  {AUDIO_DIR}/{tid}_{at}.mp3          (YouTube 5min)")
                print(f"  {AUDIO_DIR}/{tid}_{at}_hook.mp3     (Instagram 90s)")
            print()
            print("To smoke-test without real audio, run with --test-audio:")
            print("  python3 scripts/video/generate_teacher_showcase_videos.py --test-audio")

    return 0 if ok == total else 1


if __name__ == "__main__":
    raise SystemExit(main())
