#!/bin/bash
# scripts/ops/worktree_cleanup_audit.sh
#
# Audit all git worktrees and classify each as KEEP / SAFE / VERIFY.
# DOES NOT DELETE ANYTHING. Generates two files:
#   /tmp/wt_cleanup.safe.sh    — ready-to-run commands for safely-removable worktrees
#   /tmp/wt_cleanup.verify.txt — list of worktrees that need manual review
#
# Safety rules:
#   KEEP    : current worktree, main repo, any uncommitted, any "main"-on-itself
#   SAFE    : pushed=synced AND merged-to-main=yes AND uncommitted=0
#           : OR pushed=synced AND uncommitted=0 AND age >= 14 days
#   VERIFY  : everything else (LOCAL_ONLY, diverged, recent, locked, detached)
#
# Locked worktrees: surfaced as VERIFY by default (operator decides whether to --force).
# Operator runs the .safe.sh file MANUALLY after reviewing it.

export PATH=/usr/bin:/bin:/usr/sbin:/sbin
set -u

CURRENT_WT="$(git rev-parse --show-toplevel 2>/dev/null)"
SAFE_OUT=/tmp/wt_cleanup.safe.sh
VERIFY_OUT=/tmp/wt_cleanup.verify.txt
KEEP_OUT=/tmp/wt_cleanup.keep.txt
SUMMARY_OUT=/tmp/wt_cleanup.summary.txt

NOW=$(date +%s)

# Reset outputs
: > "$SAFE_OUT"
: > "$VERIFY_OUT"
: > "$KEEP_OUT"
: > "$SUMMARY_OUT"

echo "#!/bin/bash" >> "$SAFE_OUT"
echo "# Auto-generated by worktree_cleanup_audit.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$SAFE_OUT"
echo "# Review every line before executing. Run with: bash $SAFE_OUT" >> "$SAFE_OUT"
echo "set -e" >> "$SAFE_OUT"
echo "" >> "$SAFE_OUT"

echo "verdict|reason|branch|sha7|age_d|uncommit|pushed|merged|locked|path" >> "$VERIFY_OUT"
echo "verdict|reason|branch|sha7|age_d|uncommit|pushed|merged|locked|path" >> "$KEEP_OUT"

# Parse git worktree list
git worktree list --porcelain 2>/dev/null > /tmp/wt_porcelain.txt
awk '
  /^worktree / {path=$2}
  /^HEAD / {sha=$2}
  /^branch / {branch=$2}
  /^locked/ {locked="locked"}
  /^detached/ {branch="(detached)"}
  /^$/ {
    if(path) print path "\t" branch "\t" sha "\t" (locked?locked:"unlocked")
    path=""; branch=""; sha=""; locked=""
  }
  END { if(path) print path "\t" branch "\t" sha "\t" (locked?locked:"unlocked") }
' /tmp/wt_porcelain.txt > /tmp/wt_parsed.tsv

TOTAL=0; KEEP_N=0; SAFE_N=0; VERIFY_N=0

while IFS=$'\t' read -r path branch sha lock; do
  [ -d "$path" ] || continue
  TOTAL=$((TOTAL+1))
  bn=$(echo "$branch" | sed 's@refs/heads/@@')
  [ -z "$bn" ] && bn="(detached)"

  # Fast checks first (no remote queries)
  uncommitted=$(git -C "$path" status --porcelain 2>/dev/null | wc -l | tr -d ' ')
  ts=$(git -C "$path" log -1 --format=%ct HEAD 2>/dev/null)
  age=$([ -n "$ts" ] && echo "$(( (NOW - ts) / 86400 ))" || echo "?")
  sha7=$(echo "$sha" | cut -c1-7)

  # Pushed?
  if [ "$bn" = "(detached)" ]; then
    pushed="n/a"
  elif git -C "$path" show-ref --verify --quiet "refs/remotes/origin/$bn" 2>/dev/null; then
    remote_sha=$(git -C "$path" rev-parse "refs/remotes/origin/$bn" 2>/dev/null)
    [ "$sha" = "$remote_sha" ] && pushed="synced" || pushed="diverged"
  else
    pushed="LOCAL_ONLY"
  fi

  # Merged into main?
  if git -C "$path" merge-base --is-ancestor "$sha" origin/main 2>/dev/null; then
    merged="yes"
  else
    merged="no"
  fi

  row="$bn|$sha7|$age|$uncommitted|$pushed|$merged|$lock|$path"

  # Classify
  verdict="VERIFY"; reason="unclassified"
  if [ "$path" = "$CURRENT_WT" ]; then
    verdict="KEEP"; reason="current worktree"
  elif [ "$path" = "/Users/ahjan/phoenix_omega" ]; then
    verdict="KEEP"; reason="main repo location"
  elif [ "$uncommitted" -gt 0 ]; then
    verdict="KEEP"; reason="has ${uncommitted} uncommitted line(s) — could lose work"
  elif [ "$lock" = "locked" ]; then
    # Locked worktrees get VERIFY even if synced — operator must approve --force
    if [ "$pushed" = "synced" ] && [ "$merged" = "yes" ]; then
      verdict="VERIFY"; reason="locked + synced + merged (safe to --force, but operator decides)"
    else
      verdict="VERIFY"; reason="locked (operator marked don't-touch)"
    fi
  elif [ "$pushed" = "LOCAL_ONLY" ]; then
    verdict="VERIFY"; reason="LOCAL_ONLY — would lose unpushed work"
  elif [ "$pushed" = "diverged" ]; then
    verdict="VERIFY"; reason="diverged from origin"
  elif [ "$pushed" = "synced" ] && [ "$merged" = "yes" ]; then
    verdict="SAFE"; reason="synced + merged to main"
  elif [ "$pushed" = "synced" ] && [ "$age" != "?" ] && [ "$age" -ge 14 ]; then
    verdict="SAFE"; reason="synced + ${age}d old"
  elif [ "$pushed" = "synced" ]; then
    verdict="VERIFY"; reason="synced but recent (${age}d) and not merged"
  elif [ "$pushed" = "n/a" ]; then
    verdict="VERIFY"; reason="detached HEAD"
  fi

  case "$verdict" in
    KEEP)
      echo "KEEP|$reason|$row" >> "$KEEP_OUT"
      KEEP_N=$((KEEP_N+1))
      ;;
    SAFE)
      echo "SAFE|$reason|$row" >> "$VERIFY_OUT"
      SAFE_N=$((SAFE_N+1))
      echo "# $reason — branch=$bn age=${age}d" >> "$SAFE_OUT"
      echo "git worktree remove '$path'" >> "$SAFE_OUT"
      echo "" >> "$SAFE_OUT"
      ;;
    VERIFY)
      echo "VERIFY|$reason|$row" >> "$VERIFY_OUT"
      VERIFY_N=$((VERIFY_N+1))
      ;;
  esac

  # Live progress to stderr
  printf "\r[%d/%d] %s — %s     " "$TOTAL" "$(wc -l < /tmp/wt_parsed.tsv | tr -d ' ')" "$verdict" "$bn" >&2
done < /tmp/wt_parsed.tsv

echo "" >&2

echo "git worktree prune" >> "$SAFE_OUT"

cat > "$SUMMARY_OUT" <<EOF
=== Worktree Cleanup Audit Summary ===
Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
Total worktrees: $TOTAL

  KEEP     : $KEEP_N   (current, main, or has uncommitted)
  SAFE     : $SAFE_N   (synced + merged or old)
  VERIFY   : $VERIFY_N  (manual review needed)

Files generated:
  $SAFE_OUT     — bash commands for SAFE-class worktree removals
  $VERIFY_OUT   — tsv of SAFE + VERIFY worktrees (review before --force)
  $KEEP_OUT     — tsv of KEEP-class worktrees (do not touch)

Next steps:
  1. Review:    column -t -s '|' $VERIFY_OUT | less
  2. Review:    cat $SAFE_OUT | less
  3. Execute SAFE removals only after review:
                bash $SAFE_OUT
  4. For VERIFY entries you want to clean:
       a. Synced+locked+merged: manually run
            git worktree remove --force <path>
       b. LOCAL_ONLY/diverged: FIRST push the branch to origin OR
            confirm the work is junk, then --force.
       c. Uncommitted: open the worktree, decide whether to commit or discard.
EOF

cat "$SUMMARY_OUT"
