#!/usr/bin/env python3
"""One-shot author for Q1 thesis-census topic overlays (2026-07-08 lane).

Patches config/planning/chapter_thesis_bank.yaml topics: block for the six
high-volume topics. Run once; idempotent merge by topic key.
"""
from __future__ import annotations

from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
BANK_PATH = REPO / "config" / "planning" / "chapter_thesis_bank.yaml"

INTENTS = [
    "establish_mask",
    "expose_cost",
    "destabilize_strategy",
    "reveal_hidden_belief",
    "confrontation",
    "somatic_repair",
    "relational_shift",
    "embodied_identity",
    "grounded_reframe",
    "witness_without_fix",
    "the_cost_named",
    "the_oldest_version",
    "the_body_after",
    "what_you_protected",
    "the_price_of_knowing",
    "moving_without_certainty",
    "the_relational_truth",
    "the_new_self",
    "carrying_forward",
    "the_open_hand",
]

# topic → engine → list of 20 theses (same order as INTENTS)
OVERLAYS: dict[str, dict[str, list[str]]] = {
    "burnout": {
        "comparison": [
            "You benchmark your stamina against colleagues who never slow down, and that scoreboard keeps you running past empty.",
            "Every comparison to harder-working peers quietly bills your body for a pace your nervous system was never sized to carry.",
            "Outperforming everyone around you has never prevented the collapse you can feel building underneath.",
            "You believe your value is proven only when your output exceeds everyone else's in the room.",
            "You see now that competing for who's most depleted is a contest that only accelerates burnout.",
            "Your exhausted body can register enough before your mind finishes comparing you to whoever's still going.",
            "People feel the scoreboard you keep of who handles more, and they've stopped asking you to stop.",
            "You are not the relentlessly productive version you measure yourself against; you are a person who needs rest.",
            "Burnout isn't a failure to keep up; it's an honest signal that the comparison pace was never sustainable.",
            "You can notice the urge to check who's doing more without using it to justify pushing harder.",
            "You've lost the ability to rest without scanning whether you've earned it against everyone else's output.",
            "You learned to outwork the room in a place where being the reliable one was the only way to matter.",
            "When you finally stop competing, your body won't trust the quiet; stillness feels like falling behind.",
            "Ranking yourself against harder workers protects you from admitting you're already past your limit.",
            "You can no longer pretend the exhaustion is temporary once you've seen it's fueled by the comparison.",
            "You set something down before you've outperformed anyone, because winning the depletion contest was never the point.",
            "They've felt themselves measured against your impossible pace, and the ranking has thinned the trust between you.",
            "The you that can stop before the room does is already appearing in moments you don't refill the gap.",
            "The urge to compare output will still rise, but you'll know exhaustion isn't a scoreboard, and that changes the race.",
            "You release the need to outlast everyone and keep the diligence that knows what actually deserves your energy.",
        ],
        "overwhelm": [
            "You keep absorbing more work because setting it down feels more dangerous than drowning under it at your desk.",
            "The flood of deliverables never recedes because you've made carrying everything the proof that you're still coping.",
            "Doing more has never made the workload smaller; it only taught you to hold your breath through another sprint.",
            "You believe if you push through this one more deadline, the pile will finally end.",
            "You see now that there is no bottom to the inbox, and there never was going to be.",
            "Your body has been bracing against a wave of tasks that already broke; it can learn to exhale.",
            "People feel like one more demand on you, so they stop asking, and you carry the overflow alone.",
            "You are not the container for every project; you are a person never meant to hold it all.",
            "Overwhelm at work isn't a failure to cope; it's the honest signal that the load was never sized for one person.",
            "You can feel the flood of too-much without acting on every request at once.",
            "You've lost the ability to feel finished, because the moment one thing ends three more arrive.",
            "You learned to carry everything where no one else would, and carrying became who you are at the office.",
            "When the urgency drains away, your body won't trust the quiet; stillness will feel like falling behind.",
            "Carrying it all protects everyone from discovering the workload was never actually manageable.",
            "You can no longer pretend the overwhelm is temporary; you've seen it's the design, not the exception.",
            "You set something down before you feel ready, because readiness never comes while you're drowning in tasks.",
            "They've learned not to add to your plate, and in protecting you they've stopped reaching you.",
            "The you that can let a thing stay undone is already appearing when you don't refill the space.",
            "The flood will still come, but you'll know you don't have to catch every drop, and that changes the water.",
            "You release the need to hold it all and keep the power to choose what actually deserves your hands.",
        ],
        "grief": [
            "You've been still and small to honor what burnout took from you, and that stillness became your identity.",
            "Honoring what you lost to overwork through absence means you're also absent from your own life.",
            "Stillness isn't honoring what exhaustion cost you; it's letting loss define the rest.",
            "You believe your loyalty is measured in how much of yourself you've been willing to forfeit.",
            "You're aware now that you chose to stop living fully when the pace became unsustainable.",
            "The body grieves the life burnout took differently than the mind; it holds what can't be said.",
            "Your withdrawal after depletion has convinced people that you prefer to be left alone.",
            "You are not an absence at work; you are a person who was living in one.",
            "Your grief for who you were before burnout is evidence of what mattered; don't call it weakness.",
            "Loss can be real without requiring you to become smaller in response to exhaustion.",
            "You've lost the version of you that had energy for joy, and that absence has a shape.",
            "You learned to be still from a body that needed you to stop; stillness was service to survival.",
            "The loosening in your chest after burnout will feel like betrayal before it feels like relief.",
            "Your stillness protects others from the burden of your aliveness returning.",
            "You know now that your withdrawal is a choice, and that means you can unchosen it.",
            "You live while grief for your former capacity is still fresh, before it becomes safe to live.",
            "They've adjusted to you being unavailable, and that adjustment has become permanent.",
            "The person living fully is already present in the moments when pain doesn't silence you.",
            "The grief for what burnout took doesn't leave; you become someone who can carry it without letting it carry you.",
            "You release the paralysis and keep the love that made you give so much.",
        ],
    },
    "anxiety": {
        "comparison": [
            "You scan the room for who seems calmer and measure your anxiety against their apparent ease.",
            "Comparing your fear to others' composure is expensive, and you're the only one paying in sleepless nights.",
            "Watching who's less anxious than you has never made your nervous system settle.",
            "You believe the only safety is being as unruffled as everyone else appears to be.",
            "You see now that the contest for who's least afraid is one you invented, and you're losing on purpose.",
            "Your body can learn to stay present before your mind finishes ranking your anxiety against theirs.",
            "Your need to know if you're handling it better or worse keeps them from meeting the fear with you.",
            "You are not your anxiety ranking; you are the one whose nervous system is simply more visible.",
            "Anxiety isn't weakness on a comparison chart; it's a sensitivity that needs care, not a score to minimize.",
            "You can notice the urge to measure your fear against theirs without needing to win the calmness contest.",
            "You've lost the ability to be surprised by ease because you're always checking who seems to have more of it.",
            "You learned to compare your alarm level early, in a place where being the least reactive kept you safe.",
            "When the anxiety softens, the room feels strangely flat before it feels free—you're not scanning for who's calmer.",
            "Ranking your fear against others protects you from the grief underneath—the thing you're actually afraid of.",
            "You can no longer pretend the comparing is harmless once you've felt what it costs your nervous system.",
            "You let the anxiety be present before you've matched anyone else's composure, because that was never the exit.",
            "They've learned to reassure you that you're not the most anxious person in the room—and that has become a job.",
            "The you that isn't scanning for who's steadier is already flickering into existence in moments you're not watching.",
            "The urge to compare your alarm will still rise, but you'll know fear isn't a ranking, and that quiets the contest.",
            "You release the need to be least afraid in the room and keep the attunement that taught you to read danger early.",
        ],
        "false_alarm": [
            "The hypervigilance you've built around what could go wrong is so familiar you can't feel it anymore.",
            "The protection of constant scanning is expensive, and you're the only one paying.",
            "Your preparation for catastrophe has prepared you for nothing that actually happens.",
            "You believe the only safety is total knowledge, total control over every outcome.",
            "You can no longer deny that your fear is your own creation.",
            "Your body can learn to trust before your thoughts finish cataloging every threat.",
            "Your need for reassurance is actually a need to be believed about your fear.",
            "You are not your anxiety; you are the one anxiety is happening to.",
            "Your anxiety isn't a character flaw; it's a sensitivity that needs different care.",
            "The anxiety can be present without requiring you to solve it.",
            "You've lost the capacity to be surprised by joy because you're always braced.",
            "Your fear learned in a house where things actually happened without warning.",
            "Calm is unfamiliar to your nervous system; it almost feels like danger.",
            "Your fear protects you from the grief underneath—the thing you're actually afraid of.",
            "Awareness that your fear is self-generated is a burden you can't put down.",
            "You move toward what you need while the terror insists it's not safe yet.",
            "They've learned that reassuring you is an endless job with no exit.",
            "The you that isn't afraid is flickering into existence in moments you're not watching for it.",
            "The fear will still arrive, but you'll know it's not the truth, and that changes everything.",
            "You release the belief that safety requires knowing everything and keep the wisdom you've earned.",
        ],
    },
    "boundaries": {
        "comparison": [
            "You measure your limits against people who seem to give endlessly, and that comparison makes every no feel like failure.",
            "Every yardstick of who gives more quietly bills you for boundaries you were never taught were allowed.",
            "Matching others' availability has never made your exhaustion go away; it only enlarged what you're expected to carry.",
            "You believe you're only good if your generosity outlasts everyone else's on the scoreboard.",
            "You see now that the contest for who's most selfless is a game where everyone loses their limits.",
            "Your body can feel the edge of enough before your mind finishes comparing your generosity to theirs.",
            "They feel measured against your standard of self-sacrifice, and the ranking has made honest limits feel like betrayal.",
            "You are not the one who never says no; you are a person who learned that limits looked selfish next to theirs.",
            "Boundaries aren't selfishness in a generosity contest; they're how a person stays available for what matters.",
            "You can notice the urge to rank your giving against theirs without letting it erase your limit.",
            "You've lost the ability to receive without checking whether you've given as much as everyone else.",
            "You learned to measure your worth by out-giving others in a place where saying no meant being cast out.",
            "When you finally hold a limit, the quiet feels like selfishness before it feels like relief.",
            "Comparing your generosity protects you from the exposure of admitting you have limits like everyone else.",
            "You can no longer pretend saying yes is free once you've seen what the comparison costs your body.",
            "You set a boundary before you've out-given anyone, because winning the sacrifice contest was never the point.",
            "They've felt themselves ranked by how much you'll absorb, and the scoreboard has thinned honest connection.",
            "The you that can say no without measuring against their yes is already surfacing when you forget to keep score.",
            "The urge to compare your generosity will still rise, but you'll know limits aren't selfish, and that changes what you carry.",
            "You release the need to out-give everyone and keep the care that knows what actually deserves your energy.",
        ],
        "shame": [
            "You learned to disappear into usefulness before anyone could find fault with your limits.",
            "Usefulness is slowly consuming the parts of you that have nothing left to offer.",
            "Disappearing has never made you safe, only made you disappear.",
            "You believe if anyone saw the real you needing rest, you wouldn't be chosen.",
            "The invisibility you've maintained around your limits is a choice, not a destiny.",
            "Feeling is the path back to yourself when thinking got you lost in people-pleasing.",
            "You've been relating from a place of apology for having needs, and they've learned to accept it.",
            "You are not small; you are the one who learned to make yourself small to avoid disappointing anyone.",
            "Your need to be seen needing something isn't arrogance; it's necessary to being human.",
            "You can see the impulse to disappear when you want to say no without disappearing.",
            "You've lost the chance to be ordinary with limits, and ordinariness was where safety was.",
            "You disappeared because the cost of being seen needing something was higher than the cost of hiding.",
            "The absence of judgment when you hold a boundary feels like a trap; you're waiting for them to notice you're present.",
            "Your invisibility protects you from the possibility of being truly rejected for having limits.",
            "You've seen yourself disappearing into yes and can't pretend it's necessary anymore.",
            "You take up space with a limit while part of you still insists you shouldn't be visible needing anything.",
            "They've experienced your absence when you needed rest and learned not to expect your presence.",
            "The visible version of you—the one who doesn't apologize for a boundary—appears when you're not guarding.",
            "The impulse to disappear will still be there; you'll choose visibility with limits anyway.",
            "You release the invisibility and keep the sensitivity that taught you to be careful with others.",
        ],
        "overwhelm": [
            "You keep absorbing others' needs because setting them down feels more dangerous than drowning under them.",
            "The flood of requests never recedes because you've made carrying everyone the proof that you're good.",
            "Doing more for others has never made the wave smaller; it only taught you to hold your breath longer.",
            "You believe if you handle this one more ask, the pile of obligations will finally end.",
            "You see now that there is no bottom to what people expect, and there never was going to be.",
            "Your body has been bracing against a wave of other people's needs that already broke.",
            "People feel like one more demand, so they stop asking directly, and you carry it all alone.",
            "You are not the container for everyone's needs; you are a person never meant to hold it all.",
            "Overwhelm from over-giving isn't a failure to cope; it's the honest signal that the load was never yours alone.",
            "You can feel the flood of too many asks without acting on every one at once.",
            "You've lost the ability to feel finished helping, because the moment one need ends three more arrive.",
            "You learned to carry everything for others where no one else would, and carrying became who you are.",
            "When the urgency to please drains away, your body won't trust the quiet; stillness feels like letting people down.",
            "Carrying it all protects everyone from discovering your limits were never actually infinite.",
            "You can no longer pretend the overwhelm from yes is temporary; you've seen it's the design.",
            "You set a boundary down before you feel ready, because readiness never comes while you're drowning in requests.",
            "They've learned not to add to your plate, and in protecting you they've stopped reaching you honestly.",
            "The you that can let a request stay unmet is already appearing when you don't refill the space.",
            "The flood of asks will still come, but you'll know you don't have to catch every one.",
            "You release the need to hold everyone's needs and keep the power to choose what actually deserves your hands.",
        ],
    },
    "overthinking": {
        "comparison": [
            "You replay how others would decide because measuring your thinking against theirs feels safer than trusting your own.",
            "Every comparison to sharper minds quietly bills you for analysis loops that never deliver a verdict.",
            "Thinking one more comparison through has never closed the loop; it only adds another mind to outperform.",
            "You believe the only correct answer is whichever one the smartest person in the room would land on.",
            "You see now that the mental contest for who's thought it through best is a loop that eats the present.",
            "Your body can drop out of the ranking spiral before your mind finishes comparing your conclusion to theirs.",
            "You take the comparison loop into every conversation, so people meet your second-guessing instead of you.",
            "You are not the loop that measures your thinking against everyone else's; you are the one underneath it.",
            "Overthinking isn't stupidity; it's a mind trying to win a comparison it was never meant to enter.",
            "You can watch the urge to benchmark your thinking without climbing on for another revolution.",
            "You've lost the quiet between thoughts, the only place where a decision yours could live without a rival.",
            "You learned to outthink the room early, in a place where being the careful one kept you from being wrong aloud.",
            "When the loop finally stops, the silence feels less like peace and more like not having checked everyone's answer.",
            "Ranking your analysis protects you from the helplessness of choosing without a consensus to hide behind.",
            "You can no longer believe the next comparison will be the one that finally resolves it.",
            "You choose before the loop ranks every option against theirs, because consensus was never going to hand you certainty.",
            "They've learned to wait out your comparisons, and waiting has slowly become a kind of distance.",
            "The you that can let a thought pass uncaught is already here in the moments you don't chase another benchmark.",
            "The loop will still start, but you'll know your thinking doesn't need to beat theirs, and that turns spiral into weather.",
            "You release the need to think your way past everyone else and keep the discernment that lives outside the contest.",
        ],
        "spiral": [
            "You replay every angle because thinking it through one more time feels safer than letting it rest.",
            "The loop costs you the present; you live inside the rehearsal instead of the life.",
            "Thinking harder has never closed the loop; it only digs the same groove deeper.",
            "You believe that if you think it through enough times, you'll finally find the exit.",
            "You see now that the loop has no exit inside itself; the way out is to stop circling.",
            "Your body can drop out of the loop your mind keeps running, one slow breath at a time.",
            "You take the loop into every conversation, so people meet your worry instead of you.",
            "You are not the loop; you are the one the loop keeps trying to capture.",
            "The spiral isn't proof you're broken; it's a mind trying to solve safety with thought.",
            "You can watch the loop start without climbing on for another revolution.",
            "You've lost the quiet between thoughts, the only place where rest was ever going to live.",
            "You learned to loop in a place where staying one step ahead of the danger was survival.",
            "When the loop finally stops, the silence will feel less like peace and more like a held breath.",
            "The loop protects you from the helplessness of a problem that thinking can't actually solve.",
            "You can no longer believe the next loop will be the one that finally resolves it.",
            "You act before the loop resolves, because the loop was never going to hand you certainty.",
            "They've learned to wait out your loops, and waiting has slowly become a kind of distance.",
            "The you that can let a thought pass uncaught is already here in the moments you don't chase it.",
            "The loop will still start, but you'll know you can step off it, and that turns the spiral into passing weather.",
            "You release the need to think your way to certainty and keep the clarity that lives outside the loop.",
        ],
        "false_alarm": [
            "The hypervigilance you've built around worst-case scenarios is so familiar you can't feel it anymore.",
            "The protection of catastrophizing is expensive, and you're the only one paying.",
            "Your preparation for every outcome has prepared you for nothing that actually happens.",
            "You believe the only safety is total knowledge, total control over what might go wrong.",
            "You can no longer deny that your fear is your own creation.",
            "Your body can learn to trust before your thoughts finish running every scenario.",
            "Your need for reassurance is actually a need to be believed about your fear.",
            "You are not your anxiety; you are the one the what-ifs are happening to.",
            "Your catastrophizing isn't a character flaw; it's a sensitivity that needs different care.",
            "The anxiety can be present without requiring you to solve every scenario.",
            "You've lost the capacity to be surprised by joy because you're always braced for the next what-if.",
            "Your fear learned in a house where things actually happened without warning.",
            "Calm is unfamiliar to your nervous system; it almost feels like danger.",
            "Your fear protects you from the helplessness underneath—the thing you're actually afraid of.",
            "Awareness that your fear is self-generated is a burden you can't put down.",
            "You decide before every scenario feels resolved, because the what-ifs were never going to hand you certainty.",
            "They've learned to wait out your mental rehearsals, and waiting has slowly become a kind of distance.",
            "The you that can let a conclusion stand unverified is already here in moments you don't chase another scenario.",
            "The what-ifs will still arrive, but you'll know they aren't the truth, and that changes the loop.",
            "You release the need to mentally rehearse every outcome and keep the discernment that survives without a verdict.",
        ],
    },
    "self_worth": {
        "comparison": [
            "You scan every room for evidence that you belong, and the scoreboard in your chest never shows you winning long enough to rest.",
            "Every ranking quietly bills you for a self you never get to simply inhabit without a rival beside it.",
            "Winning the comparison never quiets the not-enough feeling; the scoreboard just resets with a new person to fall short of.",
            "You believe your worth is a placement on a ladder, and you can only rest once you're unquestionably at the top.",
            "You see now that the contest for enough-ness is one you invented, and you've been disqualifying yourself on purpose.",
            "Your body can feel like enough in a room before your mind finishes placing you on the ladder.",
            "You rank the people you love against each other, and they feel the scoreboard between you.",
            "You are not your rank; you are the one who exists whether or not anyone is keeping score.",
            "Self-worth isn't a placement on a chart; it's what remains when you stop asking where you landed.",
            "You can notice the urge to rank yourself without finishing the measurement.",
            "You've lost the ability to enjoy what's yours, because you only see it next to someone else's more.",
            "You learned to measure yourself early, in a place where rank decided who was safe to be seen.",
            "When you stop measuring, the room feels strangely flat before it feels free.",
            "Ranking yourself protects you from the harder question of what you'd want if no one were watching.",
            "You can no longer pretend the comparing is harmless once you've felt what it costs your sense of enough.",
            "You choose your own direction before you've won the comparison, because placement was never the point.",
            "They've felt themselves measured against others through you, and the ranking has thinned the trust between you.",
            "The you that can be glad for someone else is already surfacing when you forget to keep score.",
            "The urge to compare will still rise, but you'll know your worth isn't on the scoreboard, and that quiets the whole game.",
            "You release the need to win the comparison and keep the discernment that knows what is actually yours.",
        ],
        "shame": [
            "You learned to disappear into usefulness before anyone could find fault with who you are.",
            "Usefulness is slowly consuming the parts of you that have nothing to offer.",
            "Disappearing has never made you safe, only made you disappear.",
            "You believe if anyone saw the real you, you wouldn't be chosen.",
            "The invisibility you've maintained is a choice, not a destiny.",
            "Feeling is the path back to yourself when thinking got you lost.",
            "You've been relating from a place of apology, and they've learned to accept it.",
            "You are not small; you are the one who learned to make yourself small.",
            "Your need to be seen isn't arrogance; it's necessary to being human.",
            "You can see the impulse to disappear without disappearing.",
            "You've lost the chance to be ordinary, and ordinariness was where safety was.",
            "You disappeared because the cost of being seen was higher than the cost of hiding.",
            "The absence of judgment feels like a trap; you're waiting for the other person to notice you're present.",
            "Your invisibility protects you from the possibility of being truly rejected.",
            "You've seen yourself disappearing and can't pretend it's necessary anymore.",
            "You take up space while part of you still insists you shouldn't be visible.",
            "They've experienced your absence and learned not to expect your presence.",
            "The visible version of you—the one who doesn't apologize for existing—appears when you're not guarding.",
            "The impulse to disappear will still be there; you'll choose visibility anyway.",
            "You release the invisibility and keep the sensitivity that taught you to be careful.",
        ],
    },
    "grief": {
        "grief": [
            "You've been still and small to honor who you lost, and that stillness became your whole identity.",
            "Honoring loss through withdrawal means you're also absent from the life they would have wanted for you.",
            "Stillness isn't honoring what was lost; it's letting grief define every room you enter.",
            "You believe your love is measured in how much of your aliveness you've been willing to forfeit.",
            "You're aware now that you chose to stop living while grief is still fresh.",
            "The body grieves differently than the mind; it holds what no words can carry about who is gone.",
            "Your withdrawal has convinced people that you prefer to be left alone with your pain.",
            "You are not an absence; you are a person who was living inside one.",
            "Your pain is evidence of what mattered to you; don't call grief weakness.",
            "Loss can be real without requiring you to become smaller in response.",
            "You've lost the companion who understood your language before any words were spoken.",
            "You learned to be still from someone who needed you to be; stillness was service to love.",
            "The loosening in your chest will feel like betrayal of them before it feels like relief.",
            "Your stillness protects others from the burden of your aliveness returning.",
            "You know now that your withdrawal is a choice, and that means you can unchosen it.",
            "You live while grief is still fresh, before it becomes safe to live.",
            "They've adjusted to you being unavailable, and that adjustment has become permanent.",
            "The person living fully is already present in the moments when pain doesn't silence you.",
            "The grief doesn't leave; you become someone who can carry it without letting it carry you.",
            "You release the paralysis and keep the love that made you still.",
        ],
        "watcher": [
            "Your constant vigilance over every reminder of loss keeps you performing grief when you're already exhausted.",
            "Your body is paying the price of watching for signs of them everywhere your mind thinks is honoring.",
            "All your monitoring for their presence hasn't actually prevented the loss you fear reliving.",
            "You believe your value as someone who loved them lives in how vigilantly you still guard the memory.",
            "You see now that the system of watching for them is turning against your capacity to live.",
            "Your nervous system knows the truth about grief before your mind will admit you're allowed to rest.",
            "Your vigilance makes genuine connection impossible; they feel managed, not met in your mourning.",
            "You are not the eternally watchful mourner you've been trying to be.",
            "Your body's depletion from grief isn't weakness; it's information about what was unsustainable.",
            "You can observe the urge to scan for them without acting on every impulse.",
            "You've lost the ability to rest without guilt, and rest is what grief recovery needs most.",
            "That vigilance over loss came from somewhere real; it was once the smartest thing you could do.",
            "Your body doesn't know what to do with the space where urgency about them used to be.",
            "Your vigilance protects everyone around you from ever having to need you while you grieve.",
            "You can no longer unsee that you're building your own collapse through vigilance over loss.",
            "You must stop managing grief before you feel safe; safety comes after the stopping.",
            "They've felt controlled by your management of mourning; they've learned to mistrust your care.",
            "The person who can rest without betraying them is already showing up in brief moments.",
            "You'll manage your grief differently now; not because you've stopped caring, but because you've learned to care for yourself.",
            "You release the need for perfect vigilance over loss and keep the ability to honor what mattered.",
        ],
    },
}


def _build_topics_block() -> dict:
    topics: dict = {}
    for topic_id, engines in OVERLAYS.items():
        topics[topic_id] = {}
        for engine, theses in engines.items():
            if len(theses) != len(INTENTS):
                raise ValueError(f"{topic_id}/{engine}: expected {len(INTENTS)} theses, got {len(theses)}")
            for intent, thesis in zip(INTENTS, theses):
                topics[topic_id].setdefault(intent, {})[engine] = thesis
    return topics


def patch_bank() -> None:
    data = yaml.safe_load(BANK_PATH.read_text(encoding="utf-8")) or {}
    existing = data.get("topics") or {}
    new_topics = _build_topics_block()
    for topic_id, block in new_topics.items():
        existing[topic_id] = block
    data["topics"] = existing
    # bump header comment
    text = BANK_PATH.read_text(encoding="utf-8")
    if "Last updated: 2026-07-08" not in text:
        text = text.replace("Last updated: 2026-06-30", "Last updated: 2026-07-08")
    header, _ = text.split("\nintents:", 1)
    body = yaml.dump(
        {"intents": data["intents"], "topics": data["topics"]},
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
        width=1000,
    )
    BANK_PATH.write_text(header.rstrip() + "\n\n" + body, encoding="utf-8")


if __name__ == "__main__":
    patch_bank()
    print(f"Patched {BANK_PATH}")
