#!/usr/bin/env python3
"""Asset-attach pipeline — make assembled book/audio/manga files downloadable.

The D1 `sku.asset_url` already holds the R2 key (`assets/<sku_id>.<ext>`); the file
at that key simply does not exist until a real asset is assembled (the catalog/
cart/checkout/covers are live without it — only the download is gated). This script
reads a manifest of assembled files (sku_id -> local path) and emits:

  --out-plan  TSV (sku_id, r2_key, local_path) for a CI step to run
              `wrangler r2 object put pearl-prime-storefront-assets/<r2_key> --file <local_path> --remote`
  --out-sql   `UPDATE sku SET status='active' ...` for the attached SKUs
              (applied via `wrangler d1 execute pearl_prime_storefront --remote --file <out-sql>`)

Run it as each assembly track drops files (books = Pearl_Prime production-gate;
audiobooks = CosyVoice/audio track; manga = Qwen-Image on Pearl Star). It reports an
HONEST count of SKUs-with-real-files — 0 today, climbing as the tracks deliver.

Manifest TSV (one per line):  <sku_id><TAB><local_path>     ('#' comments allowed)
Pure stdlib; no paid LLM API.
"""
from __future__ import annotations

import argparse
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DEFAULT_EXT = {"book": "epub", "audiobook": "m4b", "manga": "pdf", "music": "mp3"}


def product_type(sku_id):
    return sku_id.split("_", 1)[0]


def main(argv=None):
    ap = argparse.ArgumentParser(description="Attach assembled asset files to storefront SKUs.")
    ap.add_argument("--manifest", help="TSV: <sku_id>\\t<local_path> per assembled file")
    ap.add_argument("--out-plan", default="artifacts/storefront/asset_upload_plan.tsv")
    ap.add_argument("--out-sql", default="storefront/seeds/asset_attach.sql")
    args = ap.parse_args(argv)

    rows = []
    if args.manifest and Path(args.manifest).exists():
        for line in Path(args.manifest).read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) < 2:
                continue
            sku_id, path = parts[0].strip(), parts[1].strip()
            if not Path(path).exists():
                print(f"  SKIP (missing file): {sku_id} -> {path}")
                continue
            ext = Path(path).suffix.lstrip(".").lower() or DEFAULT_EXT.get(product_type(sku_id), "bin")
            rows.append((sku_id, f"assets/{sku_id}.{ext}", path))

    plan = Path(args.out_plan)
    plan.parent.mkdir(parents=True, exist_ok=True)
    with plan.open("w", encoding="utf-8") as fh:
        fh.write("sku_id\tr2_key\tlocal_path\n")
        for sku_id, key, path in rows:
            fh.write(f"{sku_id}\t{key}\t{path}\n")

    ts = int(time.time())
    out_sql = Path(args.out_sql)
    out_sql.parent.mkdir(parents=True, exist_ok=True)
    with out_sql.open("w", encoding="utf-8") as fh:
        fh.write("-- generated by scripts/storefront/attach_assets.py — mark attached SKUs active\n")
        for sku_id, _, _ in rows:
            fh.write(f"UPDATE sku SET status='active', updated_at={ts} WHERE sku_id='{sku_id}';\n")

    print(f"SKUs with real files queued for attach: {len(rows)}")
    print(f"  upload plan -> {args.out_plan}")
    print(f"  status SQL  -> {args.out_sql}")
    if not rows:
        print("  (0 — assembly tracks have produced no EPUB/M4B/PNG files yet; rerun as they land, Waystream first)")
    else:
        print("  CI: per plan row -> wrangler r2 object put pearl-prime-storefront-assets/<r2_key> --file <local_path> --remote")
        print(f"      then       -> wrangler d1 execute pearl_prime_storefront --remote --file {args.out_sql}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
