"""Wave 2 universal quotes — stoic, nature, seasons, endurance (grief/depression secular-safe)."""
from __future__ import annotations

from scripts.research.quote_bank_wave1.corpus_stoic import STOIC_UNIVERSAL

W2_UNIVERSAL = [
    {
        "quote_id": "quote_w2_univ_seneca_letter_99_v01",
        "text": "Sometimes even to live is an act of courage.",
        "text_en": "Sometimes even to live is an act of courage.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 78.2",
        "verified_via": "Seneca Ep. 78.2; Loeb Gummere",
        "public_domain": "y",
        "topic_keys": ["depression", "grief", "courage"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "Endurance/consolation without religious framing",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_w2_univ_marcus_meditations_05_10_v01",
        "text": "Nature which governs the whole will soon change all things which you see, and out of their substance make other things.",
        "text_en": "Nature which governs the whole will soon change all things which you see, and out of their substance make other things.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations V.13 (tr. Long 1862)",
        "verified_via": "Meditations 5.13",
        "public_domain": "y",
        "topic_keys": ["grief", "depression", "somatic_healing"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "Nature/change cycle — secular consolation",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_w2_univ_seneca_letter_104_v02",
        "text": "It is a rough road that leads to the heights of greatness.",
        "text_en": "It is a rough road that leads to the heights of greatness.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 104.10",
        "verified_via": "Seneca Ep. 104",
        "public_domain": "y",
        "topic_keys": ["courage", "grief", "depression"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_w2_univ_epictetus_enchiridion_16_v01",
        "text": "When you see anyone weeping in grief, take care that the appearance does not hurry you away with it.",
        "text_en": "When you see anyone weeping in grief, take care that the appearance does not hurry you away with it.",
        "author": "Epictetus",
        "primary_source": "Enchiridion §16 (tr. Carter 1758)",
        "verified_via": "Epict. Ench. 16",
        "public_domain": "y",
        "topic_keys": ["grief", "compassion_fatigue", "boundaries"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_w2_univ_marcus_meditations_04_48_v01",
        "text": "Consider that men will do the same things even though you should burst with rage.",
        "text_en": "Consider that men will do the same things even though you should burst with rage.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations IV.12 (tr. Long)",
        "verified_via": "Meditations 4.12",
        "public_domain": "y",
        "topic_keys": ["boundaries", "compassion_fatigue", "social_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_w2_univ_seneca_letter_9_v01",
        "text": "Associate with those who will make a better man of you.",
        "text_en": "Associate with those who will make a better man of you.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 6.4",
        "verified_via": "Seneca Ep. 6",
        "public_domain": "y",
        "topic_keys": ["boundaries", "self_worth"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_w2_univ_epictetus_enchiridion_33_v01",
        "text": "As soon as you lay hold of yourself and know where you are, you will find yourself in all the labors of your life.",
        "text_en": "As soon as you lay hold of yourself and know where you are, you will find yourself in all the labors of your life.",
        "author": "Epictetus",
        "primary_source": "Enchiridion §33",
        "verified_via": "Epict. Ench. 33",
        "public_domain": "y",
        "topic_keys": ["mindfulness", "somatic_healing"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_w2_univ_marcus_meditations_07_47_v01",
        "text": "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it.",
        "text_en": "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations VIII.47 (tr. Long)",
        "verified_via": "Meditations 8.47",
        "public_domain": "y",
        "topic_keys": ["financial_stress", "social_anxiety", "sleep_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_w2_univ_seneca_letter_56_v01",
        "text": "We suffer more often in imagination than in reality.",
        "text_en": "We suffer more often in imagination than in reality.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 13.4",
        "verified_via": "Seneca Ep. 13",
        "public_domain": "y",
        "topic_keys": ["sleep_anxiety", "financial_stress", "social_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_w2_univ_lao_tzu_ddj_23_v01",
        "text": "希言自然。",
        "text_en": "Sparse words belong to nature.",
        "author": "Laozi",
        "primary_source": "Dao De Jing Chapter 23",
        "verified_via": "ctext.org dao-de-jing ch.23",
        "public_domain": "y",
        "topic_keys": ["mindfulness", "boundaries", "somatic_healing"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_w2_univ_zhuangzi_autumn_v01",
        "text": "彼亦一是非，此亦一是非。",
        "text_en": "That has its right and wrong; this has its right and wrong.",
        "author": "Zhuangzi",
        "primary_source": "Zhuangzi, 'Qi Wulun' (齊物論)",
        "verified_via": "ctext.org zhuangzi",
        "public_domain": "y",
        "topic_keys": ["self_worth", "compassion_fatigue", "boundaries"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_w2_univ_marcus_meditations_06_15_v01",
        "text": "The universe is change; our life is what our thoughts make it.",
        "text_en": "The universe is change; our life is what our thoughts make it.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations IV.3 (tr. Long)",
        "verified_via": "Meditations 4.3",
        "public_domain": "y",
        "topic_keys": ["grief", "depression", "mindfulness"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "Seasons/change — grief/depression consolation",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_w2_univ_seneca_consolation_v01",
        "text": "Light griefs are loquacious, but the great are dumb.",
        "text_en": "Light griefs are loquacious, but the great are dumb.",
        "author": "Seneca",
        "primary_source": "Troades 510 / Consolatio ad Marciam themes (Seneca grief corpus)",
        "verified_via": "Seneca Consolatio ad Marciam; Euripides Troades via Seneca",
        "public_domain": "y",
        "topic_keys": ["grief", "depression"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "Secular grief consolation",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_w2_univ_epictetus_enchiridion_01_v01",
        "text": "Some things are in our control and others not.",
        "text_en": "Some things are in our control and others not.",
        "author": "Epictetus",
        "primary_source": "Enchiridion §1",
        "verified_via": "Epict. Ench. 1",
        "public_domain": "y",
        "topic_keys": ["boundaries", "compassion_fatigue", "courage"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_w2_univ_marcus_meditations_09_06_v01",
        "text": "When you arise in the morning, think of what a precious privilege it is to be alive.",
        "text_en": "When you arise in the morning, think of what a precious privilege it is to be alive.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations IX.6",
        "verified_via": "Meditations 9.6",
        "public_domain": "y",
        "topic_keys": ["depression", "grief", "self_worth"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_w2_univ_seneca_letter_107_v01",
        "text": "Many things have fallen only to rise higher.",
        "text_en": "Many things have fallen only to rise higher.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 107.11",
        "verified_via": "Seneca Ep. 107",
        "public_domain": "y",
        "topic_keys": ["grief", "depression", "courage"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "Endurance/nature cycle",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_w2_univ_marcus_meditations_04_49_v01",
        "text": "Be like the rocky headland on which the waves constantly break.",
        "text_en": "Be like the rocky headland on which the waves constantly break.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations IV.49",
        "verified_via": "Meditations 4.49",
        "public_domain": "y",
        "topic_keys": ["courage", "compassion_fatigue", "somatic_healing"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "Nature metaphor",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_w2_univ_epictetus_discourses_01_01_v01",
        "text": "Freedom is the name of virtue.",
        "text_en": "Freedom is the name of virtue.",
        "author": "Epictetus",
        "primary_source": "Discourses I.1.23",
        "verified_via": "Epict. Diss. 1.1.23",
        "public_domain": "y",
        "topic_keys": ["boundaries", "self_worth"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_w2_univ_seneca_letter_66_v01",
        "text": "It is not the man who has too little, but the man who craves more, that is poor.",
        "text_en": "It is not the man who has too little, but the man who craves more, that is poor.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 2.6",
        "verified_via": "Seneca Ep. 2",
        "public_domain": "y",
        "topic_keys": ["financial_stress", "boundaries"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_w2_univ_marcus_meditations_12_17_v01",
        "text": "If it is not right, do not do it; if it is not true, do not say it.",
        "text_en": "If it is not right, do not do it; if it is not true, do not say it.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations XII.17",
        "verified_via": "Meditations 12.17",
        "public_domain": "y",
        "topic_keys": ["boundaries", "courage", "self_worth"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
]

# Re-tag wave1 stoics for wave2 topics where thematically appropriate
_W2_RETAGGED = []
for q in STOIC_UNIVERSAL:
    extra_topics = []
    qid = q["quote_id"]
    if "seneca_letter_13" in qid or "imagination" in q.get("text_en", "").lower():
        extra_topics.extend(["sleep_anxiety", "financial_stress"])
    if "marcus_meditations_08_47" in qid or "estimate" in q.get("text_en", "").lower():
        extra_topics.extend(["depression", "self_worth"])
    if "epictetus_enchiridion_01" in qid:
        extra_topics.extend(["boundaries", "compassion_fatigue"])
    if "lao_tzu" in qid or "zhuangzi" in qid:
        extra_topics.extend(["mindfulness", "somatic_healing"])
    if "marcus_meditations_07_22" in qid or "present" in q.get("text_en", "").lower():
        extra_topics.extend(["mindfulness", "sleep_anxiety"])
    if "seneca_letter_78" in qid:
        extra_topics.extend(["courage", "social_anxiety"])
    if extra_topics:
        copy = dict(q)
        copy["quote_id"] = qid.replace("quote_univ_", "quote_w2_univ_retag_")
        copy["topic_keys"] = list(dict.fromkeys(q["topic_keys"] + extra_topics))
        _W2_RETAGGED.append(copy)

UNIVERSAL_ALL = W2_UNIVERSAL + _W2_RETAGGED
