#!/usr/bin/env python3
"""Generate config/freebies/somatic_app_catalog.yaml from somatic_exercise_freebee_apps/."""
from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
APPS_DIR = REPO / "somatic_exercise_freebee_apps"
OUT = REPO / "config" / "freebies" / "somatic_app_catalog.yaml"

# Map exercise_pairs keys to primary app filename
PAIR_TO_FILE = {
    "cyclic_sighing": "app26_cyclic_sighing.html",
    "box_breathing": "ex02_box_breathing.html",
    "body_scan": "ex13_body_scan.html",
    "extended_exhale": "ex04_extended_exhale.html",
    "five_senses_grounding": "ex14_grounding_54321.html",
    "478_breathing": "ex01_478_breathing.html",
    "sigh_of_relief": "app26_cyclic_sighing.html",
    "bee_breath": "ex12_bee_breath.html",
    "triangle_breathing": "ex09_triangle_breathing.html",
}


def exercise_id_from_filename(name: str) -> str:
    base = name.replace(".html", "")
    m = re.match(r"^(?:ex|app)(\d+)_(.+)$", base)
    if m:
        return m.group(2)
    return base


def main() -> int:
    files = sorted(APPS_DIR.glob("*.html"))
    lines = [
        "# Somatic HTML mini-apps — catalog for E1/E2 links and phoenix_lead.js routing.",
        "# Generated by scripts/freebies/generate_somatic_app_catalog.py — re-run when apps change.",
        "",
        "schema_version: 1",
        "base_path: /somatic_exercise_freebee_apps/",
        "",
        "apps:",
    ]
    for f in files:
        eid = exercise_id_from_filename(f.name)
        lines.append(f"  {eid}:")
        lines.append(f"    file: {f.name}")
        lines.append(f"    url: /somatic_exercise_freebee_apps/{f.name}")
        lines.append("    email_gate: false")
        lines.append("    topics: [anxiety, burnout, sleep_anxiety, somatic_healing, compassion_fatigue]")
        lines.append("    e1_eligible: true")
        lines.append("    e2_eligible: true")
    lines.append("")
    lines.append("exercise_pairs_files:")
    for pair_id, fname in sorted(PAIR_TO_FILE.items()):
        lines.append(f"  {pair_id}: {fname}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(files)} apps to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
