"""Reusable R2-push helper for render pipelines.

Layer 3 of the cloud-native agents migration. Wraps `r2_sync.py push`
in a Python API that render scripts can call directly without shelling
out. Returns the manifest path so callers can commit it.

Designed to be import-and-call from existing render scripts:

    from scripts.artifacts.r2_push_helper import push_book_render

    manifest_path = push_book_render(
        out_dir=Path("out/rendered/series_xyz/ep_001"),
        series_id="stillness_press__anxiety",
        book_id="ep_001",
    )
    print(f"Manifest written: {manifest_path}")

This module is intentionally minimal — heavy lifting is in r2_sync.py.
We just expose typed entry points for the four common namespaces.
"""
from __future__ import annotations

import hashlib
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[2]
SCHEMA = REPO / "schemas" / "artifacts" / "manifest.schema.json"
CONFIG = REPO / "config" / "artifacts" / "r2_buckets.yaml"
LOCAL_CACHE_DIR = REPO / "artifacts" / "r2_cache"


class R2PushError(RuntimeError):
    pass


def _load_yaml(path: Path) -> dict[str, Any]:
    import yaml  # type: ignore

    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _r2_client():
    """Boto3 client against R2's S3-compatible endpoint.

    Lifts the same logic as r2_sync.py to avoid a fragile import dance.
    """
    try:
        import boto3  # type: ignore
        from botocore.config import Config  # type: ignore
    except ImportError as e:
        raise R2PushError(f"boto3 missing: {e}. pip install boto3")

    account_id = os.environ.get("CLOUDFLARE_ACCOUNT_ID")
    access_key = os.environ.get("R2_ACCESS_KEY_ID")
    secret_key = os.environ.get("R2_SECRET_ACCESS_KEY")
    missing = [
        n
        for n, v in [
            ("CLOUDFLARE_ACCOUNT_ID", account_id),
            ("R2_ACCESS_KEY_ID", access_key),
            ("R2_SECRET_ACCESS_KEY", secret_key),
        ]
        if not v
    ]
    if missing:
        raise R2PushError(f"missing R2 creds: {missing}")

    endpoint = f"https://{account_id}.r2.cloudflarestorage.com"
    return boto3.client(
        "s3",
        endpoint_url=endpoint,
        aws_access_key_id=access_key,
        aws_secret_access_key=secret_key,
        region_name="auto",
        config=Config(signature_version="s3v4", retries={"max_attempts": 3}),
    )


def _sha256_file(path: Path, chunk_size: int = 65536) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while chunk := f.read(chunk_size):
            h.update(chunk)
    return h.hexdigest()


def _content_type(path: Path) -> str:
    suffix = path.suffix.lower()
    return {
        ".png": "image/png",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".webp": "image/webp",
        ".pdf": "application/pdf",
        ".epub": "application/epub+zip",
        ".mp3": "audio/mpeg",
        ".m4a": "audio/mp4",
        ".wav": "audio/wav",
        ".json": "application/json",
        ".yaml": "application/yaml",
        ".txt": "text/plain",
    }.get(suffix, "application/octet-stream")


def _validate_manifest(data: dict[str, Any]) -> list[str]:
    try:
        import jsonschema  # type: ignore

        schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
        v = jsonschema.Draft202012Validator(schema)
        return [
            f"{'.'.join(str(p) for p in err.absolute_path)}: {err.message}"
            for err in v.iter_errors(data)
        ]
    except ImportError:
        errs = []
        for req in ("manifest_schema", "manifest_id", "namespace", "bucket", "artifacts"):
            if req not in data:
                errs.append(f"missing required: {req}")
        return errs


def _write_manifest(path: Path, data: dict[str, Any]) -> None:
    import yaml  # type: ignore

    errors = _validate_manifest(data)
    if errors:
        raise R2PushError("manifest invalid:\n  - " + "\n  - ".join(errors))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# Auto-generated by scripts/artifacts/r2_push_helper.py — do not hand-edit.\n"
        + yaml.safe_dump(data, sort_keys=False, default_flow_style=False),
        encoding="utf-8",
    )


def _bucket_name() -> str:
    cfg = _load_yaml(CONFIG)
    return ((cfg.get("buckets") or {}).get("artifacts") or {}).get("name") or "phoenix-omega-artifacts"


def _produced_by() -> str:
    return os.environ.get("PHOENIX_OMEGA_REMOTE", "unknown")


def push_directory(
    *,
    src_dir: Path,
    namespace: str,
    key_prefix: str,
    manifest_path: Path,
    extra_meta: dict[str, Any] | None = None,
) -> Path:
    """Generic push: upload every file in src_dir under key_prefix, write manifest.

    Args:
        src_dir: directory of files to upload
        namespace: one of the namespaces in r2_buckets.yaml
        key_prefix: full R2 key prefix (e.g. "manga/rendered_books/.../ep_001/")
                    must end with /
        manifest_path: where to write the manifest YAML
        extra_meta: optional dict merged into the manifest top-level
                    (e.g. {"series_id": "x", "book_id": "y"})

    Returns the manifest path.
    """
    if not src_dir.exists() or not src_dir.is_dir():
        raise R2PushError(f"src_dir not a directory: {src_dir}")
    if not key_prefix.endswith("/"):
        raise R2PushError("key_prefix must end with '/'")

    files = sorted(p for p in src_dir.rglob("*") if p.is_file())
    if not files:
        raise R2PushError(f"no files under {src_dir}")

    bucket = _bucket_name()
    client = _r2_client()
    artifacts = []
    total_bytes = 0

    for f in files:
        rel = f.relative_to(src_dir)
        key = key_prefix + str(rel).replace(os.sep, "/")
        sha = _sha256_file(f)
        size = f.stat().st_size
        ctype = _content_type(f)

        with f.open("rb") as fh:
            client.put_object(
                Bucket=bucket,
                Key=key,
                Body=fh,
                ContentType=ctype,
                Metadata={"sha256": sha},
            )
        artifacts.append(
            {"key": key, "sha256": sha, "bytes": size, "content_type": ctype}
        )
        total_bytes += size

    manifest = {
        "manifest_schema": "1.0.0",
        "manifest_id": key_prefix.rstrip("/"),
        "namespace": namespace,
        "bucket": bucket,
        "produced_by": _produced_by(),
        "produced_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "artifacts": artifacts,
        "total_bytes": total_bytes,
        "total_artifacts": len(artifacts),
    }
    if extra_meta:
        manifest.update(extra_meta)

    _write_manifest(manifest_path, manifest)
    return manifest_path


# ─── Typed entry points for the four common namespaces ─────────────────────


def push_book_render(
    *,
    out_dir: Path,
    series_id: str,
    book_id: str,
    manifest_dir: Path | None = None,
) -> Path:
    """Push a single rendered manga book to R2.

    Returns the manifest path (committable to repo).
    """
    if manifest_dir is None:
        manifest_dir = REPO / "artifacts" / "manifests" / "manga_rendered_books" / series_id

    return push_directory(
        src_dir=out_dir,
        namespace="manga_rendered_books",
        key_prefix=f"manga/rendered_books/{series_id}/{book_id}/",
        manifest_path=manifest_dir / f"{book_id}.yaml",
        extra_meta={"series_id": series_id, "book_id": book_id},
    )


def push_character_portraits(
    *,
    portrait_dir: Path,
    character_id: str,
    manifest_dir: Path | None = None,
) -> Path:
    """Push a character's portrait set (main + variants) to R2."""
    if manifest_dir is None:
        manifest_dir = REPO / "artifacts" / "manifests" / "manga_portraits"

    return push_directory(
        src_dir=portrait_dir,
        namespace="manga_portraits",
        key_prefix=f"manga/portraits/{character_id}/",
        manifest_path=manifest_dir / f"{character_id}.yaml",
    )


def push_qa_run(
    *,
    run_dir: Path,
    run_id: str,
    date: str | None = None,
    manifest_dir: Path | None = None,
) -> Path:
    """Push a Pearl Prime QA-run snapshot to R2.

    Lives under qa_runs/{date}/{run_id}/ which the bucket lifecycle rotates after 30d.
    """
    if date is None:
        date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    if manifest_dir is None:
        manifest_dir = REPO / "artifacts" / "manifests" / "pearl_prime_qa_runs" / date

    return push_directory(
        src_dir=run_dir,
        namespace="pearl_prime_qa_runs",
        key_prefix=f"qa_runs/{date}/{run_id}/",
        manifest_path=manifest_dir / f"{run_id}.yaml",
        extra_meta={"run_id": run_id},
    )


def push_brand_asset(
    *,
    asset_dir: Path,
    brand_id: str,
    asset_type: str,
    manifest_dir: Path | None = None,
) -> Path:
    """Push brand-level assets (logos, cover templates) to R2."""
    if manifest_dir is None:
        manifest_dir = REPO / "artifacts" / "manifests" / "brand_assets" / brand_id

    return push_directory(
        src_dir=asset_dir,
        namespace="brand_assets",
        key_prefix=f"brand/{brand_id}/{asset_type}/",
        manifest_path=manifest_dir / f"{asset_type}.yaml",
    )


def sign_url(*, key: str, ttl_seconds: int = 3600) -> str:
    """Generate a time-limited signed URL for one R2 object.

    Useful for handing reviewers a public link to a single rendered cover
    or QA epub without exposing the whole bucket.
    """
    bucket = _bucket_name()
    client = _r2_client()
    return client.generate_presigned_url(
        "get_object",
        Params={"Bucket": bucket, "Key": key},
        ExpiresIn=ttl_seconds,
    )


# ─── CLI shim for sign-url (push uses r2_sync.py directly) ─────────────────


if __name__ == "__main__":
    import argparse

    # Add repo root to path so assert_remote import works when run as script.
    if str(REPO) not in sys.path:
        sys.path.insert(0, str(REPO))
    try:
        from scripts.agent.assert_remote import assert_remote  # type: ignore

        assert_remote(allow_override=True)
    except ImportError:
        pass

    p = argparse.ArgumentParser(description="R2 push helper — sign-url subcommand")
    sub = p.add_subparsers(dest="cmd", required=True)

    sp = sub.add_parser("sign-url", help="generate a time-limited signed URL")
    sp.add_argument("--key", required=True, help="R2 object key")
    sp.add_argument("--ttl", type=int, default=3600, help="seconds (default 3600)")

    args = p.parse_args()

    if args.cmd == "sign-url":
        try:
            print(sign_url(key=args.key, ttl_seconds=args.ttl))
        except R2PushError as e:
            sys.stderr.write(f"❌ {e}\n")
            sys.exit(1)
