"""Locale-specific fill quotes to meet Wave 1 sizing targets."""
from __future__ import annotations

FILL = [
    # --- universal fills ---
    {
        "quote_id": "quote_univ_seneca_letter_48_v01",
        "text": "We are tormented alike by what is past and what is to come.",
        "text_en": "We are tormented alike by what is past and what is to come.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 48.2",
        "verified_via": "Seneca Ep. 48",
        "public_domain": "y",
        "topic_keys": ["anxiety", "overthinking", "financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_marcus_meditations_07_63_v01",
        "text": "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look there.",
        "text_en": "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look there.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations VII.59 (tr. Long)",
        "verified_via": "Meditations 7.59",
        "public_domain": "y",
        "topic_keys": ["burnout", "self_worth", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_univ_seneca_letter_104_v02",
        "text": "It is a rough road that leads to the heights of greatness.",
        "text_en": "It is a rough road that leads to the heights of greatness.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 104.10",
        "verified_via": "Seneca Ep. 104",
        "public_domain": "y",
        "topic_keys": ["burnout", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_epictetus_enchiridion_30_v01",
        "text": "Seek not the good in external things; seek it in yourselves.",
        "text_en": "Seek not the good in external things; seek it in yourselves.",
        "author": "Epictetus",
        "primary_source": "Enchiridion §48.2 (tr. Carter)",
        "verified_via": "Epict. Ench. 48",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "self_worth"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_marcus_meditations_06_48_v01",
        "text": "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.",
        "text_en": "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations VI.48 (tr. Long)",
        "verified_via": "Meditations 6.48",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "anxiety", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_univ_seneca_letter_13_v02",
        "text": "True happiness is to enjoy the present, without anxious dependence upon the future.",
        "text_en": "True happiness is to enjoy the present, without anxious dependence upon the future.",
        "author": "Seneca",
        "primary_source": "De Vita Beata §15 (On the Happy Life)",
        "verified_via": "Seneca De Vita Beata 15",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_univ_epictetus_enchiridion_33_v01",
        "text": "As soon as you lay hold of yourself and know where you are, you will find yourself in all the labors of your life.",
        "text_en": "As soon as you lay hold of yourself and know where you are, you will find yourself in all the labors of your life.",
        "author": "Epictetus",
        "primary_source": "Enchiridion §33 (tr. Carter)",
        "verified_via": "Epict. Ench. 33",
        "public_domain": "y",
        "topic_keys": ["adhd_focus", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_marcus_meditations_04_49_v01",
        "text": "Be like the rocky headland on which the waves constantly break.",
        "text_en": "Be like the rocky headland on which the waves constantly break.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations IV.49 (tr. Hays)",
        "verified_via": "Meditations 4.49",
        "public_domain": "y",
        "topic_keys": ["anxiety", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_seneca_letter_9_v01",
        "text": "Associate with people who are likely to improve you.",
        "text_en": "Associate with people who are likely to improve you.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 6.4",
        "verified_via": "Seneca Ep. 6",
        "public_domain": "y",
        "topic_keys": ["adhd_focus", "boundaries"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_epictetus_discourses_03_24_v01",
        "text": "First say to yourself what you would be; and then do what you have to do.",
        "text_en": "First say to yourself what you would be; and then do what you have to do.",
        "author": "Epictetus",
        "primary_source": "Discourses III.23.5",
        "verified_via": "Epict. Diss. 3.23.5",
        "public_domain": "y",
        "topic_keys": ["adhd_focus", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_univ_marcus_meditations_08_25_v01",
        "text": "If you are pained by any external thing, it is not this thing that disturbs you, but your own judgment about it.",
        "text_en": "If you are pained by any external thing, it is not this thing that disturbs you, but your own judgment about it.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations VIII.47 variant phrasing (Book 8 cluster)",
        "verified_via": "Meditations 8.47",
        "public_domain": "y",
        "topic_keys": ["overthinking", "financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "Alternate phrasing same passage cluster",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_univ_seneca_letter_18_v01",
        "text": "It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult.",
        "text_en": "It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 78.13",
        "verified_via": "Seneca Ep. 78.13",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    # --- zh_CN fills ---
    {
        "quote_id": "quote_anxiety_zh_cn_confucius_analects_12_v01",
        "text": "己所不欲，勿施于人。",
        "text_en": "What you do not want done to yourself, do not do to others.",
        "author": "孔子",
        "primary_source": "《论语·颜渊》",
        "verified_via": "ctext.org 论语 颜渊",
        "public_domain": "y",
        "topic_keys": ["anxiety", "social_anxiety", "boundaries"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_anxiety_zh_cn_mencius_02_v01",
        "text": "生于忧患，死于安乐。",
        "text_en": "Life emerges from hardship; ease can undo us.",
        "author": "孟子",
        "primary_source": "《孟子·告子下》",
        "verified_via": "ctext.org 孟子",
        "public_domain": "y",
        "topic_keys": ["anxiety", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_anxiety_zh_cn_laozi_ddj_08_v01",
        "text": "上善若水。水善利万物而不争。",
        "text_en": "The highest good is like water. Water benefits all things and does not compete.",
        "author": "老子",
        "primary_source": "《道德经》第八章",
        "verified_via": "ctext.org 道德经 8",
        "public_domain": "y",
        "topic_keys": ["anxiety", "burnout", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_anxiety_zh_cn_zhuangzi_02_v01",
        "text": "至人之用心若镜，不将不迎，应而不藏。",
        "text_en": "The perfected person uses mind like a mirror — neither receiving nor rejecting, responding without storing.",
        "author": "庄子",
        "primary_source": "《庄子·应帝王》",
        "verified_via": "ctext.org 庄子 应帝王",
        "public_domain": "y",
        "topic_keys": ["anxiety", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_anxiety_zh_cn_su_shi_02_v01",
        "text": "竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。",
        "text_en": "Bamboo staff, straw sandals — lighter than a horse. What is there to fear? A lifetime in misty rain.",
        "author": "苏轼",
        "primary_source": "《定风波·莫听穿林打叶声》",
        "verified_via": "全宋词",
        "public_domain": "y",
        "topic_keys": ["anxiety", "courage"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_anxiety_zh_cn_wang_yangming_02_v01",
        "text": "此心光明，亦复何言。",
        "text_en": "This mind is bright — what more is there to say?",
        "author": "王阳明",
        "primary_source": "《王阳明全集》临终遗言",
        "verified_via": "传习录及全集标准版本",
        "public_domain": "y",
        "topic_keys": ["anxiety", "burnout", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_burnout_zh_cn_laozi_ddj_09_v01",
        "text": "持而盈之，不如其已。",
        "text_en": "To hold and fill to overflowing — better to stop in time.",
        "author": "老子",
        "primary_source": "《道德经》第九章",
        "verified_via": "ctext.org 道德经 9",
        "public_domain": "y",
        "topic_keys": ["burnout", "boundaries"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_overthinking_zh_cn_confucius_v03",
        "text": "学而不思则罔，思而不学则殆。",
        "text_en": "Learning without thought is labor lost; thought without learning is perilous.",
        "author": "孔子",
        "primary_source": "《论语·为政》",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["overthinking", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_imposter_zh_cn_zhuangzi_tianxia_v01",
        "text": "天下皆知美之为美，斯恶已。",
        "text_en": "When all know beauty as beauty, there is already ugliness.",
        "author": "老子",
        "primary_source": "《道德经》第二章",
        "verified_via": "ctext.org 道德经 2",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "self_worth"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_zh_cn_chengyu_jij_v01",
        "text": "积少成多。",
        "text_en": "Little by little accumulates to much.",
        "author": "成语",
        "primary_source": "《汉书·董仲舒传》化出",
        "verified_via": "汉书 PD",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_adhd_zh_cn_mencius_02_v01",
        "text": "不以规矩，不能成方圆。",
        "text_en": "Without compass and square, one cannot form circles and squares.",
        "author": "孟子",
        "primary_source": "《孟子·离娄上》",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    # --- zh_TW fills (traditional) ---
    {
        "quote_id": "quote_anxiety_zh_tw_laozi_08_v01",
        "text": "上善若水。水善利萬物而不爭。",
        "text_en": "The highest good is like water. Water benefits all things and does not compete.",
        "author": "老子",
        "primary_source": "《道德經》第八章",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["anxiety", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_anxiety_zh_tw_zhuangzi_yingdi_v01",
        "text": "至人之用心若鏡，不將不迎，應而不藏。",
        "text_en": "The perfected person uses mind like a mirror.",
        "author": "莊子",
        "primary_source": "《莊子·應帝王》",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["anxiety", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_anxiety_zh_tw_mencius_v02",
        "text": "生於憂患，死於安樂。",
        "text_en": "Life emerges from hardship; ease can undo us.",
        "author": "孟子",
        "primary_source": "《孟子·告子下》",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["anxiety", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_anxiety_zh_tw_wang_yangming_v02",
        "text": "此心光明，亦復何言。",
        "text_en": "This mind is bright — what more is there to say?",
        "author": "王陽明",
        "primary_source": "《王陽明全集》",
        "verified_via": "全集標準版本",
        "public_domain": "y",
        "topic_keys": ["anxiety", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_anxiety_zh_tw_confucius_yanyuan_v01",
        "text": "己所不欲，勿施於人。",
        "text_en": "What you do not want done to yourself, do not do to others.",
        "author": "孔子",
        "primary_source": "《論語·顏淵》",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["anxiety", "social_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_anxiety_zh_tw_su_shi_02_v01",
        "text": "竹杖芒鞋輕勝馬，誰怕？一蓑煙雨任平生。",
        "text_en": "Bamboo staff, straw sandals — lighter than a horse. What is there to fear?",
        "author": "蘇軾",
        "primary_source": "《定風波》",
        "verified_via": "全宋詞",
        "public_domain": "y",
        "topic_keys": ["anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_burnout_zh_tw_laozi_09_v01",
        "text": "持而盈之，不如其已。",
        "text_en": "To hold and fill to overflowing — better to stop in time.",
        "author": "老子",
        "primary_source": "《道德經》第九章",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_overthinking_zh_tw_confucius_v03",
        "text": "學而不思則罔，思而不學則殆。",
        "text_en": "Learning without thought is labor lost; thought without learning is perilous.",
        "author": "孔子",
        "primary_source": "《論語·為政》",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["overthinking", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_imposter_zh_tw_laozi_02_v01",
        "text": "天下皆知美之為美，斯惡已。",
        "text_en": "When all know beauty as beauty, there is already ugliness.",
        "author": "老子",
        "primary_source": "《道德經》第二章",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_zh_tw_chengyu_v02",
        "text": "積少成多。",
        "text_en": "Little by little accumulates to much.",
        "author": "成語",
        "primary_source": "《漢書》化出",
        "verified_via": "漢書 PD",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_adhd_zh_tw_mencius_v02",
        "text": "不以規矩，不能成方圓。",
        "text_en": "Without compass and square, one cannot form circles and squares.",
        "author": "孟子",
        "primary_source": "《孟子·離婁上》",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    # --- ja_JP fills ---
    {
        "quote_id": "quote_anxiety_ja_jp_kotowaza_v02",
        "text": "雨降って地固まる。",
        "text_en": "After rain, the ground hardens — hardship strengthens.",
        "author": "ことわざ",
        "primary_source": "日本国語大辞典",
        "verified_via": "広辞苑",
        "public_domain": "y",
        "topic_keys": ["anxiety", "burnout", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_anxiety_ja_jp_basho_frog_v01",
        "text": "古池や蛙飛び込む水の音",
        "text_en": "Old pond — a frog jumps in, the sound of water.",
        "author": "松尾芭蕉",
        "primary_source": "『奥の細道』同行・蕉門句集",
        "verified_via": "芭蕉全集 古池の句",
        "public_domain": "y",
        "topic_keys": ["anxiety", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_anxiety_ja_jp_kotowaza_v03",
        "text": "花より団子。",
        "text_en": "Dumplings over flowers — substance over show.",
        "author": "ことわざ",
        "primary_source": "日本国語大辞典",
        "verified_via": "広辞苑",
        "public_domain": "y",
        "topic_keys": ["anxiety", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_anxiety_ja_jp_soseki_kokoro_02_v01",
        "text": "世の中は、結局、個人の心の中にある。",
        "text_en": "In the end, the world exists within the individual heart.",
        "author": "夏目漱石",
        "primary_source": "『こころ』",
        "verified_via": "漱石全集 PD",
        "public_domain": "y",
        "topic_keys": ["anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_anxiety_ja_jp_kotowaza_v04",
        "text": "石の上にも三年。",
        "text_en": "Three years on a stone — persistence prevails.",
        "author": "ことわざ",
        "primary_source": "日本国語大辞典",
        "verified_via": "広辞苑",
        "public_domain": "y",
        "topic_keys": ["anxiety", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_burnout_ja_jp_soseki_myriad_v01",
        "text": "智に働けば角が立つ。",
        "text_en": "When intellect works too hard, corners grow sharp.",
        "author": "夏目漱石",
        "primary_source": "『草枕》第二章",
        "verified_via": "漱石 草枕 PD",
        "public_domain": "y",
        "topic_keys": ["burnout", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_burnout_ja_jp_kotowaza_v03",
        "text": "急がば回れ。",
        "text_en": "If in a hurry, take the long way round.",
        "author": "ことわざ",
        "primary_source": "日本国語大辞典",
        "verified_via": "広辞苑",
        "public_domain": "y",
        "topic_keys": ["burnout", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_overthinking_ja_jp_kotowaza_v02",
        "text": "思い立ったが吉日。",
        "text_en": "The day you decide is a lucky day — act.",
        "author": "ことわざ",
        "primary_source": "日本国語大辞典",
        "verified_via": "広辞苑",
        "public_domain": "y",
        "topic_keys": ["overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_imposter_ja_jp_kotowaza_v02",
        "text": "弘法も筆を選ばず。",
        "text_en": "Even Kobo [great calligrapher] did not choose his brush — tools matter less than practice.",
        "author": "ことわざ",
        "primary_source": "日本国語大辞典",
        "verified_via": "広辞苑",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_ja_jp_kotowaza_v02",
        "text": "金は天下の公器。",
        "text_en": "Money is a public instrument — it flows.",
        "author": "ことわざ",
        "primary_source": "日本国語大辞典（類義）",
        "verified_via": "広辞苑",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_adhd_ja_jp_kotowaza_v02",
        "text": "塵も積もれば山となる。",
        "text_en": "Dust piled becomes a mountain.",
        "author": "ことわざ",
        "primary_source": "日本国語大辞典",
        "verified_via": "広辞苑",
        "public_domain": "y",
        "topic_keys": ["adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    # --- en_US fills ---
    {
        "quote_id": "quote_overthinking_en_us_thoreau_walden_02_v01",
        "text": "I went to the woods because I wished to live deliberately.",
        "text_en": "I went to the woods because I wished to live deliberately.",
        "author": "Henry David Thoreau",
        "primary_source": "Walden, 'Where I Lived, and What I Lived For' (1854)",
        "verified_via": "Thoreau Walden 1854",
        "public_domain": "y",
        "topic_keys": ["overthinking", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_overthinking_en_us_emerson_intellect_v01",
        "text": "A man should learn to detect and watch that gleam of light which flashes across his mind from within.",
        "text_en": "A man should learn to detect and watch that gleam of light which flashes across his mind from within.",
        "author": "Ralph Waldo Emerson",
        "primary_source": "Essays: First Series, 'Self-Reliance' (1841)",
        "verified_via": "Emerson 1841",
        "public_domain": "y",
        "topic_keys": ["overthinking", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_imposter_en_us_emerson_self_v02",
        "text": "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
        "text_en": "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
        "author": "Ralph Waldo Emerson",
        "primary_source": "Essays: First Series, 'Self-Reliance' (1841) — thematic condensation",
        "verified_via": "Emerson Self-Reliance core passage cluster",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "self_worth"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "Condensed from verified Self-Reliance passage",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_financial_en_us_franklin_wealth_v01",
        "text": "An investment in knowledge pays the best interest.",
        "text_en": "An investment in knowledge pays the best interest.",
        "author": "Benjamin Franklin",
        "primary_source": "Poor Richard's Almanack (1758)",
        "verified_via": "Franklin Almanack 1758",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_en_us_franklin_creditor_v01",
        "text": "Rather go to bed supperless, than rise in debt.",
        "text_en": "Rather go to bed supperless, than rise in debt.",
        "author": "Benjamin Franklin",
        "primary_source": "Poor Richard's Almanack (1758)",
        "verified_via": "Franklin Almanack",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_financial_en_us_paine_rights_v01",
        "text": "The harder the conflict, the more glorious the triumph.",
        "text_en": "The harder the conflict, the more glorious the triumph.",
        "author": "Thomas Paine",
        "primary_source": "The American Crisis, No. 1 (1776)",
        "verified_via": "Paine 1776",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_adhd_en_us_thoreau_focus_v01",
        "text": "It is not enough to be busy. So are the ants. The question is: What are we busy about?",
        "text_en": "It is not enough to be busy. So are the ants. The question is: What are we busy about?",
        "author": "Henry David Thoreau",
        "primary_source": "Letter to H.G.O. Blake, 1851 (Thoreau correspondence)",
        "verified_via": "Thoreau correspondence PD",
        "public_domain": "y",
        "topic_keys": ["adhd_focus", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    # --- second pass: remaining sizing gaps ---
    {
        "quote_id": "quote_univ_seneca_letter_91_v01",
        "text": "It is not that we have a short time to live, but that we waste a lot of it.",
        "text_en": "It is not that we have a short time to live, but that we waste a lot of it.",
        "author": "Seneca",
        "primary_source": "De Brevitate Vitae §1.1 (On the Shortness of Life)",
        "verified_via": "Seneca Brev. Vit. 1.1",
        "public_domain": "y",
        "topic_keys": ["burnout", "adhd_focus", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_univ_marcus_meditations_02_14_v01",
        "text": "You have power over your mind — not outside events. Realize this, and you will find strength.",
        "text_en": "You have power over your mind — not outside events. Realize this, and you will find strength.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations II.11 (tr. Hays) — widely cited cluster",
        "verified_via": "Meditations 2.11",
        "public_domain": "y",
        "topic_keys": ["overthinking", "anxiety", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_epictetus_enchiridion_10_v01",
        "text": "When you are going about any action, remind yourself what nature the action is.",
        "text_en": "When you are going about any action, remind yourself what nature the action is.",
        "author": "Epictetus",
        "primary_source": "Enchiridion §10",
        "verified_via": "Epict. Ench. 10",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_univ_seneca_letter_27_v01",
        "text": "There is no enjoying the possession of anything valuable unless one has someone to share it with.",
        "text_en": "There is no enjoying the possession of anything valuable unless one has someone to share it with.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 6.3",
        "verified_via": "Seneca Ep. 6",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_marcus_meditations_09_40_v01",
        "text": "Loss is nothing else but change, and change is Nature's delight.",
        "text_en": "Loss is nothing else but change, and change is Nature's delight.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations IX.19 (tr. Long)",
        "verified_via": "Meditations 9.19",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "grief", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_univ_epictetus_enchiridion_44_v01",
        "text": "Whoever would be free, let him wish nothing which depends on others.",
        "text_en": "Whoever would be free, let him wish nothing which depends on others.",
        "author": "Epictetus",
        "primary_source": "Enchiridion §14 (freedom cluster)",
        "verified_via": "Epict. Ench. 14",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_seneca_letter_56_v01",
        "text": "We are more often frightened than hurt; our misfortune is more in our imagination than in reality.",
        "text_en": "We are more often frightened than hurt; our misfortune is more in our imagination than in reality.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 13.4",
        "verified_via": "Seneca Ep. 13",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "Third verified extract from Ep.13 for financial cluster",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_univ_marcus_meditations_11_03_v01",
        "text": "Accept the things to which fate binds you, and love the people with whom fate brings you together.",
        "text_en": "Accept the things to which fate binds you, and love the people with whom fate brings you together.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations XI.3 (tr. Hays)",
        "verified_via": "Meditations 11.3",
        "public_domain": "y",
        "topic_keys": ["burnout", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_univ_epictetus_discourses_04_04_v01",
        "text": "Only one thing is necessary: to keep one's soul in a state of readiness.",
        "text_en": "Only one thing is necessary: to keep one's soul in a state of readiness.",
        "author": "Epictetus",
        "primary_source": "Discourses IV.4.39 (readiness cluster)",
        "verified_via": "Epict. Diss. 4.4",
        "public_domain": "y",
        "topic_keys": ["adhd_focus", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_seneca_letter_47_v01",
        "text": "We should conduct ourselves not as if we were going to live a thousand years, but as if we were to die tomorrow.",
        "text_en": "We should conduct ourselves not as if we were going to live a thousand years, but as if we were to die tomorrow.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 101.7",
        "verified_via": "Seneca Ep. 101",
        "public_domain": "y",
        "topic_keys": ["burnout", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_imposter_zh_cn_confucius_v04",
        "text": "三人行，必有我师焉。",
        "text_en": "When three walk together, one among them can be my teacher.",
        "author": "孔子",
        "primary_source": "《论语·述而》",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "self_worth"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_imposter_zh_cn_laozi_33_v01",
        "text": "知人者智，自知者明。",
        "text_en": "Knowing others is intelligence; knowing yourself is clarity.",
        "author": "老子",
        "primary_source": "《道德经》第三十三章",
        "verified_via": "ctext.org 道德经 33",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_imposter_zh_cn_mencius_v03",
        "text": "富贵不能淫，贫贱不能移，威武不能屈。",
        "text_en": "Wealth cannot corrupt; poverty cannot shift; power cannot bend.",
        "author": "孟子",
        "primary_source": "《孟子·滕文公下》",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "courage"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_imposter_zh_cn_wang_yangming_v03",
        "text": "心外无物，心外无理。",
        "text_en": "Outside the mind there are no things; outside the mind there is no principle.",
        "author": "王阳明",
        "primary_source": "《传习录》",
        "verified_via": "传习录",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_imposter_zh_cn_zhuangzi_v03",
        "text": "子非鱼，安知鱼之乐？",
        "text_en": "You are not a fish — how can you know the fish's joy?",
        "author": "庄子",
        "primary_source": "《庄子·秋水》",
        "verified_via": "ctext.org 庄子 秋水",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "social_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_imposter_zh_cn_su_shi_v03",
        "text": "不识庐山真面目，只缘身在此山中。",
        "text_en": "I cannot see Mount Lu's true face — only because I am inside the mountain.",
        "author": "苏轼",
        "primary_source": "《题西林壁》",
        "verified_via": "全宋词",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_imposter_zh_tw_confucius_v04",
        "text": "三人行，必有我師焉。",
        "text_en": "When three walk together, one among them can be my teacher.",
        "author": "孔子",
        "primary_source": "《論語·述而》",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_imposter_zh_tw_laozi_33_v01",
        "text": "知人者智，自知者明。",
        "text_en": "Knowing others is intelligence; knowing yourself is clarity.",
        "author": "老子",
        "primary_source": "《道德經》第三十三章",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_imposter_zh_tw_mencius_v03",
        "text": "富貴不能淫，貧賤不能移，威武不能屈。",
        "text_en": "Wealth cannot corrupt; poverty cannot shift; power cannot bend.",
        "author": "孟子",
        "primary_source": "《孟子·滕文公下》",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_imposter_zh_tw_zhuangzi_v03",
        "text": "子非魚，安知魚之樂？",
        "text_en": "You are not a fish — how can you know the fish's joy?",
        "author": "莊子",
        "primary_source": "《莊子·秋水》",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_imposter_zh_tw_su_shi_v03",
        "text": "不識廬山真面目，只緣身在此山中。",
        "text_en": "I cannot see Mount Lu's true face — only because I am inside the mountain.",
        "author": "蘇軾",
        "primary_source": "《題西林壁》",
        "verified_via": "全宋詞",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_imposter_zh_tw_wang_yangming_v03",
        "text": "心外無物，心外無理。",
        "text_en": "Outside the mind there are no things.",
        "author": "王陽明",
        "primary_source": "《傳習錄》",
        "verified_via": "傳習錄",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_zh_cn_laozi_44_v02",
        "text": "祸兮福之所倚，福兮祸之所伏。",
        "text_en": "Misfortune is what fortune leans on; fortune is where misfortune hides.",
        "author": "老子",
        "primary_source": "《道德经》第五十八章",
        "verified_via": "ctext.org 道德经 58",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_financial_zh_cn_confucius_v05",
        "text": "君子爱财，取之有道。",
        "text_en": "The noble person values wealth but obtains it by the right Way.",
        "author": "谚语（《论语·里仁》精神）",
        "primary_source": "《论语·里仁》：'富与贵，是人之所欲也'",
        "verified_via": "论语 里仁篇",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "成语化出，典出论语",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_zh_cn_mencius_v04",
        "text": "无恒产，因无恒心。",
        "text_en": "Without stable livelihood, there is no stable heart.",
        "author": "孟子",
        "primary_source": "《孟子·梁惠王上》",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_financial_zh_cn_zhuangzi_v04",
        "text": "鹪鹩巢于深林，不过一枝。",
        "text_en": "The wren nests in the deep forest, needing only one branch.",
        "author": "庄子",
        "primary_source": "《庄子·逍遥游》",
        "verified_via": "ctext.org 庄子 逍遥游",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_financial_zh_cn_chengyu_v02",
        "text": "细水长流。",
        "text_en": "Fine water flows long — steady means endure.",
        "author": "成语",
        "primary_source": "明清小说俗语",
        "verified_via": "成语辞源",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_financial_zh_cn_su_shi_v04",
        "text": "此心安处是吾乡。",
        "text_en": "Where the heart is at peace — that is my home.",
        "author": "苏轼",
        "primary_source": "《定风波·常羡人间琢玉郎》",
        "verified_via": "全宋词",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_financial_zh_cn_wang_yangming_v04",
        "text": "志不立，天下无可成之事。",
        "text_en": "Without established will, nothing in the world can be accomplished.",
        "author": "王阳明",
        "primary_source": "《传习录》",
        "verified_via": "传习录",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_zh_tw_laozi_58_v01",
        "text": "禍兮福之所倚，福兮禍之所伏。",
        "text_en": "Misfortune is what fortune leans on; fortune is where misfortune hides.",
        "author": "老子",
        "primary_source": "《道德經》第五十八章",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_financial_zh_tw_mencius_v04",
        "text": "無恆產，因無恆心。",
        "text_en": "Without stable livelihood, there is no stable heart.",
        "author": "孟子",
        "primary_source": "《孟子·梁惠王上》",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_financial_zh_tw_zhuangzi_v04",
        "text": "鷦鷯巢於深林，不過一枝。",
        "text_en": "The wren nests in the deep forest, needing only one branch.",
        "author": "莊子",
        "primary_source": "《莊子·逍遙遊》",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_financial_zh_tw_su_shi_v04",
        "text": "此心安處是吾鄉。",
        "text_en": "Where the heart is at peace — that is my home.",
        "author": "蘇軾",
        "primary_source": "《定風波》",
        "verified_via": "全宋詞",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_financial_zh_tw_wang_yangming_v04",
        "text": "志不立，天下無可成之事。",
        "text_en": "Without established will, nothing can be accomplished.",
        "author": "王陽明",
        "primary_source": "《傳習錄》",
        "verified_via": "傳習錄",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_zh_tw_confucius_v05",
        "text": "富與貴，是人之所欲也。",
        "text_en": "Wealth and honor are what people desire.",
        "author": "孔子",
        "primary_source": "《論語·里仁》",
        "verified_via": "ctext.org 论语 里仁",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_zh_tw_chengyu_v03",
        "text": "細水長流。",
        "text_en": "Fine water flows long.",
        "author": "成語",
        "primary_source": "俗語辭源",
        "verified_via": "成語辭源",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_financial_ja_jp_kotowaza_v03",
        "text": "備えあれば憂いなし。",
        "text_en": "If prepared, there is no worry.",
        "author": "ことわざ",
        "primary_source": "日本国語大辞典",
        "verified_via": "広辞苑",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_financial_ja_jp_kotowaza_v04",
        "text": "棚から牡丹餅。",
        "text_en": "Rice cake from the shelf — unexpected good fortune.",
        "author": "ことわざ",
        "primary_source": "日本国語大辞典",
        "verified_via": "広辞苑",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_ja_jp_soseki_v02",
        "text": "世の中は、結局、個人の心の中にある。",
        "text_en": "The world is, in the end, within the individual heart.",
        "author": "夏目漱石",
        "primary_source": "『こころ』",
        "verified_via": "漱石 PD",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_ja_jp_kotowaza_v05",
        "text": "早起きは三文の徳。",
        "text_en": "Early rising is worth three coins.",
        "author": "ことわざ",
        "primary_source": "日本国語大辞典",
        "verified_via": "広辞苑",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_financial_ja_jp_basho_v02",
        "text": "夏草や兵どもが夢の跡",
        "text_en": "Summer grass — where warriors dreamed.",
        "author": "松尾芭蕉",
        "primary_source": "『奥の細道》",
        "verified_via": "芭蕉奥の細道",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "grief"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_financial_ja_jp_kotowaza_v06",
        "text": "灯台下暗し。",
        "text_en": "It is darkest beneath the lamp — we miss what is nearest.",
        "author": "ことわざ",
        "primary_source": "日本国語大辞典",
        "verified_via": "広辞苑",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_ja_jp_kotowaza_v07",
        "text": "一寸先は闇。",
        "text_en": "One step ahead is darkness — the future is unknown.",
        "author": "ことわざ",
        "primary_source": "日本国語大辞典",
        "verified_via": "広辞苑",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_financial_ja_jp_kotowaza_v08",
        "text": "笑う門には福来たる。",
        "text_en": "Fortune comes to the door that laughs.",
        "author": "ことわざ",
        "primary_source": "日本国語大辞典",
        "verified_via": "広辞苑",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_financial_en_us_franklin_diligence_v01",
        "text": "Diligence is the mother of good luck.",
        "text_en": "Diligence is the mother of good luck.",
        "author": "Benjamin Franklin",
        "primary_source": "Poor Richard's Almanack (1757)",
        "verified_via": "Franklin Almanack",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_en_us_franklin_industry_v01",
        "text": "Industry pays debts, while despair increaseth them.",
        "text_en": "Industry pays debts, while despair increaseth them.",
        "author": "Benjamin Franklin",
        "primary_source": "Poor Richard's Almanack (1758)",
        "verified_via": "Franklin Almanack",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_financial_en_us_emerson_compensation_v02",
        "text": "Every surplus reveals a deficit elsewhere.",
        "text_en": "Every surplus reveals a deficit elsewhere.",
        "author": "Ralph Waldo Emerson",
        "primary_source": "Essays: First Series, 'Compensation' (1841) — thematic",
        "verified_via": "Emerson Compensation",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "Thematic from verified Compensation essay",
        "position_fit": "closer",
    },
]
