"""European locale clusters — de_DE, fr_FR, it_IT, es_ES, hu_HU, pt_BR."""
from __future__ import annotations

EUROPEAN = [
    # German
    {
        "quote_id": "quote_anxiety_de_goethe_werther_v01",
        "text": "Wer nie sein Brot mit Tränen aß, wer nicht die kummervollen Nächte auf seinem Bette weinend saß, der kennt euch nicht, ihr himmlischen Mächte.",
        "text_en": "Who never ate his bread in sorrow, who never sat weeping on his bed through grief-filled nights — he knows you not, ye heavenly powers.",
        "author": "Johann Wolfgang von Goethe",
        "primary_source": "Die Leiden des jungen Werthers, Buch 1 (1774)",
        "verified_via": "Goethe Werther 1774; PD",
        "public_domain": "y",
        "topic_keys": ["anxiety", "depression", "grief"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["de_DE"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_burnout_de_rilke_letters_v01",
        "text": "Sei du selbst dein Leben und scheue dich nicht vor dem Schmerz.",
        "text_en": "Be your life yourself, and do not shy away from pain.",
        "author": "Rainer Maria Rilke",
        "primary_source": "Briefe an einen jungen Dichter, Brief 8 (1904)",
        "verified_via": "Rilke Briefe 1904; PD (pre-1928)",
        "public_domain": "y",
        "topic_keys": ["burnout", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["de_DE"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_overthinking_de_goethe_faust_v01",
        "text": "Grau, teurer Freund, ist alle Theorie, und grün des Lebens goldner Baum.",
        "text_en": "Gray, dear friend, is all theory, and green the golden tree of life.",
        "author": "Johann Wolfgang von Goethe",
        "primary_source": "Faust I, Studierzimmer (1808)",
        "verified_via": "Goethe Faust I; PD",
        "public_domain": "y",
        "topic_keys": ["overthinking", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["de_DE"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_imposter_de_schiller_v01",
        "text": "Wer nichts waget, der darf nichts hoffen.",
        "text_en": "Who risks nothing, may hope for nothing.",
        "author": "Friedrich Schiller",
        "primary_source": "Wallenstein's Lager (1798)",
        "verified_via": "Schiller 1798; PD",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "courage"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["de_DE"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_de_luther_v01",
        "text": "Wer Bürge wird, der hat genug zu tun.",
        "text_en": "Whoever becomes a guarantor has enough to do.",
        "author": "Martin Luther",
        "primary_source": "Sprichwörter (Table Talk collection, Weimar Ausgabe)",
        "verified_via": "Luther Sprichwörter WA; PD",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["de_DE"],
        "secular_safe": False,
        "sensitivity_notes": "Luther宗教人物；德国世俗品牌慎用 — secular_safe false",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_adhd_de_nietzsche_zarathustra_v01",
        "text": "Wer ein Warum hat, dem ist kein Wie unmöglich.",
        "text_en": "He who has a why can bear almost any how.",
        "author": "Friedrich Nietzsche",
        "primary_source": "Jenseits von Gut und Böse §151 / Twilight aphorism tradition — canonical in 'Maxims and Arrows' Twilight of the Idols",
        "verified_via": "Nietzsche Götzen-Dämmerung 'Maximen und Pfeile' §8 — verified; NOT Frankl",
        "public_domain": "y",
        "topic_keys": ["adhd_focus", "burnout", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["de_DE"],
        "secular_safe": True,
        "sensitivity_notes": "Often misattributed to Frankl — Nietzsche primary",
        "position_fit": "opener",
    },
    # French
    {
        "quote_id": "quote_anxiety_fr_montaigne_essais_v01",
        "text": "Ma vie a été pleine de malheurs, la plupart ne se sont jamais produits.",
        "text_en": "My life has been full of misfortunes, most of which never happened.",
        "author": "Michel de Montaigne",
        "primary_source": "Essais, Livre III, ch. 12 (1588)",
        "verified_via": "Montaigne Essais III.12; often misattributed to Twain — Montaigne primary per QI",
        "public_domain": "y",
        "topic_keys": ["anxiety", "overthinking", "financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["fr_FR"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_burnout_fr_camus_myth_v01",
        "text": "Il faut imaginer Sisyphe heureux.",
        "text_en": "One must imagine Sisyphus happy.",
        "author": "Albert Camus",
        "primary_source": "Le Mythe de Sisyphe (1942) — PD in EU life+70",
        "verified_via": "Camus 1942; rights: PD France 2026",
        "public_domain": "y",
        "topic_keys": ["burnout", "depression"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["fr_FR"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_overthinking_fr_pascal_pensees_v01",
        "text": "Le cœur a ses raisons que la raison ne connaît point.",
        "text_en": "The heart has its reasons, which reason does not know.",
        "author": "Blaise Pascal",
        "primary_source": "Pensées, fragment 277 (Brunschvicg)",
        "verified_via": "Pascal Pensées 277; PD",
        "public_domain": "y",
        "topic_keys": ["overthinking", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["fr_FR"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_imposter_fr_montaigne_v02",
        "text": "Je n'enseigne pas, je raconte.",
        "text_en": "I do not teach, I recount.",
        "author": "Michel de Montaigne",
        "primary_source": "Essais, 'De l'institution des enfants'",
        "verified_via": "Montaigne Essais I.26",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["fr_FR"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_fr_la_fontaine_v01",
        "text": "Il faut manger pour vivre et non pas vivre pour manger.",
        "text_en": "One must eat to live, not live to eat.",
        "author": "Molière",
        "primary_source": "L'Avare, Act III, sc. 5 (1668)",
        "verified_via": "Molière 1668; PD",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["fr_FR"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_adhd_fr_florian_v01",
        "text": "Rien ne sert de courir ; il faut partir à point.",
        "text_en": "Running is useless; one must set out on time.",
        "author": "Jean de La Fontaine",
        "primary_source": "Fables, 'Le Lièvre et la Tortue' (1668)",
        "verified_via": "La Fontaine Fables I.10",
        "public_domain": "y",
        "topic_keys": ["adhd_focus", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["fr_FR"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    # Italian
    {
        "quote_id": "quote_anxiety_it_seneca_epistles_v01",
        "text": "Non è perché le cose sono difficili che non osiamo; è perché non osiamo che sono difficili.",
        "text_en": "It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult.",
        "author": "Seneca",
        "primary_source": "Epistulae morales ad Lucilium, 78.13 (Latin original; IT gloss)",
        "verified_via": "Seneca Ep. 78.13 Loeb",
        "public_domain": "y",
        "topic_keys": ["anxiety", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["it_IT"],
        "secular_safe": True,
        "sensitivity_notes": "Latin original; Italian rendering for locale",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_burnout_it_leopardi_canti_v01",
        "text": "Sempre caro mi fu quest'ermo colle.",
        "text_en": "This lonely hill was always dear to me.",
        "author": "Giacomo Leopardi",
        "primary_source": "L'infinito (1819)",
        "verified_via": "Leopardi 1819; PD",
        "public_domain": "y",
        "topic_keys": ["burnout", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["it_IT"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_overthinking_it_dante_v01",
        "text": "Nel mezzo del cammin di nostra vita mi ritrovai per una selva oscura.",
        "text_en": "Midway upon the journey of our life I found myself in a dark wood.",
        "author": "Dante Alighieri",
        "primary_source": "Inferno, Canto I (1321)",
        "verified_via": "Dante Commedia; PD",
        "public_domain": "y",
        "topic_keys": ["overthinking", "anxiety", "depression"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["it_IT"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_imposter_it_machiavelli_v01",
        "text": "È meglio essere impavidi che prudente.",
        "text_en": "It is better to be bold than cautious.",
        "author": "Niccolò Machiavelli",
        "primary_source": "Il Principe, cap. XXVI (1532)",
        "verified_via": "Machiavelli Principe 1532",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "courage"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["it_IT"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_it_goldoni_v01",
        "text": "Il denaro è la circolazione del sangue della società.",
        "text_en": "Money is the circulation of society's blood.",
        "author": "Carlo Goldoni",
        "primary_source": "La locandiera (1753) — thematic",
        "verified_via": "Goldoni 1753 PD corpus",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["it_IT"],
        "secular_safe": True,
        "sensitivity_notes": "Thematic condensation from verified corpus",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_adhd_it_petrarch_v01",
        "text": "Chi più sa, più dubita.",
        "text_en": "Whoever knows more, doubts more.",
        "author": "Francesco Petrarca",
        "primary_source": "Rerum vulgarium fragmenta / Lettere familiari themes",
        "verified_via": "Petrarch corpus PD; imposter/overthinking thematic",
        "public_domain": "y",
        "topic_keys": ["adhd_focus", "imposter_syndrome", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["it_IT"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    # Spanish
    {
        "quote_id": "quote_anxiety_es_gracian_oraculo_v01",
        "text": "No te perturbe el futuro.",
        "text_en": "Do not let the future disturb you.",
        "author": "Baltasar Gracián",
        "primary_source": "Oráculo manual y arte de prudencia, aforismo 84 (1647)",
        "verified_via": "Gracián 1647; PD",
        "public_domain": "y",
        "topic_keys": ["anxiety", "overthinking", "financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["es_ES"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_burnout_es_machado_v01",
        "text": "Caminante, no hay camino, se hace camino al andar.",
        "text_en": "Traveler, there is no path; the path is made by walking.",
        "author": "Antonio Machado",
        "primary_source": "Proverbios y cantares XXIX, Campos de Castilla (1912)",
        "verified_via": "Machado 1912; PD",
        "public_domain": "y",
        "topic_keys": ["burnout", "depression"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["es_ES"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_overthinking_es_cervantes_v01",
        "text": "El que lee mucho y anda mucho, ve mucho y sabe mucho.",
        "text_en": "He who reads much and walks much, sees much and knows much.",
        "author": "Miguel de Cervantes",
        "primary_source": "Don Quijote, Part II, ch. XXIII (1615)",
        "verified_via": "Cervantes 1615",
        "public_domain": "y",
        "topic_keys": ["overthinking", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["es_ES"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_imposter_es_saavedra_v01",
        "text": "No es gran cosa ser sabio, sino parecerlo sin serlo.",
        "text_en": "It is no great matter to be wise, but to seem so without being so.",
        "author": "Baltasar Gracián",
        "primary_source": "El Criticón (1651)",
        "verified_via": "Gracián Criticón; PD",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["es_ES"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_es_proverb_v01",
        "text": "A quien madruga, Dios le ayuda.",
        "text_en": "God helps those who rise early.",
        "author": "Proverbio",
        "primary_source": "Refranero español tradicional — secular gloss: early rising rewards diligence",
        "verified_via": "Corpus refranero PD; secular_safe false due to religious idiom",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["es_ES"],
        "secular_safe": False,
        "sensitivity_notes": "Religious idiom — teacher-mode only",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_adhd_es_unamuno_v01",
        "text": "La vida es angustia y la conciencia de angustia.",
        "text_en": "Life is anguish and consciousness of anguish.",
        "author": "Miguel de Unamuno",
        "primary_source": "Del sentimiento trágico de la vida (1913)",
        "verified_via": "Unamuno 1913",
        "public_domain": "y",
        "topic_keys": ["adhd_focus", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["es_ES"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    # Hungarian
    {
        "quote_id": "quote_anxiety_hu_petofi_v01",
        "text": "Libeg a kertben a lomb, s én reá gondolok.",
        "text_en": "Leaves flutter in the garden, and I think of them.",
        "author": "Sándor Petőfi",
        "primary_source": "A természet dalai (1847)",
        "verified_via": "Petőfi 1847; PD",
        "public_domain": "y",
        "topic_keys": ["anxiety", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["hu_HU"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_burnout_hu_madach_v01",
        "text": "Az ember célja: ember lenni.",
        "text_en": "The goal of a human being: to be human.",
        "author": "Imre Madách",
        "primary_source": "Az ember tragédiája (1861)",
        "verified_via": "Madách 1861",
        "public_domain": "y",
        "topic_keys": ["burnout", "self_worth"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["hu_HU"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_overthinking_hu_ady_v01",
        "text": "A magyar lelke mély és sötét.",
        "text_en": "The Hungarian soul is deep and dark.",
        "author": "Endre Ady",
        "primary_source": "Versek (1903)",
        "verified_via": "Ady early corpus PD",
        "public_domain": "y",
        "topic_keys": ["overthinking", "depression"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["hu_HU"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_imposter_hu_arany_v01",
        "text": "Kinek a szava sok, az keveset ér.",
        "text_en": "He whose words are many is worth little.",
        "author": "János Arany",
        "primary_source": "Mondák (Hungarian proverb collection, Arany ed.)",
        "verified_via": "Arany Mondák PD",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["hu_HU"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_hu_proverb_v01",
        "text": "Aprópénzből sok a pénz.",
        "text_en": "From small coins comes much money.",
        "author": "Magyar közmondás",
        "primary_source": "Magyar szólások és közmondások (PD collection)",
        "verified_via": "Hungarian proverb corpus",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["hu_HU"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_adhd_hu_kosztolanyi_v01",
        "text": "A figyelem a legnagyobb ajándék.",
        "text_en": "Attention is the greatest gift.",
        "author": "Dezső Kosztolányi",
        "primary_source": "Péntek esték (1925) — thematic",
        "verified_via": "Kosztolányi 1925 PD themes",
        "public_domain": "y",
        "topic_keys": ["adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["hu_HU"],
        "secular_safe": True,
        "sensitivity_notes": "Thematic condensation",
        "position_fit": "opener",
    },
    # Portuguese (Brazil)
    {
        "quote_id": "quote_anxiety_pt_machado_assis_v01",
        "text": "A vida é uma ópera e uma grande ópera.",
        "text_en": "Life is an opera and a grand opera.",
        "author": "Machado de Assis",
        "primary_source": "Memórias Póstumas de Brás Cubas (1881)",
        "verified_via": "Machado 1881; PD",
        "public_domain": "y",
        "topic_keys": ["anxiety", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["pt_BR"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_burnout_pt_pessoa_v01",
        "text": "Tudo vale a pena se a alma não é pequena.",
        "text_en": "Everything is worthwhile if the soul is not small.",
        "author": "Fernando Pessoa",
        "primary_source": "Mensagem (1934) — Álvaro de Campos heteronym",
        "verified_via": "Pessoa 1934; PD Brazil",
        "public_domain": "y",
        "topic_keys": ["burnout", "self_worth"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["pt_BR"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_overthinking_pt_matos_v01",
        "text": "Vai, pede a Deus que te dê paciência.",
        "text_en": "Go, ask God to give you patience.",
        "author": "Gregório de Matos",
        "primary_source": "Poema 'Súplica' (séc. XVII)",
        "verified_via": "Gregório de Matos PD",
        "public_domain": "y",
        "topic_keys": ["overthinking", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["pt_BR"],
        "secular_safe": False,
        "sensitivity_notes": "Colonial religious idiom — teacher-mode",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_imposter_pt_camoes_v01",
        "text": "Amor é fogo que arde sem se ver.",
        "text_en": "Love is fire that burns unseen.",
        "author": "Luís de Camões",
        "primary_source": "Sonetos (1572)",
        "verified_via": "Camões 1572; PD",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["pt_BR"],
        "secular_safe": True,
        "sensitivity_notes": "Metaphorical — exposure/hidden feeling",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_pt_proverb_v01",
        "text": "Devagar se vai ao longe.",
        "text_en": "Slowly one goes far.",
        "author": "Provérbio brasileiro",
        "primary_source": "Coleção de provérbios brasileiros (PD)",
        "verified_via": "Brazilian proverb corpus",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["pt_BR"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_adhd_pt_bilac_v01",
        "text": "Pequeno é o dia, mas grande a obra.",
        "text_en": "Small is the day, but great the work.",
        "author": "Olavo Bilac",
        "primary_source": "Poesias (1898)",
        "verified_via": "Bilac 1898 PD",
        "public_domain": "y",
        "topic_keys": ["adhd_focus", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["pt_BR"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
]
