"""Simplified Chinese (zh-CN) canon — PRC-safe sources only."""
from __future__ import annotations

ZH_CN = [
    {
        "quote_id": "quote_anxiety_zh_cn_laozi_ddj_16_v01",
        "text": "致虚极，守静笃，万物并作，吾以观复。",
        "text_en": "Attain the utmost emptiness; hold firmly to stillness. While the myriad things rise together, I observe their return.",
        "author": "老子",
        "primary_source": "《道德经》第十六章，王弼本",
        "verified_via": "中国哲学书电子化计划 ctext.org 道德经十六",
        "public_domain": "y",
        "topic_keys": ["anxiety", "overthinking", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "哲学道家；无宗教仪轨用语",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_anxiety_zh_cn_zhuangzi_v01",
        "text": "吾生也有涯，而知也无涯。以有涯随无涯，殆已！",
        "text_en": "Life has limits, but knowledge has none. To chase the limitless with the limited — perilous!",
        "author": "庄子",
        "primary_source": "《庄子·养生主》",
        "verified_via": "ctext.org 庄子 养生主",
        "public_domain": "y",
        "topic_keys": ["anxiety", "overthinking", "burnout", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_anxiety_zh_cn_confucius_analects_v01",
        "text": "君子不器。",
        "text_en": "The noble person is not a single-purpose vessel.",
        "author": "孔子",
        "primary_source": "《论语·为政》",
        "verified_via": "ctext.org 论语 为政",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "adhd_focus", "self_worth"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "儒家思想；世俗化阐释",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_anxiety_zh_cn_wang_yangming_v01",
        "text": "知行合一。",
        "text_en": "Knowledge and action are one.",
        "author": "王阳明",
        "primary_source": "《传习录》",
        "verified_via": "传习录 上卷；中国思想史标准版本",
        "public_domain": "y",
        "topic_keys": ["overthinking", "adhd_focus", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_anxiety_zh_cn_su_shi_v01",
        "text": "回首向来萧瑟处，归去，也无风雨也无晴。",
        "text_en": "Looking back on the path I walked through wind and rain — going home, there is neither storm nor clear sky.",
        "author": "苏轼",
        "primary_source": "《定风波·莫听穿林打叶声》",
        "verified_via": "全宋词 苏轼词作；PD",
        "public_domain": "y",
        "topic_keys": ["anxiety", "burnout", "grief"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03", "COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_burnout_zh_cn_chengyu_v01",
        "text": "欲速则不达。",
        "text_en": "Haste makes waste; rushing prevents arrival.",
        "author": "谚语（《论语·子路》化出）",
        "primary_source": "《论语·子路》：'欲速则不达，见小利则大事不成'",
        "verified_via": "论语 子路篇",
        "public_domain": "y",
        "topic_keys": ["burnout", "anxiety", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "成语；有经典出处",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_overthinking_zh_cn_laozi_ddj_48_v01",
        "text": "为学日益，为道日损。",
        "text_en": "In learning, one accumulates daily; in the Way, one reduces daily.",
        "author": "老子",
        "primary_source": "《道德经》第四十八章",
        "verified_via": "ctext.org 道德经 48",
        "public_domain": "y",
        "topic_keys": ["overthinking", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_imposter_zh_cn_mencius_v01",
        "text": "人皆可以为尧舜。",
        "text_en": "Every person can become like Yao and Shun.",
        "author": "孟子",
        "primary_source": "《孟子·告子下》",
        "verified_via": "ctext.org 孟子 告子下",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "self_worth"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "古代圣王为道德典范非政治人物",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_zh_cn_laozi_ddj_44_v01",
        "text": "知足不辱，知止不殆。",
        "text_en": "Knowing contentment, you are not disgraced; knowing when to stop, you are not endangered.",
        "author": "老子",
        "primary_source": "《道德经》第四十四章",
        "verified_via": "ctext.org 道德经 44",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_adhd_zh_cn_zhuangzi_v02",
        "text": "用志不分，乃凝于神。",
        "text_en": "When will is undivided, the spirit concentrates.",
        "author": "庄子",
        "primary_source": "《庄子·达生》佝偻丈人承蜩",
        "verified_via": "ctext.org 庄子 达生",
        "public_domain": "y",
        "topic_keys": ["adhd_focus", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_anxiety_zh_cn_laozi_ddj_64_v01",
        "text": "千里之行，始于足下。",
        "text_en": "A journey of a thousand li begins beneath one's feet.",
        "author": "老子",
        "primary_source": "《道德经》第六十四章",
        "verified_via": "ctext.org 道德经 64",
        "public_domain": "y",
        "topic_keys": ["anxiety", "financial_anxiety", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_burnout_zh_cn_confucius_v02",
        "text": "学而时习之，不亦说乎。",
        "text_en": "To learn and practice what is learned time and again — is it not pleasant?",
        "author": "孔子",
        "primary_source": "《论语·学而》开篇",
        "verified_via": "ctext.org 论语 学而",
        "public_domain": "y",
        "topic_keys": ["burnout", "self_worth"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["zh_CN"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
]
