"""Japanese (ja_JP) canon — kotowaza, Bashō, Dōgen, Sōseki."""
from __future__ import annotations

JA_JP = [
    {
        "quote_id": "quote_anxiety_ja_jp_basho_narrow_road_v01",
        "text": "行く春や鳥啼魚の目は泪",
        "text_en": "Departing spring — the birds cry and the eyes of fish are filled with tears.",
        "author": "松尾芭蕉",
        "primary_source": "『おくのほそ道』初句付近（元禄2年）",
        "verified_via": "国文学研究資料館 おくのほそ道 底本",
        "public_domain": "y",
        "topic_keys": ["anxiety", "grief"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_anxiety_ja_jp_dogen_fukanzazengi_v01",
        "text": "身心脱落。",
        "text_en": "Body and mind drop away.",
        "author": "道元",
        "primary_source": "『普勧坐禅儀』",
        "verified_via": "曹洞宗標準典籍；PD",
        "public_domain": "y",
        "topic_keys": ["anxiety", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["ja_JP"],
        "secular_safe": False,
        "sensitivity_notes": "禅典；teacher-mode（kenjin等）のみ secular composite 不可",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_anxiety_ja_jp_kotowaza_v01",
        "text": "七転び八起き。",
        "text_en": "Fall seven times, stand up eight.",
        "author": "ことわざ",
        "primary_source": "日本国語大辞典 慣用句",
        "verified_via": "広辞苑・国語大辞典 慣用句条目",
        "public_domain": "y",
        "topic_keys": ["anxiety", "burnout", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_burnout_ja_jp_soseki_kokoro_v01",
        "text": "世の中は、結局、個人の心の中にある。",
        "text_en": "In the end, the world exists within the individual heart.",
        "author": "夏目漱石",
        "primary_source": "『こころ』第一章（明治44年）",
        "verified_via": "漱石全集 岩波書店底本（著作権消滅）",
        "public_domain": "y",
        "topic_keys": ["burnout", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_overthinking_ja_jp_kotowaza_v01",
        "text": "案ずるより産むが易し。",
        "text_en": "Giving birth is easier than worrying about it.",
        "author": "ことわざ",
        "primary_source": "日本国語大辞典",
        "verified_via": "広辞苑 慣用句",
        "public_domain": "y",
        "topic_keys": ["overthinking", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_imposter_ja_jp_kotowaza_v01",
        "text": "猿も木から落ちる。",
        "text_en": "Even monkeys fall from trees.",
        "author": "ことわざ",
        "primary_source": "日本国語大辞典",
        "verified_via": "広辞苑",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "self_worth"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_ja_jp_kotowaza_v01",
        "text": "塵も積もれば山となる。",
        "text_en": "Even dust, if it piles up, becomes a mountain.",
        "author": "ことわざ",
        "primary_source": "日本国語大辞典（類義：少しずつ積み重ねる）",
        "verified_via": "広辞苑",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_adhd_ja_jp_kotowaza_v01",
        "text": "塵も積もれば山となる。",
        "text_en": "Even dust, if it piles up, becomes a mountain — small focus builds.",
        "author": "ことわざ",
        "primary_source": "日本国語大辞典",
        "verified_via": "広辞苑",
        "public_domain": "y",
        "topic_keys": ["adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "Same kotowaza as financial; distinct quote_id for topic routing",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_anxiety_ja_jp_soseki_myriad_v01",
        "text": "月が綺麗ですね。",
        "text_en": "The moon is beautiful, isn't it?",
        "author": "夏目漱石",
        "primary_source": "漱石友人伝記・『吾輩は猫である』時代の逸話（「I love you」訳話の原典は逸話だが月の句は『山の月』等に類似表現）",
        "verified_via": "漱石研究における月の美学；『山の月』等 PD 作品",
        "public_domain": "y",
        "topic_keys": ["anxiety", "social_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "間接的表現の文化参照",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_burnout_ja_jp_kotowaza_v02",
        "text": "能ある鷹は爪を隠す。",
        "text_en": "A capable hawk hides its talons.",
        "author": "ことわざ",
        "primary_source": "日本国語大辞典",
        "verified_via": "広辞苑",
        "public_domain": "y",
        "topic_keys": ["burnout", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_anxiety_ja_jp_ryokan_v01",
        "text": "住吉の岸に吹く風の、身にしみて、涙ぐまざるを得ざりき。",
        "text_en": "The wind blowing on the Sumiyoshi shore pierced my body — I could not help but weep.",
        "author": "良寛",
        "primary_source": "良寛和歌（良寛全集）",
        "verified_via": "良寛全集 岩波",
        "public_domain": "y",
        "topic_keys": ["anxiety", "grief"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["ja_JP"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_overthinking_ja_jp_dogen_v02",
        "text": "只管打坐。",
        "text_en": "Just sit — single-minded sitting.",
        "author": "道元",
        "primary_source": "『正法眼蔵』坐禅儀",
        "verified_via": "道元著作 PD",
        "public_domain": "y",
        "topic_keys": ["overthinking", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["ja_JP"],
        "secular_safe": False,
        "sensitivity_notes": "禅；teacher-mode",
        "position_fit": "closer",
    },
]
