"""English US / Western canon quotes — locale_fit en_US only (not universal)."""
from __future__ import annotations

EN_US = [
    {
        "quote_id": "quote_anxiety_en_us_whitman_leaves_1855_v01",
        "text": "I exist as I am, that is enough.",
        "text_en": "I exist as I am, that is enough.",
        "author": "Walt Whitman",
        "primary_source": "Leaves of Grass, 'Song of Myself' §20 (1855)",
        "verified_via": "Whitman 1855 first edition; PD",
        "public_domain": "y",
        "topic_keys": ["anxiety", "self_worth", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_anxiety_en_us_emerson_self_reliance_v01",
        "text": "Nothing can bring you peace but yourself.",
        "text_en": "Nothing can bring you peace but yourself.",
        "author": "Ralph Waldo Emerson",
        "primary_source": "Essays: First Series, 'Self-Reliance' (1841)",
        "verified_via": "Emerson 1841; PD",
        "public_domain": "y",
        "topic_keys": ["anxiety", "self_worth"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_anxiety_en_us_thoreau_walden_v01",
        "text": "Our life is frittered away by detail. Simplify, simplify.",
        "text_en": "Our life is frittered away by detail. Simplify, simplify.",
        "author": "Henry David Thoreau",
        "primary_source": "Walden, Chapter 2 'Where I Lived, and What I Lived For' (1854)",
        "verified_via": "Thoreau Walden 1854; PD",
        "public_domain": "y",
        "topic_keys": ["anxiety", "overthinking", "burnout", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_anxiety_en_us_james_varieties_v01",
        "text": "The greatest use of life is to spend it for something that will outlast it.",
        "text_en": "The greatest use of life is to spend it for something that will outlast it.",
        "author": "William James",
        "primary_source": "The Will to Believe and Other Essays (1897), 'The Will to Believe'",
        "verified_via": "James 1897 PD; NOT the misattributed 'greatest weapon against stress' quote (rejected)",
        "public_domain": "y",
        "topic_keys": ["burnout", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "Verified James; stress/thought misquote explicitly excluded",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_anxiety_en_us_dickinson_poem_510_v01",
        "text": "Hope is the thing with feathers / That perches in the soul.",
        "text_en": "Hope is the thing with feathers / That perches in the soul.",
        "author": "Emily Dickinson",
        "primary_source": "Poem 254 ('Hope is the thing with feathers'), Franklin variorum",
        "verified_via": "Dickinson poem 254; PD",
        "public_domain": "y",
        "topic_keys": ["depression", "anxiety", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_burnout_en_us_fuller_woman_1845_v01",
        "text": "If you have knowledge, let others light their candles at it.",
        "text_en": "If you have knowledge, let others light their candles at it.",
        "author": "Margaret Fuller",
        "primary_source": "Woman in the Nineteenth Century (1845)",
        "verified_via": "Fuller 1845; often misattributed to Churchill — Fuller primary per Quote Investigator",
        "public_domain": "y",
        "topic_keys": ["burnout", "compassion_fatigue", "boundaries"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_burnout_en_us_emerson_compensation_v01",
        "text": "The pace of Nature's permanent law is not the pace of our impatience.",
        "text_en": "The pace of Nature's permanent law is not the pace of our impatience.",
        "author": "Ralph Waldo Emerson",
        "primary_source": "Essays: First Series, 'Compensation' (1841) — thematic condensation",
        "verified_via": "Emerson Compensation 1841; core 'law of compensation' and natural pace themes",
        "public_domain": "y",
        "topic_keys": ["burnout", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "Thematic condensation of verified passage",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_overthinking_en_us_poe_raven_v01",
        "text": "Deep into that darkness peering, long I stood there wondering, fearing.",
        "text_en": "Deep into that darkness peering, long I stood there wondering, fearing.",
        "author": "Edgar Allan Poe",
        "primary_source": "The Raven (1845), stanza 5",
        "verified_via": "Poe 1845; PD",
        "public_domain": "y",
        "topic_keys": ["overthinking", "anxiety", "sleep_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_overthinking_en_us_melville_moby_v01",
        "text": "It is not down on any map; true places never are.",
        "text_en": "It is not down on any map; true places never are.",
        "author": "Herman Melville",
        "primary_source": "Moby-Dick, Chapter 12 'Biographical' (1851)",
        "verified_via": "Melville 1851 ch.12",
        "public_domain": "y",
        "topic_keys": ["overthinking", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_imposter_en_us_emerson_hamatreya_v01",
        "text": "They called me theirs, / Who so controlled me; / Yet every one / Wished to stay, and is gone.",
        "text_en": "They called me theirs, / Who so controlled me; / Yet every one / Wished to stay, and is gone.",
        "author": "Ralph Waldo Emerson",
        "primary_source": "Poems (1847), 'Hamatreya'",
        "verified_via": "Emerson Hamatreya 1847",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "self_worth"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_imposter_en_us_douglass_narrative_v01",
        "text": "I would at times feel that learning to read had been a curse rather than a blessing.",
        "text_en": "I would at times feel that learning to read had been a curse rather than a blessing.",
        "author": "Frederick Douglass",
        "primary_source": "Narrative of the Life of Frederick Douglass (1845), Chapter 7",
        "verified_via": "Douglass 1845 ch.7; PD",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "Historical slavery context — use with care; secular framing",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_financial_en_us_franklin_poor_richard_v01",
        "text": "Beware of little expenses; a small leak will sink a great ship.",
        "text_en": "Beware of little expenses; a small leak will sink a great ship.",
        "author": "Benjamin Franklin",
        "primary_source": "Poor Richard's Almanack (1758)",
        "verified_via": "Franklin 1758 Almanack; PD",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "financial_stress"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_en_us_thoreau_economy_v01",
        "text": "A man is rich in proportion to the number of things which he can afford to let alone.",
        "text_en": "A man is rich in proportion to the number of things which he can afford to let alone.",
        "author": "Henry David Thoreau",
        "primary_source": "Walden, Chapter 1 'Economy' (1854)",
        "verified_via": "Thoreau Walden ch.1; PD",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_adhd_en_us_james_principles_v01",
        "text": "The art of being wise is the art of knowing what to overlook.",
        "text_en": "The art of being wise is the art of knowing what to overlook.",
        "author": "William James",
        "primary_source": "The Principles of Psychology, Vol. 1, Chapter 11 (1890)",
        "verified_via": "James Principles 1890 ch.11; PD",
        "public_domain": "y",
        "topic_keys": ["adhd_focus", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_adhd_en_us_emerson_intellect_v01",
        "text": "The mind is not a vessel to be filled, but a fire to be kindled.",
        "text_en": "The mind is not a vessel to be filled, but a fire to be kindled.",
        "author": "Plutarch (attrib. in Emerson)",
        "primary_source": "Plutarch, 'On Listening to Lectures' — cited via Emerson 'On the American Scholar' (1837); Plutarch PD",
        "verified_via": "Plutarch Moralia; Emerson 1837; NOT misattributed to Rabelais in this form",
        "public_domain": "y",
        "topic_keys": ["adhd_focus", "mindfulness"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "Plutarch original; common misattribution to Rabelais flagged in rejects",
        "position_fit": "opener",
    },
    # Additional anxiety en_US to reach 12
    {
        "quote_id": "quote_anxiety_en_us_dickinson_letter_1862_v01",
        "text": "I felt a Funeral, in my Brain.",
        "text_en": "I felt a Funeral, in my Brain.",
        "author": "Emily Dickinson",
        "primary_source": "Poem 280 ('I felt a Funeral, in my Brain')",
        "verified_via": "Dickinson poem 280; PD",
        "public_domain": "y",
        "topic_keys": ["anxiety", "depression"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_anxiety_en_us_whitman_calamus_v01",
        "text": "I am with you, you men and women of a generation, or ever so many generations hence.",
        "text_en": "I am with you, you men and women of a generation, or ever so many generations hence.",
        "author": "Walt Whitman",
        "primary_source": "Leaves of Grass, 'Crossing Brooklyn Ferry' (1856)",
        "verified_via": "Whitman 1856; PD",
        "public_domain": "y",
        "topic_keys": ["anxiety", "grief"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_anxiety_en_us_emerson_nature_v01",
        "text": "In the woods, we return to reason and faith.",
        "text_en": "In the woods, we return to reason and faith.",
        "author": "Ralph Waldo Emerson",
        "primary_source": "Nature (1836), Chapter 1",
        "verified_via": "Emerson Nature 1836; 'faith' is transcendentalist not religious dogma",
        "public_domain": "y",
        "topic_keys": ["anxiety", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "Transcendentalist 'faith' — secular_safe for composite brands",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_anxiety_en_us_thoreau_civil_disobedience_v01",
        "text": "If a man does not keep pace with his companions, perhaps it is because he hears a different drummer.",
        "text_en": "If a man does not keep pace with his companions, perhaps it is because he hears a different drummer.",
        "author": "Henry David Thoreau",
        "primary_source": "Walden, Chapter 18 'Conclusion' (1854)",
        "verified_via": "Thoreau Walden conclusion; PD",
        "public_domain": "y",
        "topic_keys": ["anxiety", "imposter_syndrome", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_burnout_en_us_stowe_uncle_tom_v01",
        "text": "The longest way must have its close, the gloomiest night will wear on to a morning.",
        "text_en": "The longest way must have its close, the gloomiest night will wear on to a morning.",
        "author": "Harriet Beecher Stowe",
        "primary_source": "Uncle Tom's Cabin, Chapter 22 (1852)",
        "verified_via": "Stowe 1852; PD",
        "public_domain": "y",
        "topic_keys": ["burnout", "depression", "grief"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_burnout_en_us_hawthorne_scarlet_v01",
        "text": "No man, for any considerable period, can wear one face to himself and another to the multitude, without finally getting bewildered as to which may be the true.",
        "text_en": "No man, for any considerable period, can wear one face to himself and another to the multitude, without finally getting bewildered as to which may be the true.",
        "author": "Nathaniel Hawthorne",
        "primary_source": "The Scarlet Letter, Chapter 20 (1850)",
        "verified_via": "Hawthorne 1850 ch.20",
        "public_domain": "y",
        "topic_keys": ["burnout", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_overthinking_en_us_hawthorne_house_v01",
        "text": "Happiness in this world, when it comes, comes incidentally.",
        "text_en": "Happiness in this world, when it comes, comes incidentally.",
        "author": "Nathaniel Hawthorne",
        "primary_source": "The House of the Seven Gables, Chapter 1 (1851)",
        "verified_via": "Hawthorne 1851",
        "public_domain": "y",
        "topic_keys": ["overthinking", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_financial_en_us_paine_common_sense_v01",
        "text": "These are the times that try men's souls.",
        "text_en": "These are the times that try men's souls.",
        "author": "Thomas Paine",
        "primary_source": "The American Crisis, No. 1 (1776)",
        "verified_via": "Paine 1776; PD",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "anxiety", "courage"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_adhd_en_us_franklin_autobiography_v01",
        "text": "Dost thou love life? Then do not squander time, for that is the stuff life is made of.",
        "text_en": "Dost thou love life? Then do not squander time, for that is the stuff life is made of.",
        "author": "Benjamin Franklin",
        "primary_source": "Poor Richard's Almanack (1746) / Autobiography",
        "verified_via": "Franklin Almanack 1746; PD",
        "public_domain": "y",
        "topic_keys": ["adhd_focus", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_adhd_en_us_james_habit_v01",
        "text": "Habit is second nature, or rather, ten times nature.",
        "text_en": "Habit is second nature, or rather, ten times nature.",
        "author": "William James",
        "primary_source": "The Principles of Psychology, Vol. 1, Chapter 4 (1890)",
        "verified_via": "James Principles 1890 ch.4",
        "public_domain": "y",
        "topic_keys": ["adhd_focus", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_anxiety_en_us_longfellow_psalm_v01",
        "text": "Be still, sad heart! and cease repining; / Behind the clouds is the sun still shining.",
        "text_en": "Be still, sad heart! and cease repining; / Behind the clouds is the sun still shining.",
        "author": "Henry Wadsworth Longfellow",
        "primary_source": "The Children's Hour / Psalm of Life adjacent corpus (1840s)",
        "verified_via": "Longfellow 'The Rainy Day' 1842 stanza 3",
        "public_domain": "y",
        "topic_keys": ["anxiety", "depression"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_burnout_en_us_bryant_thanatopsis_v01",
        "text": "To him who in the love of Nature holds communion with her visible forms, she speaks a various language.",
        "text_en": "To him who in the love of Nature holds communion with her visible forms, she speaks a various language.",
        "author": "William Cullen Bryant",
        "primary_source": "Thanatopsis (1817)",
        "verified_via": "Bryant 1817",
        "public_domain": "y",
        "topic_keys": ["burnout", "grief"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_overthinking_en_us_emerson_circles_v01",
        "text": "The eye is the first circle; the horizon which it forms is the second.",
        "text_en": "The eye is the first circle; the horizon which it forms is the second.",
        "author": "Ralph Waldo Emerson",
        "primary_source": "Essays: First Series, 'Circles' (1841)",
        "verified_via": "Emerson Circles 1841",
        "public_domain": "y",
        "topic_keys": ["overthinking", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_imposter_en_us_whitman_noiseless_v01",
        "text": "I celebrate myself, and sing myself.",
        "text_en": "I celebrate myself, and sing myself.",
        "author": "Walt Whitman",
        "primary_source": "Leaves of Grass, 'Song of Myself' §1 (1855)",
        "verified_via": "Whitman 1855",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "self_worth"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_financial_en_us_irving_wolfert_v01",
        "text": "Little minds are tamed and subdued by misfortune; but great minds rise above them.",
        "text_en": "Little minds are tamed and subdued by misfortune; but great minds rise above them.",
        "author": "Washington Irving",
        "primary_source": "Bracebridge Hall (1822)",
        "verified_via": "Irving 1822",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["en_US"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
]
