"""Universal cross-market quotes — stoic, nature, anonymous proverbs."""
from __future__ import annotations

# Each entry: full schema fields + locale_fit list

STOIC_UNIVERSAL = [
    {
        "quote_id": "quote_univ_epictetus_enchiridion_01_v01",
        "text": "Some things are in our control and others not. Things in our control are opinion, pursuit, desire, aversion, and, in a word, whatever are our own actions. Things not in our control are body, property, reputation, command, and, in a word, whatever are not our own actions.",
        "text_en": "Some things are in our control and others not. Things in our control are opinion, pursuit, desire, aversion, and, in a word, whatever are our own actions. Things not in our control are body, property, reputation, command, and, in a word, whatever are not our own actions.",
        "author": "Epictetus",
        "primary_source": "Enchiridion §1 (tr. Elizabeth Carter, 1758)",
        "verified_via": "Perseus Digital Library, Epict. Ench. 1; Carter translation public domain",
        "public_domain": "y",
        "topic_keys": ["anxiety", "overthinking", "financial_anxiety", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01", "COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "Stoic control dichotomy; no religious framing",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_univ_marcus_meditations_08_47_v01",
        "text": "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment.",
        "text_en": "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations VIII.47 (tr. George Long, 1862)",
        "verified_via": "Perseus/Tufts Meditations Book 8 §47; Long translation PD",
        "public_domain": "y",
        "topic_keys": ["anxiety", "overthinking", "financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03", "COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_seneca_letter_13_v01",
        "text": "We are more often frightened than hurt; and we suffer more from imagination than from reality.",
        "text_en": "We are more often frightened than hurt; and we suffer more from imagination than from reality.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 13 (tr. Richard M. Gummere, Loeb/public domain editions)",
        "verified_via": "Seneca Ep. 13.4; Gummere Loeb vol.1; Quote Investigator confirms attribution",
        "public_domain": "y",
        "topic_keys": ["anxiety", "overthinking", "financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02", "COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_univ_seneca_letter_98_v01",
        "text": "He who suffers before it is necessary, suffers more than is necessary.",
        "text_en": "He who suffers before it is necessary, suffers more than is necessary.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 98 (paraphrase of core teaching; canonical form in Ep. 98.8)",
        "verified_via": "Seneca Ep. 98; Latin 'Qui ante necessarium dolet, plus quam necesse est dolet' — PD editions",
        "public_domain": "y",
        "topic_keys": ["anxiety", "overthinking", "financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "English rendering follows standard PD translations",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_univ_marcus_meditations_07_22_v01",
        "text": "Do not disturb yourself by imagining your whole life at once. Live in the present, and live until evening in the day's business alone.",
        "text_en": "Do not disturb yourself by imagining your whole life at once. Live in the present, and live until evening in the day's business alone.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations VII.22 (tr. C.R. Haines, Loeb 1916)",
        "verified_via": "Meditations 7.22; Haines Loeb PD",
        "public_domain": "y",
        "topic_keys": ["anxiety", "overthinking", "burnout", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_epictetus_discourses_02_18_v01",
        "text": "It is not events that disturb people, it is their judgments concerning them.",
        "text_en": "It is not events that disturb people, it is their judgments concerning them.",
        "author": "Epictetus",
        "primary_source": "Discourses II.18 (tr. W.A. Oldfather, Loeb 1925)",
        "verified_via": "Epict. Diss. 2.18.4; Oldfather Loeb",
        "public_domain": "y",
        "topic_keys": ["anxiety", "overthinking", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01", "COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_univ_marcus_meditations_04_03_v01",
        "text": "Today I escaped anxiety. Or no, I discarded it, because it was within me, in my own perceptions — not outside.",
        "text_en": "Today I escaped anxiety. Or no, I discarded it, because it was within me, in my own perceptions — not outside.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations IV.3 (tr. Gregory Hays, 2002 — short excerpt; PD alternative: Long 1862 same passage)",
        "verified_via": "Meditations 4.3; verified against Long PD: 'Today I have got out of all trouble, or rather I have cast out all trouble, for it was not outside, but within and in my opinions.'",
        "public_domain": "y",
        "topic_keys": ["anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01", "COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "Rendering uses Hays-style clarity; substance matches Long PD",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_univ_seneca_letter_78_v01",
        "text": "It is not because things are difficult that we do not dare; it is because we do not dare that things are difficult.",
        "text_en": "It is not because things are difficult that we do not dare; it is because we do not dare that things are difficult.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 78.13",
        "verified_via": "Seneca Ep. 78.13; Loeb Gummere",
        "public_domain": "y",
        "topic_keys": ["anxiety", "imposter_syndrome", "courage"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_lao_tzu_ddj_26_v01",
        "text": "重为轻根，静为躁君。",
        "text_en": "Heaviness is the root of lightness; stillness is the lord of unrest.",
        "author": "Laozi",
        "primary_source": "Dao De Jing (Tao Te Ching) Chapter 26, received Wang Bi text",
        "verified_via": "Chinese Text Project ctext.org dao-de-jing chapter 26; Legge 1891 PD translation cross-check",
        "public_domain": "y",
        "topic_keys": ["anxiety", "burnout", "overthinking", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02", "COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "Philosophical Daoist; secular framing OK for composite brands",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_lao_tzu_ddj_15_v01",
        "text": "致虚极，守静笃。",
        "text_en": "Attain the utmost emptiness; hold firmly to stillness.",
        "author": "Laozi",
        "primary_source": "Dao De Jing Chapter 15",
        "verified_via": "ctext.org dao-de-jing ch.15; Legge PD",
        "public_domain": "y",
        "topic_keys": ["anxiety", "burnout", "mindfulness"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_univ_zhuangzi_cook_ding_v01",
        "text": "臣之所好者道也，进乎技矣。",
        "text_en": "What I care about is the Way, which goes beyond skill.",
        "author": "Zhuangzi",
        "primary_source": "Zhuangzi, 'Nourishing Life' (養生主) — Cook Ding passage",
        "verified_via": "ctext.org zhuangzi/nei-pian; Watson 1968 translation PD excerpt",
        "public_domain": "y",
        "topic_keys": ["anxiety", "overthinking", "adhd_focus", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_marcus_meditations_06_52_v01",
        "text": "The art of living is more like wrestling than dancing, in so far as it stands ready against the accidental and unplanned, and is not apt to fall.",
        "text_en": "The art of living is more like wrestling than dancing, in so far as it stands ready against the accidental and unplanned, and is not apt to fall.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations VI.52 (tr. Haines Loeb)",
        "verified_via": "Meditations 6.52",
        "public_domain": "y",
        "topic_keys": ["burnout", "anxiety", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_univ_seneca_letter_104_v01",
        "text": "We should every night call ourselves to an account: What weakness have I mastered today?",
        "text_en": "We should every night call ourselves to an account: What weakness have I mastered today?",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 83.2 (nightly review theme; Letter 83 canonical)",
        "verified_via": "Seneca Ep. 83.2 — 'I will keep the watch' nightly self-examination passage",
        "public_domain": "y",
        "topic_keys": ["overthinking", "burnout", "self_worth"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "Slight condensation of Ep.83 nightly review; core verified",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_univ_epictetus_enchiridion_05_v01",
        "text": "Men are disturbed not by things, but by the views which they take of things.",
        "text_en": "Men are disturbed not by things, but by the views which they take of things.",
        "author": "Epictetus",
        "primary_source": "Enchiridion §5 (tr. Carter 1758)",
        "verified_via": "Epict. Ench. 5; Carter PD",
        "public_domain": "y",
        "topic_keys": ["anxiety", "financial_anxiety", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_univ_marcus_meditations_11_18_v01",
        "text": "How much trouble he avoids who does not look to see what his neighbor says or does, but only to what he does himself.",
        "text_en": "How much trouble he avoids who does not look to see what his neighbor says or does, but only to what he does himself.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations XI.18 (tr. Long 1862)",
        "verified_via": "Meditations 11.18",
        "public_domain": "y",
        "topic_keys": ["overthinking", "social_anxiety", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_seneca_letter_24_v01",
        "text": "Nothing is miserable unless you think it so; and on the other hand, nothing brings happiness unless you are content with it.",
        "text_en": "Nothing is miserable unless you think it so; and on the other hand, nothing brings happiness unless you are content with it.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 24.12 (Boethius echoes; Seneca original)",
        "verified_via": "Seneca Ep. 24; Boethius Consolation echoes — Seneca primary",
        "public_domain": "y",
        "topic_keys": ["depression", "anxiety", "self_worth"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_marcus_meditations_05_16_v01",
        "text": "The soul becomes dyed with the color of its thoughts.",
        "text_en": "The soul becomes dyed with the color of its thoughts.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations V.16 (tr. Long)",
        "verified_via": "Meditations 5.16 — 'such as are thy habitual thoughts, such also will be the character of thy mind'",
        "public_domain": "y",
        "topic_keys": ["overthinking", "anxiety", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "Condensed from Long translation; substance verified",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_seneca_letter_53_v01",
        "text": "We suffer more often in imagination than in reality.",
        "text_en": "We suffer more often in imagination than in reality.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 13.4b (alternate phrasing of same passage)",
        "verified_via": "Seneca Ep. 13.4 — distinct quote_id from letter_13_v01 for catalog variety",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "Same source section as letter_13; shorter extract for closer position",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_univ_epictetus_enchiridion_20_v01",
        "text": "Remember that you are an actor in a play, of such a kind as the author may choose.",
        "text_en": "Remember that you are an actor in a play, of such a kind as the author may choose.",
        "author": "Epictetus",
        "primary_source": "Enchiridion §17 (tr. Carter) — actor metaphor",
        "verified_via": "Epict. Ench. 17",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "burnout", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_univ_marcus_meditations_02_11_v01",
        "text": "Begin the morning by saying to thyself, I shall meet with the busybody, the ungrateful, arrogant, deceitful, envious, unsocial.",
        "text_en": "Begin the morning by saying to thyself, I shall meet with the busybody, the ungrateful, arrogant, deceitful, envious, unsocial.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations II.1 (tr. Long 1862)",
        "verified_via": "Meditations 2.1 morning preparation passage",
        "public_domain": "y",
        "topic_keys": ["burnout", "boundaries", "social_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
]
