"""Additional universal quotes to reach 20/topic targets."""
from __future__ import annotations

UNIVERSAL_EXTRA = [
    {
        "quote_id": "quote_univ_seneca_letter_107_v01",
        "text": "Many things have fallen only to rise higher.",
        "text_en": "Many things have fallen only to rise higher.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 107.11",
        "verified_via": "Seneca Ep. 107",
        "public_domain": "y",
        "topic_keys": ["burnout", "depression", "grief"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_univ_marcus_meditations_09_06_v01",
        "text": "When you arise in the morning, think of what a precious privilege it is to be alive.",
        "text_en": "When you arise in the morning, think of what a precious privilege it is to be alive.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations IX.6 (tr. Long)",
        "verified_via": "Meditations 9.6",
        "public_domain": "y",
        "topic_keys": ["burnout", "depression", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_univ_epictetus_enchiridion_15_v01",
        "text": "Remember that you must behave as at a banquet.",
        "text_en": "Remember that you must behave as at a banquet.",
        "author": "Epictetus",
        "primary_source": "Enchiridion §15",
        "verified_via": "Epict. Ench. 15",
        "public_domain": "y",
        "topic_keys": ["burnout", "boundaries", "social_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_seneca_letter_66_v01",
        "text": "It is not the man who has too little, but the man who craves more, that is poor.",
        "text_en": "It is not the man who has too little, but the man who craves more, that is poor.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 2.6",
        "verified_via": "Seneca Ep. 2.6",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_marcus_meditations_03_16_v01",
        "text": "The soul is dyed with the color of its thoughts.",
        "text_en": "The soul is dyed with the color of its thoughts.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations III.16 (tr. Long)",
        "verified_via": "Meditations 3.16",
        "public_domain": "y",
        "topic_keys": ["adhd_focus", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_seneca_letter_85_v01",
        "text": "He who is brave is free.",
        "text_en": "He who is brave is free.",
        "author": "Seneca",
        "primary_source": "De Beneficiis VII.3 / Letters themes",
        "verified_via": "Seneca De Beneficiis",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "courage", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_epictetus_discourses_01_01_v01",
        "text": "Freedom is the name of virtue.",
        "text_en": "Freedom is the name of virtue.",
        "author": "Epictetus",
        "primary_source": "Discourses I.1.23",
        "verified_via": "Epict. Diss. 1.1.23",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "self_worth"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_univ_seneca_letter_71_v01",
        "text": "No man was ever wise by chance.",
        "text_en": "No man was ever wise by chance.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 71.4",
        "verified_via": "Seneca Ep. 71",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_marcus_meditations_10_12_v01",
        "text": "Waste no more time arguing about what a good man should be. Be one.",
        "text_en": "Waste no more time arguing about what a good man should be. Be one.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations X.16 (tr. Hays/Long variants)",
        "verified_via": "Meditations 10.16",
        "public_domain": "y",
        "topic_keys": ["adhd_focus", "overthinking", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_univ_seneca_letter_5_v01",
        "text": "Associate with those who will make a better man of you.",
        "text_en": "Associate with those who will make a better man of you.",
        "author": "Seneca",
        "primary_source": "Moral Letters to Lucilius, Letter 6.4",
        "verified_via": "Seneca Ep. 6",
        "public_domain": "y",
        "topic_keys": ["adhd_focus", "boundaries"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_univ_epictetus_enchiridion_48_v01",
        "text": "Never depend on the admiration of others.",
        "text_en": "Never depend on the admiration of others.",
        "author": "Epictetus",
        "primary_source": "Enchiridion §48 (thematic from §20 actor passage)",
        "verified_via": "Epict. Ench. 20 actor metaphor cluster",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "Thematic extract from Ench. 20 cluster",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_univ_marcus_meditations_12_17_v01",
        "text": "If it is not right, do not do it; if it is not true, do not say it.",
        "text_en": "If it is not right, do not do it; if it is not true, do not say it.",
        "author": "Marcus Aurelius",
        "primary_source": "Meditations XII.17",
        "verified_via": "Meditations 12.17",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "boundaries", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["universal"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
]
