"""Traditional Chinese (zh-TW) — broader canon, Buddhist sources tagged."""
from __future__ import annotations

ZH_TW = [
    {
        "quote_id": "quote_anxiety_zh_tw_heart_sutra_v01",
        "text": "色不異空，空不異色。",
        "text_en": "Form is not different from emptiness; emptiness is not different from form.",
        "author": "般若波羅蜜多心經",
        "primary_source": "《般若波羅蜜多心經》（玄奘譯本）",
        "verified_via": "大正新脩大藏經 T08, no. 251; ctext.org",
        "public_domain": "y",
        "topic_keys": ["anxiety", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["zh_TW"],
        "secular_safe": False,
        "sensitivity_notes": "佛教經典；teacher-mode 品牌可用；composite 品牌禁用",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_anxiety_zh_tw_laozi_ddj_26_v01",
        "text": "重為輕根，靜為躁君。",
        "text_en": "Heaviness is the root of lightness; stillness is the lord of unrest.",
        "author": "老子",
        "primary_source": "《道德經》第二十六章",
        "verified_via": "ctext.org 道德經 26 繁體",
        "public_domain": "y",
        "topic_keys": ["anxiety", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_anxiety_zh_tw_su_shi_v01",
        "text": "回首向來蕭瑟處，歸去，也無風雨也無晴。",
        "text_en": "Looking back on the wind and rain — going home, neither storm nor clear sky.",
        "author": "蘇軾",
        "primary_source": "《定風波·莫聽穿林打葉聲》",
        "verified_via": "全宋詞",
        "public_domain": "y",
        "topic_keys": ["anxiety", "grief", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v05"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_burnout_zh_tw_zhuangzi_v01",
        "text": "吾生也有涯，而知也無涯。以有涯隨無涯，殆已！",
        "text_en": "Life has limits, but knowledge has none. To chase the limitless with the limited — perilous!",
        "author": "莊子",
        "primary_source": "《莊子·養生主》",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["burnout", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_overthinking_zh_tw_wang_yangming_v01",
        "text": "知行合一。",
        "text_en": "Knowledge and action are one.",
        "author": "王陽明",
        "primary_source": "《傳習錄》",
        "verified_via": "傳習錄標準版本",
        "public_domain": "y",
        "topic_keys": ["overthinking", "adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_imposter_zh_tw_mencius_v01",
        "text": "人皆可以為堯舜。",
        "text_en": "Every person can become like Yao and Shun.",
        "author": "孟子",
        "primary_source": "《孟子·告子下》",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["imposter_syndrome", "self_worth"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_zh_tw_laozi_44_v01",
        "text": "知足不辱，知止不殆。",
        "text_en": "Knowing contentment, you are not disgraced; knowing when to stop, you are not endangered.",
        "author": "老子",
        "primary_source": "《道德經》第四十四章",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v03"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
    {
        "quote_id": "quote_adhd_zh_tw_zhuangzi_v01",
        "text": "用志不分，乃凝於神。",
        "text_en": "When will is undivided, the spirit concentrates.",
        "author": "莊子",
        "primary_source": "《莊子·達生》",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["adhd_focus"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_anxiety_zh_tw_dhammapada_v01",
        "text": "心為法先，心為主，心為造，若淨若污，皆自心作。",
        "text_en": "Mind precedes all phenomena; mind is chief; mind-made are they. If with a pure mind one speaks or acts, happiness follows.",
        "author": "法句經",
        "primary_source": "《法句經》第1偈（耶舍羅譯）",
        "verified_via": "Dhammapada v.1; Pali Text Society PD",
        "public_domain": "y",
        "topic_keys": ["anxiety", "overthinking"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_TW"],
        "secular_safe": False,
        "sensitivity_notes": "佛教；teacher-mode only",
        "position_fit": "opener",
    },
    {
        "quote_id": "quote_burnout_zh_tw_confucius_v01",
        "text": "君子坦蕩蕩，小人長戚戚。",
        "text_en": "The noble person is at ease; the petty person is always anxious.",
        "author": "孔子",
        "primary_source": "《論語·述而》",
        "verified_via": "ctext.org 論語 述而",
        "public_domain": "y",
        "topic_keys": ["burnout", "anxiety"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v02"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_anxiety_zh_tw_confucius_v02",
        "text": "不患人之不己知，患不知人也。",
        "text_en": "Do not worry that others do not know you; worry that you do not know others.",
        "author": "孔子",
        "primary_source": "《論語·學而》",
        "verified_via": "ctext.org",
        "public_domain": "y",
        "topic_keys": ["anxiety", "social_anxiety", "imposter_syndrome"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v04"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "either",
    },
    {
        "quote_id": "quote_financial_zh_tw_chengyu_v01",
        "text": "細水長流。",
        "text_en": "Fine water flows long — steady small gains endure.",
        "author": "諺語",
        "primary_source": "《西遊記》第九回化出之俗語（明清小說）",
        "verified_via": "西遊記 PD；成語辭源",
        "public_domain": "y",
        "topic_keys": ["financial_anxiety", "burnout"],
        "doctrine_keys": ["COMPOSITE_DOCTRINE v01"],
        "locale_fit": ["zh_TW"],
        "secular_safe": True,
        "sensitivity_notes": "",
        "position_fit": "closer",
    },
]
