#!/usr/bin/env python3
"""
Add the mecha genre to the catalog (planning-level), per OQ-1 / D-9.
====================================================================

Mecha is governance-canonical (MANGA_CATALOG_RECONCILIATION_SPEC OQ-1 disposition
(a) "own genre", D-9; in series_plan.schema.json enum + canonical_genre_list
`must_include: yes`) but was never generated into any locale's series_plans (the
270-regen predated the promotion). This emits the missing mecha series_plan.yaml
per config/manga/brand_genre_allocation.yaml's mecha cells:

  bright_presence_tw_seinen  zh_TW (30% — Adi Da tentpole)           x2
  warrior_calm_cultivation   en_US/ja_JP/zh_TW/zh_CN                 x1 each
  solar_return_isekai        en_US/ja_JP/zh_TW/zh_CN                 x1 each
  digital_ground             ja_JP                                  x1
  (ko_KR has no mecha allocation)

Format per config/manga/format_routing.yaml mecha rules: ja_JP is print-first
(bw_page_manga, Evangelion/Gundam register); others color_vertical_webtoon.
topic = brand primary/secondary (rotated); manga_author = deterministic EI name.
title is left TBD for the title-synthesis pass. RENDER stays deferred (blocked on
the adi_da + Animagine mecha LoRAs — see artifacts/research/license_risk_register).

Additive only — new files, never modifies existing series. Usage:
  python3 scripts/manga/generate_mecha_series_plans.py [--dry-run]
"""

from __future__ import annotations

import argparse
import glob
import sys
from pathlib import Path

import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))
from generate_manga_author import generate_display_name  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
SERIES_ROOT = REPO / "config" / "source_of_truth" / "manga_series_plans"
CANON = REPO / "config" / "manga" / "canonical_brand_list.yaml"

# (canonical_brand_id, locale, count) — derived from brand_genre_allocation.yaml mecha cells
MECHA_PLAN = [
    ("bright_presence_tw_seinen", "zh_TW", 2),
    ("warrior_calm_cultivation", "en_US", 1),
    ("warrior_calm_cultivation", "ja_JP", 1),
    ("warrior_calm_cultivation", "zh_TW", 1),
    ("warrior_calm_cultivation", "zh_CN", 1),
    ("solar_return_isekai", "en_US", 1),
    ("solar_return_isekai", "ja_JP", 1),
    ("solar_return_isekai", "zh_TW", 1),
    ("solar_return_isekai", "zh_CN", 1),
    ("digital_ground", "ja_JP", 1),
]

# config/manga/format_routing.yaml mecha master_format per locale
MECHA_MASTER = {
    "en_US": "color_vertical_webtoon", "ja_JP": "bw_page_manga",
    "zh_TW": "color_vertical_webtoon", "zh_CN": "color_vertical_webtoon",
}
MECHA_FLATTEN = {"en_US": ["bw_page_manga"], "ja_JP": [], "zh_TW": ["bw_page_manga"], "zh_CN": []}
LOCALE_ORIGIN = {"en_US": "us", "ja_JP": "jp", "zh_TW": "tw", "zh_CN": "cn"}

FORMAT_BLOCK = {
    "color_vertical_webtoon": {
        "connector_lane": "unified_canvas",
        "panel_layout_template": "config/manga/panel_layout_templates/vertical_scroll_webtoon.yaml",
        "target_platforms": ["webtoon_canvas", "line_manga_indies", "bookwalker"],
        "pending_partner_targets": ["line_manga_originals"],
    },
    "bw_page_manga": {
        "connector_lane": "print_only",
        "panel_layout_template": "config/manga/panel_layout_templates/bw_page_rtl.yaml",
        "target_platforms": ["bookwalker", "comic_cmoa", "line_manga_indies", "amazon_kdp_comics"],
        "pending_partner_targets": ["piccoma_smartoon", "line_manga_originals"],
    },
}

HEADER = (
    "# Auto-generated by scripts/manga/generate_mecha_series_plans.py — do not hand-edit.\n"
    "# Mecha genre (OQ-1 / D-9) added planning-level per config/manga/brand_genre_allocation.yaml.\n"
    "# Format: config/manga/format_routing.yaml mecha rules. Schema: series_plan.schema.json v2.1.0.\n"
    "# RENDER deferred (adi_da + Animagine mecha LoRA blockers). title=TBD for the title pass.\n\n"
)


def _load(p: Path):
    with open(p, encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def _template_for(brand: str, locale: str) -> dict:
    hits = sorted(glob.glob(str(SERIES_ROOT / locale / f"{brand}__*.yaml")))
    if not hits:
        raise SystemExit(f"no template series for {brand} / {locale}")
    return _load(Path(hits[0]))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    brands = (_load(CANON) or {}).get("brands", {})

    written = 0
    for brand, locale, count in MECHA_PLAN:
        tmpl = _template_for(brand, locale)
        binfo = brands.get(brand, {})
        topics = [binfo.get("primary_topic", "")] + list(binfo.get("secondary_topics", []) or [])
        topics = [t for t in topics if t] or ["self_worth"]
        master = MECHA_MASTER[locale]
        fb = FORMAT_BLOCK[master]
        for i in range(1, count + 1):
            topic = topics[(i - 1) % len(topics)]
            sid = f"{brand}__{locale}__mecha__series{i:02d}"
            author = generate_display_name(genre="mecha", locale=locale, brand_id=brand,
                                           topic=topic, demographic=binfo.get("demographic", "general"))
            sp = {
                "series_plan_schema": "2.1.0",
                "series_id": sid,
                "brand_id": brand,
                "teacher_id": tmpl.get("teacher_id"),
                "locale": locale,
                "default_locale": locale,
                "format": master,
                "master_format": master,
                "flatten_exports": MECHA_FLATTEN[locale],
                "connector_lane": fb["connector_lane"],
                "panel_layout_template": fb["panel_layout_template"],
                "target_platforms": fb["target_platforms"],
                "pending_partner_targets": fb["pending_partner_targets"],
                "title": "TBD",
                "localized_titles": {locale: "TBD"},
                "genre": "mecha",
                "demographic": tmpl.get("demographic", "general"),
                "locale_origin": LOCALE_ORIGIN[locale],
                "distribution_status": tmpl.get("distribution_status", "distributed"),
                "topic": topic,
                "manga_author": author,
                "chapters_target": 14,
                "ai_disclosure_required": True,
            }
            out = SERIES_ROOT / locale / f"{sid}.yaml"
            print(f"  {'[dry] ' if args.dry_run else ''}{locale}/{brand} mecha s{i:02d}  topic={topic}  author={author}  fmt={master}")
            if not args.dry_run:
                with open(out, "w", encoding="utf-8") as fh:
                    fh.write(HEADER)
                    yaml.dump(sp, fh, allow_unicode=True, default_flow_style=False, sort_keys=False)
            written += 1
    print(f"mecha series {'planned' if args.dry_run else 'written'}: {written}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
