#!/usr/bin/env python3
"""
Native ko_KR (Korean) manga/webtoon title / topic / EI-author synthesis for SSOT.
==================================================================================

Fills the `title` / `localized_titles.ko_KR` / `topic` / `manga_author` fields
(currently ``TBD``) on the ~270 live ko_KR series plans at
``config/source_of_truth/manga_series_plans/ko_KR/*.yaml``.

Mirrors ``scripts/manga/synthesize_manga_titles_jajp.py`` (the MERGED ja_JP
precedent, PR #1772) for ``apply_edits`` / clinical-leak filter / dedup /
topic round-robin. The ONE difference: ko_KR titles are AUTHORED BY CLAUDE
(Pearl_Writer), not generated by Qwen/Ollama — the Korean lexicon and
composition grammar below are Claude-authored. NO LLM is called at runtime
(deterministic), NO paid API, NO render, no other locale touched.

Per-field provenance (LLM tier policy compliant):
  - title          → Claude-authored native Korean (한글) webtoon title.
                     Genre-faithful; the wellness `topic` is INTERIOR
                     architecture (Genre Shell thesis) — NEVER an explicit
                     self-help / clinical term. Vertical-scroll webtoon
                     register. Deterministic selection + global &
                     within-brand uniqueness disambiguation.
  - topic          → deterministic round-robin of the brand's primary +
                     secondary topics across its series. No LLM.
  - manga_author   → generate_manga_author.generate_display_name. Deterministic.
                     (No ko_KR name pool exists → falls back to the EN pool;
                     acceptable per task brief.) No LLM.

In-place, idempotent: only `: TBD` lines are rewritten, so partial runs resume
and re-runs never clobber filled values. File comments / field order preserved
(targeted line replacement, not a YAML round-trip).

Usage:
  python3 scripts/manga/synthesize_manga_titles_kokr.py            # all ~270
  python3 scripts/manga/synthesize_manga_titles_kokr.py --brand stillness_press
  python3 scripts/manga/synthesize_manga_titles_kokr.py --limit 3 --no-write
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import re
import sys
import time
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))
from generate_manga_author import generate_display_name  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
_MAIN_REPO = Path("/Users/ahjan/phoenix_omega")
ROOT = _MAIN_REPO if (not (REPO_ROOT / "config").exists()
                      and (_MAIN_REPO / "config").exists()) else REPO_ROOT

SERIES_DIR = ROOT / "config" / "source_of_truth" / "manga_series_plans" / "ko_KR"
CANONICAL_BRANDS = ROOT / "config" / "manga" / "canonical_brand_list.yaml"
REVIEW_OUT = ROOT / "artifacts" / "catalog" / "manga" / "ssot_rollup" / "ko_KR_title_synthesis_review.csv"

# ───────────────────────────────────────────────────────────────────────────
# Claude-authored Korean title engine (Genre Shell thesis).
#
# Composition grammar:  <IMAGE_NOUN><CONNECTOR><GENRE_HEAD>  or a standalone
# striking PHRASE.  The reader is sold the GENRE; the wellness topic is the
# INTERIOR architecture (the noun is chosen to *resonate* with the topic
# without ever naming it clinically).  All strings are native Korean (한글),
# short, bestseller/webtoon-shaped.
#
# Per (genre, topic): a list of distinct, fully-formed candidate titles.
# The Nth global occurrence of a (genre, topic) pair takes the Nth candidate;
# a deterministic native disambiguator is appended only if a title would still
# collide globally (rare — banks are sized ≥ the max global cell of 10).
# ───────────────────────────────────────────────────────────────────────────

# Genre register heads (native Korean nouns evoking each genre's promise).
# Used by the fallback composer when a (genre, topic) cell runs short.
_GENRE_HEADS: dict[str, list[str]] = {
    "iyashikei": ["오후", "정원", "골목", "창가", "햇살", "찻집", "산책", "온기", "빈터", "노을", "툇마루", "물결"],
    "dark_fantasy": ["저주", "마탑", "심연", "흑야", "사슬", "재앙", "고룡", "잿빛 성", "낙인", "주박", "왕좌", "마수"],
    "psychological_thriller": ["밀실", "추적", "거짓말", "공범", "함정", "그림자", "실종", "자백", "용의자", "균열", "관찰자", "덫"],
    "sci_fi_cyberpunk": ["네온", "전뇌", "회로", "의체", "데이터", "고철 도시", "복제", "암호", "기억 매매", "안드로이드", "접속", "잔상"],
    "romance_josei_drama": ["거리", "재회", "계절", "편지", "약속", "온도", "틈", "주말", "퇴근길", "그날", "안부", "두 사람"],
    "workplace_drama": ["사무실", "야근", "회의실", "사표", "팀장", "프로젝트", "정시 퇴근", "월요일", "보고서", "엘리베이터", "탕비실", "성과"],
    "action_battle": ["주먹", "최강", "결전", "투기장", "왕좌전", "수라", "맹세", "검", "전선", "패왕", "한 방", "끝장"],
    "historical_period": ["사화", "변방", "어전", "장원", "환로", "유배", "회한", "북풍", "옛 성", "사관", "밀지", "귀향"],
    "isekai": ["이세계", "전생", "회귀", "용사", "던전", "차원문", "다시", "두 번째 삶", "마왕성", "리셋", "환생", "귀환"],
    "supernatural_mystery": ["괴담", "심령", "골목 귀신", "사찰", "부적", "원혼", "야행", "기담", "흉가", "야시", "신내림", "저편"],
    "psychological_horror": ["악몽", "벽 속", "방", "거울", "지하", "정적", "속삭임", "흔적", "문 너머", "정전", "그것", "틈새"],
    "sports_competition": ["코트", "마지막 세트", "결승", "역전", "팀", "벤치", "한계점", "라스트 슛", "트랙", "링", "버저", "전국대회"],
    "school_coming_of_age": ["교실", "방과 후", "옥상", "졸업", "여름", "동아리", "첫날", "열일곱", "체육창고", "복도", "수학여행", "그 계절"],
    "cultivation_martial": ["무림", "검문", "기연", "심법", "절벽", "단약", "패도", "은거", "비급", "한천", "협객", "득도"],
}

# Per (genre, topic) → Claude-authored native Korean candidate titles.
# Each cell holds enough variants for the worst-case global occurrence count.
_TITLES: dict[tuple[str, str], list[str]] = {
    # ── action_battle ──────────────────────────────────────────────────────
    ("action_battle", "adhd_focus"): ["폭주하는 검", "산만한 천재 검사", "흩어진 검의 길", "질주의 끝", "멈추지 않는 주먹", "한 점만 노려라"],
    ("action_battle", "courage"): ["겁쟁이의 첫 일격", "물러서지 않는다", "떨리는 검", "한 발 더", "도망치던 자의 반격", "끝까지 선다"],
    ("action_battle", "self_worth"): ["밑바닥의 패왕", "버려진 검의 왕좌", "이름 없는 최강", "증명의 무대", "약자의 정점", "쓸모없던 자의 검"],
    ("action_battle", "burnout"): ["불타버린 검사", "재가 된 주먹", "마지막 불씨", "타들어간 전선", "꺼진 투지", "다시 타오르다"],
    ("action_battle", "imposter_syndrome"): ["가짜 영웅", "거짓 최강자", "훔친 칭호", "사칭하는 검", "진짜가 아닌 자", "들통난 패왕"],
    ("action_battle", "social_anxiety"): ["혼자 싸우는 검", "군중이 무서운 투사", "고독한 패왕", "낯선 투기장", "말 없는 검객", "무리 밖의 강자"],
    ("action_battle", "grief"): ["복수의 검", "잃은 자를 위한 일격", "남겨진 검사", "묘비 앞의 맹세", "떠난 이의 검", "마지막 약속의 칼"],
    ("action_battle", "compassion"): ["적을 베지 않는 검", "지키는 주먹", "용서의 일격", "구하는 칼", "분노 너머의 검", "끌어안는 패왕"],
    ("action_battle", "somatic_healing"): ["부서진 몸의 검", "통증을 넘어선 주먹", "흉터의 검사", "다시 일어선 전사", "낡은 몸의 패왕", "상처를 입은 칼"],
    # ── cultivation_martial ────────────────────────────────────────────────
    ("cultivation_martial", "courage"): ["겁많은 무림 후기지수", "절벽 위의 첫걸음", "두려움을 베는 검", "물러서지 않는 협객", "한 걸음의 기연", "무명의 패도"],
    # ── dark_fantasy ───────────────────────────────────────────────────────
    ("dark_fantasy", "anxiety"): ["멈추지 않는 저주", "끝없는 흑야", "심장을 갉는 마수", "불길한 예감의 성", "잠들지 못하는 마탑", "흔들리는 왕좌"],
    ("dark_fantasy", "boundaries"): ["넘지 말아야 할 선", "금단의 마탑", "결계를 긋는 자", "침범당한 성", "선을 지키는 마법사", "경계의 주박"],
    ("dark_fantasy", "burnout"): ["꺼져가는 마력", "잿빛 마탑", "타버린 대마법사", "고갈된 주문", "마지막 불꽃의 저주", "재가 된 왕좌"],
    ("dark_fantasy", "compassion"): ["마왕을 용서한 자", "저주를 끌어안다", "괴물을 사랑한 기사", "자비의 마탑", "구원의 흑마법", "용서받지 못할 자비"],
    ("dark_fantasy", "courage"): ["저주에 맞선 검사", "심연으로 내려가다", "두려움의 마탑", "물러서지 않는 기사", "어둠을 가르는 자", "공포를 삼킨 용사"],
    ("dark_fantasy", "financial_anxiety"): ["빚에 팔린 영혼", "황금 저주", "파산한 마법사", "대가를 치르는 계약", "탐욕의 마탑", "값을 매긴 운명"],
    ("dark_fantasy", "grief"): ["죽은 자를 부르는 마법", "남겨진 흑마법사", "되살리는 금기", "잿빛 추억의 성", "떠난 이의 주박", "묘지의 대마법사"],
    ("dark_fantasy", "imposter_syndrome"): ["가짜 용사", "사칭하는 대마법사", "거짓 예언의 아이", "훔친 마력", "왕좌의 사기꾼", "정체를 숨긴 마왕"],
    ("dark_fantasy", "overthinking"): ["천 갈래의 운명", "끝없는 예언의 미로", "생각에 잠긴 마탑", "결말을 읽는 자의 저주", "되감기는 운명", "선택의 심연"],
    ("dark_fantasy", "self_worth"): ["버려진 마왕의 후예", "밑바닥의 흑마법사", "쓸모없는 저주받은 아이", "이름 없는 용사", "잿더미의 왕", "가치를 증명하는 마탑"],
    ("dark_fantasy", "sleep"): ["깨어나지 못하는 저주", "악몽의 마탑", "잠의 결계", "영원히 잠든 성", "꿈을 먹는 마수", "잠들지 못하는 왕"],
    ("dark_fantasy", "somatic_healing"): ["부서진 몸의 마법사", "흉터의 저주", "낡은 그릇의 마왕", "통증을 봉인한 성", "되살아나는 살갗", "상처 입은 용사"],
    ("dark_fantasy", "trauma_recovery"): ["재가 된 자의 부활", "무너진 성의 재건", "상흔의 마탑", "되돌아온 마왕", "깨진 봉인의 회복", "잿더미에서 일어선 자"],
    # ── historical_period ──────────────────────────────────────────────────
    ("historical_period", "burnout"): ["탈진한 사관", "북풍의 변방장수", "꺼진 등불의 어전", "마지막 상소", "지친 충신", "회한의 장원"],
    ("historical_period", "courage"): ["유배 간 충신의 반격", "어전에 선 변방의 무사", "물러서지 않는 사관", "북풍에 맞선 자", "두려움 없는 협객", "옛 성의 결단"],
    ("historical_period", "grief"): ["떠난 임을 그리는 사화", "남겨진 미망인", "잿빛 귀향", "묘비 앞의 충신", "잃어버린 장원", "한 서린 변방"],
    ("historical_period", "imposter_syndrome"): ["가짜 세자", "사칭한 어의", "훔친 가문의 이름", "거짓 충신", "정체를 숨긴 무사", "들통난 사관"],
    ("historical_period", "overthinking"): ["천 갈래의 밀지", "끝없는 책략의 어전", "생각에 잠긴 책사", "수읽기의 사화", "되감기는 음모", "선택의 변방"],
    ("historical_period", "self_worth"): ["천출의 어의", "밑바닥의 변방장수", "이름 없는 충신", "버려진 가문의 후예", "쓸모없던 사관", "증명의 어전"],
    ("historical_period", "shame"): ["낙인 찍힌 사관", "치욕의 유배", "감춰진 죄의 장원", "고개 숙인 충신", "오명을 쓴 무사", "되찾는 명예"],
    ("historical_period", "social_anxiety"): ["말 없는 어의", "낯선 어전의 무사", "고독한 변방장수", "무리 밖의 충신", "홀로 선 사관", "침묵하는 책사"],
    ("historical_period", "somatic_healing"): ["부서진 몸의 무사", "흉터의 변방장수", "낡은 갑옷의 장수", "통증을 견딘 충신", "되살아난 어의", "상처 입은 협객"],
    # ── isekai ─────────────────────────────────────────────────────────────
    ("isekai", "anxiety"): ["불안한 용사의 전생", "끝없는 던전의 밤", "잠들지 못하는 이세계", "불길한 차원문", "흔들리는 마왕성", "멈추지 않는 회귀"],
    ("isekai", "burnout"): ["은퇴하고 싶은 용사", "타버린 마왕", "재가 된 전생자", "고갈된 마력의 회귀", "마지막 던전의 불씨", "지친 차원 여행자"],
    ("isekai", "courage"): ["겁쟁이 용사의 전생", "두려움을 넘은 회귀자", "물러서지 않는 던전", "한 발 더 내딛다", "공포를 삼킨 전생자", "다시 맞서는 용사"],
    ("isekai", "imposter_syndrome"): ["가짜 용사의 전생", "사칭하는 회귀자", "훔친 직업의 이세계", "거짓 영웅의 던전", "정체를 숨긴 마왕", "들통난 전생자"],
    ("isekai", "self_worth"): ["버려진 용사의 회귀", "밑바닥부터 다시", "쓸모없던 직업의 전생", "이름 없는 이세계인", "최약체의 두 번째 삶", "증명하는 던전"],
    ("isekai", "trauma_recovery"): ["다시 사는 용사", "무너진 세계의 재건", "상흔의 회귀자", "되돌아온 전생자", "깨진 운명의 회복", "잿더미의 이세계"],
    # ── iyashikei ──────────────────────────────────────────────────────────
    ("iyashikei", "anxiety"): ["느릿한 오후의 찻집", "골목 끝 작은 정원", "햇살 드는 창가", "천천히, 산책", "노을 지는 빈터", "조용한 툇마루"],
    ("iyashikei", "boundaries"): ["나만의 작은 정원", "문을 닫는 오후", "혼자만의 찻집", "거리를 두는 산책", "내 자리의 햇살", "조용한 거절의 창가"],
    ("iyashikei", "burnout"): ["아무것도 하지 않는 오후", "쉬어가는 찻집", "느린 회복의 정원", "멈춰 선 산책", "비워내는 창가", "다시 데우는 온기"],
    ("iyashikei", "financial_anxiety"): ["작은 동전의 찻집", "소박한 밥상의 오후", "검소한 정원", "한 끼의 온기", "가벼운 주머니의 산책", "넉넉한 마음의 빈터"],
    ("iyashikei", "grief"): ["떠난 이의 빈 의자", "노을빛 추억의 정원", "남겨진 찻잔", "그리움이 머문 창가", "조용한 작별의 산책", "온기가 남은 툇마루", "빈집에 남은 화분", "두고 간 우산의 오후", "마지막 편지의 찻집", "오래된 사진 속 골목"],
    ("iyashikei", "imposter_syndrome"): ["서툴러도 괜찮은 찻집", "어설픈 정원사", "흉내 내는 오후", "초보의 산책", "부족한 대로의 창가", "있는 그대로의 온기"],
    ("iyashikei", "overthinking"): ["생각을 내려놓는 오후", "비워지는 찻집", "멈춘 머릿속의 정원", "단순한 산책", "고요한 창가", "텅 빈 툇마루"],
    ("iyashikei", "self_worth"): ["있는 그대로의 오후", "작아도 빛나는 정원", "나다운 찻집", "느려도 좋은 산책", "충분한 창가", "소중한 빈터"],
    ("iyashikei", "shame"): ["감추지 않는 오후", "흠집 난 찻잔의 정원", "민낯의 산책", "부끄럼 없는 창가", "있는 그대로의 툇마루", "용서하는 온기"],
    ("iyashikei", "sleep"): ["나른한 오후의 낮잠", "잠이 오는 찻집", "포근한 정원", "느린 밤의 산책", "별빛 드는 창가", "잠드는 툇마루"],
    ("iyashikei", "social_anxiety"): ["혼자여도 좋은 오후", "말 없는 찻집", "조용한 정원의 손님", "낯선 골목의 산책", "고요한 창가", "한 사람의 온기", "구석 자리의 단골", "인사가 서툰 주인", "혼밥하기 좋은 골목", "조용히 머무는 빈터"],
    ("iyashikei", "somatic_healing"): ["몸을 데우는 오후", "따뜻한 목욕의 찻집", "느린 호흡의 정원", "맨발의 산책", "햇볕 쬐는 창가", "온기 도는 툇마루"],
    ("iyashikei", "trauma_recovery"): ["천천히 아무는 오후", "되살아나는 정원", "조심스러운 찻집", "한 걸음씩 산책", "다시 여는 창가", "회복의 툇마루"],
    # ── psychological_horror ───────────────────────────────────────────────
    ("psychological_horror", "anxiety"): ["벽 속의 속삭임", "멈추지 않는 노크", "불 꺼진 방", "끝없는 복도", "거울 속의 그것", "잠들 수 없는 집"],
    ("psychological_horror", "burnout"): ["텅 빈 껍데기", "꺼진 방의 정적", "타버린 흔적", "무너진 집", "재가 된 그것", "마지막 정전"],
    ("psychological_horror", "grief"): ["떠난 이가 남긴 방", "빈 의자의 속삭임", "지워지지 않는 흔적", "거울 속 그 사람", "돌아오는 발소리", "문 너머의 그림자"],
    ("psychological_horror", "sleep"): ["악몽이 끝나지 않는 방", "잠들면 오는 그것", "눈뜨면 다른 집", "끝없는 정전의 밤", "꿈과 벽 사이", "깨어나지 못하는 침대"],
    ("psychological_horror", "somatic_healing"): ["살갗 아래의 그것", "낡은 몸의 흔적", "거울 속 상처", "지하의 통증", "벽이 된 몸", "흉터가 속삭이다"],
    ("psychological_horror", "trauma_recovery"): ["지워지지 않는 방", "되돌아오는 그것", "무너진 집의 정적", "흔적을 지우는 밤", "깨진 거울의 회복", "문을 닫는 손"],
    # ── psychological_thriller ─────────────────────────────────────────────
    ("psychological_thriller", "anxiety"): ["멈추지 않는 추적", "끝나지 않는 밀실", "불길한 자백", "잠들 수 없는 용의자", "흔들리는 알리바이", "다가오는 덫"],
    ("psychological_thriller", "boundaries"): ["넘지 말아야 할 선", "침범당한 밀실", "거리를 둔 공범", "선을 그은 관찰자", "지켜야 할 비밀", "경계의 함정"],
    ("psychological_thriller", "burnout"): ["지친 형사의 마지막 사건", "꺼진 추적", "탈진한 관찰자", "마지막 자백", "무너진 수사", "재가 된 진실"],
    ("psychological_thriller", "financial_anxiety"): ["빚이 부른 살인", "보험금의 덫", "파산한 자의 거짓말", "돈을 쫓는 추적", "탐욕의 밀실", "값을 매긴 알리바이"],
    ("psychological_thriller", "imposter_syndrome"): ["가짜 형사", "사칭한 용의자", "훔친 신분의 거짓말", "거짓 증인", "정체를 숨긴 공범", "들통난 관찰자"],
    ("psychological_thriller", "overthinking"): ["천 갈래의 진실", "끝없는 수읽기의 밀실", "생각에 갇힌 형사", "되감기는 알리바이", "결말을 의심하다", "선택의 함정"],
    ("psychological_thriller", "self_worth"): ["무능한 형사의 한 수", "밑바닥 탐정", "이름 없는 관찰자", "버려진 수사관", "증명하는 자백", "최약체의 추적"],
    ("psychological_thriller", "shame"): ["감춰진 죄의 밀실", "낙인 찍힌 용의자", "치욕의 자백", "지워야 할 과거", "고개 숙인 형사", "오명을 벗는 추적"],
    ("psychological_thriller", "sleep"): ["잠들면 시작되는 추적", "악몽의 밀실", "불면의 용의자", "눈뜨면 사라진 증거", "끝없는 밤의 함정", "깨어나지 못한 알리바이"],
    ("psychological_thriller", "social_anxiety"): ["말 없는 목격자", "낯선 자들의 밀실", "고독한 관찰자", "무리 밖의 용의자", "홀로 쫓는 형사", "침묵하는 공범"],
    ("psychological_thriller", "somatic_healing"): ["흉터가 말하는 진실", "부서진 몸의 형사", "통증의 알리바이", "낡은 손의 추적", "되살아난 기억의 자백", "상처 입은 관찰자"],
    # ── romance_josei_drama ────────────────────────────────────────────────
    ("romance_josei_drama", "boundaries"): ["적당한 거리의 두 사람", "선을 긋는 연애", "혼자만의 주말", "내 자리의 온도", "거리를 두는 재회", "지켜야 할 틈"],
    ("romance_josei_drama", "burnout"): ["퇴근길의 위로", "지친 두 사람", "쉬어가는 계절", "멈춰 선 약속", "비워내는 주말", "다시 데우는 온도"],
    ("romance_josei_drama", "financial_anxiety"): ["소박한 데이트", "월급날의 재회", "검소한 두 사람", "한 끼의 온도", "가벼운 주머니의 계절", "넉넉한 마음의 약속"],
    ("romance_josei_drama", "grief"): ["떠난 그 사람의 편지", "노을빛 재회", "남겨진 두 사람", "그리움이 머문 거리", "조용한 작별의 계절", "온기가 남은 약속"],
    ("romance_josei_drama", "imposter_syndrome"): ["사랑받을 자격", "서툰 두 사람", "흉내 내는 연애", "부족한 대로의 재회", "있는 그대로의 온도", "어설픈 고백"],
    ("romance_josei_drama", "self_worth"): ["나다운 연애", "있는 그대로의 두 사람", "충분한 사랑", "느려도 좋은 재회", "소중한 계절", "빛나는 나의 온도"],
    ("romance_josei_drama", "social_anxiety"): ["말주변 없는 그 사람", "낯선 자리의 재회", "고요한 두 사람", "무리 밖의 연애", "홀로 선 계절", "조용한 첫 인사", "눈을 못 맞추는 그녀", "단둘이 남은 엘리베이터", "인사가 어려운 사이", "창밖만 보던 두 사람", "말 대신 건넨 우산", "조용한 옆자리"],
    ("romance_josei_drama", "somatic_healing"): ["손이 닿는 거리", "따뜻한 두 사람", "느린 호흡의 계절", "맞잡은 온도", "햇볕 같은 재회", "온기 도는 약속"],
    # ── sci_fi_cyberpunk ───────────────────────────────────────────────────
    ("sci_fi_cyberpunk", "anxiety"): ["멈추지 않는 회로", "끝없는 네온의 밤", "잠들 수 없는 전뇌", "불길한 신호의 도시", "흔들리는 의체", "다가오는 잔상"],
    ("sci_fi_cyberpunk", "burnout"): ["방전된 의체", "꺼진 회로", "탈진한 해커", "마지막 접속", "무너진 네트워크", "재가 된 데이터"],
    ("sci_fi_cyberpunk", "financial_anxiety"): ["빚에 팔린 의체", "기억을 파는 도시", "파산한 해커", "크레딧의 덫", "탐욕의 전뇌", "값을 매긴 영혼"],
    ("sci_fi_cyberpunk", "imposter_syndrome"): ["가짜 인간", "사칭하는 안드로이드", "훔친 신분의 데이터", "거짓 기억의 의체", "정체를 숨긴 복제", "들통난 해커"],
    ("sci_fi_cyberpunk", "overthinking"): ["천 갈래의 시뮬레이션", "끝없는 연산의 도시", "생각에 갇힌 전뇌", "되감기는 데이터", "결말을 읽는 회로", "선택의 잔상"],
    ("sci_fi_cyberpunk", "self_worth"): ["버려진 의체", "밑바닥 해커", "쓸모없던 안드로이드", "이름 없는 복제", "최약체의 회로", "증명하는 데이터"],
    ("sci_fi_cyberpunk", "sleep"): ["잠들지 못하는 전뇌", "악몽의 회로", "불면의 의체", "눈뜨면 다른 도시", "끝없는 정전의 밤", "깨어나지 못한 접속"],
    ("sci_fi_cyberpunk", "somatic_healing"): ["살갗 아래의 회로", "낡은 의체의 통증", "거울 속 잔상", "고철 도시의 흉터", "되살아나는 감각", "상처 입은 안드로이드"],
    # ── school_coming_of_age ───────────────────────────────────────────────
    ("school_coming_of_age", "courage"): ["옥상에서의 첫 고백", "물러서지 않는 열일곱", "두려웠던 방과 후", "한 발 더, 졸업 전에", "용기 낸 그 여름", "교실 밖으로"],
    ("school_coming_of_age", "self_worth"): ["빛나지 않아도 괜찮아", "교실 구석의 나", "있는 그대로의 열일곱", "느려도 좋은 졸업", "충분한 그 계절", "나다운 방과 후"],
    # ── sports_competition ─────────────────────────────────────────────────
    ("sports_competition", "adhd_focus"): ["산만한 천재 선수", "흩어진 집중의 코트", "질주의 마지막 세트", "멈추지 않는 트랙", "한 점만 노려라", "폭주하는 에이스"],
    ("sports_competition", "burnout"): ["불타버린 에이스", "방전된 코트", "마지막 세트의 불씨", "지친 주전", "무너진 트랙", "다시 뛰는 벤치"],
    ("sports_competition", "courage"): ["벤치의 첫 출전", "물러서지 않는 코트", "두려웠던 결승", "한 발 더, 라스트 슛", "겁쟁이 에이스", "버저 너머로"],
    ("sports_competition", "grief"): ["떠난 동료의 등번호", "남겨진 코트", "그를 위한 결승", "빈 벤치의 약속", "마지막 세트의 묘비", "이어달리는 트랙"],
    ("sports_competition", "imposter_syndrome"): ["가짜 에이스", "사칭한 주전", "훔친 등번호", "거짓 천재", "정체를 숨긴 신인", "들통난 코트"],
    ("sports_competition", "self_worth"): ["만년 후보의 한 방", "밑바닥 에이스", "이름 없는 주전", "버려진 신인", "증명하는 결승", "최약체의 코트"],
    ("sports_competition", "social_anxiety"): ["말 없는 에이스", "낯선 코트의 신인", "고독한 주전", "무리 밖의 선수", "홀로 뛰는 트랙", "침묵하는 벤치"],
    # ── supernatural_mystery ───────────────────────────────────────────────
    ("supernatural_mystery", "anxiety"): ["멈추지 않는 괴담", "끝없는 야행", "불 꺼진 흉가", "잠들 수 없는 사찰", "흔들리는 부적", "다가오는 원혼"],
    ("supernatural_mystery", "boundaries"): ["넘지 말아야 할 골목", "결계 친 사찰", "거리를 둔 심령", "선을 그은 부적", "지켜야 할 흉가", "경계의 야시"],
    ("supernatural_mystery", "burnout"): ["지친 퇴마사", "꺼진 부적", "탈진한 무당", "마지막 굿", "무너진 사찰", "재가 된 원혼"],
    ("supernatural_mystery", "courage"): ["흉가에 들어선 자", "두려움을 쫓는 퇴마사", "물러서지 않는 무당", "야행에 맞선 자", "공포를 삼킨 심령탐정", "어둠을 가르는 부적"],
    ("supernatural_mystery", "grief"): ["떠난 이를 부르는 굿", "남겨진 무당", "되돌아온 원혼", "잿빛 사찰의 추억", "그리움이 머문 흉가", "묘지의 심령탐정"],
    ("supernatural_mystery", "imposter_syndrome"): ["가짜 무당", "사칭한 퇴마사", "훔친 신내림", "거짓 영매", "정체를 숨긴 원혼", "들통난 심령탐정"],
    ("supernatural_mystery", "overthinking"): ["천 갈래의 괴담", "끝없는 수읽기의 흉가", "생각에 갇힌 퇴마사", "되감기는 야행", "결말을 의심하는 무당", "선택의 사찰"],
    ("supernatural_mystery", "self_worth"): ["밑바닥 무당", "이름 없는 퇴마사", "버려진 신내림", "쓸모없던 영매", "증명하는 굿", "최약체의 부적"],
    ("supernatural_mystery", "shame"): ["감춰진 죄의 흉가", "낙인 찍힌 무당", "치욕의 신내림", "지워야 할 과거의 원혼", "고개 숙인 퇴마사", "오명을 벗는 굿"],
    ("supernatural_mystery", "sleep"): ["잠들면 오는 원혼", "악몽의 사찰", "불면의 무당", "눈뜨면 다른 골목", "끝없는 야행의 밤", "깨어나지 못한 흉가"],
    ("supernatural_mystery", "social_anxiety"): ["말 없는 영매", "낯선 골목의 퇴마사", "고독한 무당", "무리 밖의 심령탐정", "홀로 걷는 야행", "침묵하는 부적"],
    ("supernatural_mystery", "somatic_healing"): ["살갗에 새긴 부적", "낡은 몸의 무당", "거울 속 원혼", "사찰의 흉터", "되살아나는 감각의 굿", "상처 입은 퇴마사"],
    ("supernatural_mystery", "trauma_recovery"): ["지워지지 않는 괴담", "되돌아온 원혼의 화해", "무너진 사찰의 재건", "흔적을 지우는 굿", "깨진 부적의 회복", "문을 닫는 무당"],
    # ── workplace_drama ────────────────────────────────────────────────────
    ("workplace_drama", "adhd_focus"): ["산만한 천재 사원", "흩어진 책상의 야근", "질주하는 프로젝트", "멈추지 않는 회의", "한 가지만 끝내라", "폭주하는 신입"],
    ("workplace_drama", "anxiety"): ["멈추지 않는 야근", "끝없는 회의", "불길한 월요일", "잠들 수 없는 사무실", "흔들리는 보고서", "다가오는 마감"],
    ("workplace_drama", "boundaries"): ["정시 퇴근의 기술", "선을 긋는 사원", "혼자만의 점심", "내 자리의 온도", "거리를 두는 회식", "지켜야 할 퇴근길"],
    ("workplace_drama", "burnout"): ["사표를 품은 직장인", "방전된 사무실", "탈진한 팀장", "마지막 야근", "무너진 프로젝트", "다시 출근하는 월요일"],
    ("workplace_drama", "courage"): ["사표를 내던진 날", "물러서지 않는 사원", "두려웠던 회의실", "한 마디 더, 상사에게", "겁쟁이 신입의 반격", "엘리베이터 너머로"],
    ("workplace_drama", "financial_anxiety"): ["월급날의 사무실", "빚에 묶인 직장인", "검소한 점심의 야근", "보너스의 덫", "탐욕의 회의실", "값을 매긴 성과"],
    ("workplace_drama", "imposter_syndrome"): ["가짜 에이스 사원", "사칭한 팀장", "훔친 성과의 보고서", "거짓 경력", "정체를 숨긴 신입", "들통난 회의실"],
    ("workplace_drama", "overthinking"): ["천 갈래의 보고서", "끝없는 수읽기의 회의", "생각에 갇힌 사원", "되감기는 프로젝트", "결말을 의심하는 팀장", "선택의 사무실"],
    ("workplace_drama", "social_anxiety"): ["말 없는 사원", "낯선 회의실의 신입", "고독한 팀장", "무리 밖의 직장인", "홀로 남은 야근", "침묵하는 탕비실"],
}

# Native Korean disambiguators — appended ONLY if a chosen title would still
# collide globally (rare). Keep them genre-neutral and non-clinical.
_DISAMBIG = ["再", "외전", "후일담", "두 번째", "그 후", "다른 길", "또 하나의", "새벽편", "황혼편", "이면"]
# Use Korean words (not the CJK char) so titles stay native:
_DISAMBIG = ["외전", "후일담", "그 후", "다른 길", "또 하나의 이야기", "새벽 편", "황혼 편", "이면", "재회 편", "전야"]

# Clinical / self-help stems that must NEVER appear in a title (topic-leak guard).
# Korean clinical vocabulary + the obvious banned terms from the brief.
CLINICAL_STEMS = (
    "불안", "번아웃", "치유", "자존감", "트라우마", "우울", "공황", "스트레스",
    "심리치료", "상담", "자기계발", "멘탈", "힐링", "테라피", "증후군",
    "집중력", "수면장애", "자기혐오", "회복탄력", "마음챙김", "명상법",
)


def _leaks_topic(title: str) -> bool:
    return any(stem in title for stem in CLINICAL_STEMS)


def _has_korean(s: str) -> bool:
    return any("가" <= c <= "힣" for c in s)  # Hangul syllables


def _load_yaml(p: Path) -> Any:
    with open(p, "r", encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def _det_index(seed: str, n: int) -> int:
    digest = hashlib.sha256(seed.encode("utf-8")).digest()
    return int.from_bytes(digest[:4], "big") % max(n, 1)


def assign_topics(brand_info: dict, series_list: list[dict]) -> None:
    """Round-robin the brand's [primary]+secondary topics across its series.

    Identical algorithm to the ja_JP precedent (sort by genre then series
    index, then modulo over the topic list).
    """
    topics = [brand_info.get("primary_topic", "")] + list(brand_info.get("secondary_topics", []) or [])
    topics = [t for t in topics if t] or ["self_worth"]
    for i, sp in enumerate(sorted(series_list, key=lambda r: (r["genre"], r["series_index"]))):
        sp["_topic"] = topics[i % len(topics)]


def gen_title(brand: str, genre: str, topic: str, occ: int,
              used_global: set[str], used_brand: set[str]) -> str:
    """Pick a Claude-authored Korean title for the `occ`-th global occurrence
    of (genre, topic). Guarantees no clinical leak, global uniqueness, and
    within-brand uniqueness.
    """
    candidates = list(_TITLES.get((genre, topic), []))
    # Fallback composer: <image noun> + genre head, if the cell is thin.
    if not candidates:
        heads = _GENRE_HEADS.get(genre, [genre])
        candidates = [h for h in heads]

    # Deterministic ordering offset so different (genre,topic) cells don't all
    # start at index 0, but stable across runs.
    start = _det_index(f"{genre}|{topic}", len(candidates))
    ordered = candidates[start:] + candidates[:start]

    # First pass: walk ordered candidates, take the first that is clean + unused.
    for cand in ordered:
        if not cand or _leaks_topic(cand) or not _has_korean(cand):
            continue
        if cand in used_global or cand in used_brand:
            continue
        return cand

    # Second pass: compose from genre heads if all base candidates are taken.
    heads = _GENRE_HEADS.get(genre, [genre])
    for h in heads:
        for suffix in _DISAMBIG:
            cand = f"{h}: {suffix}"
            if _leaks_topic(cand) or cand in used_global or cand in used_brand:
                continue
            return cand

    # Last resort: append a native disambiguator to the first base candidate.
    base = next((c for c in ordered if c and not _leaks_topic(c) and _has_korean(c)), genre)
    for suffix in _DISAMBIG:
        cand = f"{base} {suffix}"
        if cand not in used_global and cand not in used_brand and not _leaks_topic(cand):
            return cand
    # numeric fallback (still native-readable)
    i = 2
    while True:
        cand = f"{base} 제{i}부"
        if cand not in used_global and cand not in used_brand:
            return cand
        i += 1


def _yaml_quote(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def apply_edits(path: Path, *, title: str, topic: str, author: str) -> bool:
    """Replace `: TBD` lines in place. Idempotent. Returns True if changed.

    Targeted line replacement (NOT a YAML round-trip) — preserves the header
    comments and field order exactly. Only the 4 target TBD lines are touched.
    """
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    changed = False
    in_localized = False
    for i, line in enumerate(lines):
        stripped = line.rstrip("\n")
        if re.match(r"^title:\s*TBD\s*$", stripped):
            lines[i] = f"title: {_yaml_quote(title)}\n"; changed = True
        elif re.match(r"^localized_titles:\s*$", stripped):
            in_localized = True
        elif in_localized and re.match(r"^\s+ko_KR:\s*TBD\s*$", stripped):
            indent = line[:len(line) - len(line.lstrip())]
            lines[i] = f"{indent}ko_KR: {_yaml_quote(title)}\n"; changed = True; in_localized = False
        elif re.match(r"^topic:\s*TBD\s*$", stripped):
            lines[i] = f"topic: {topic}\n"; changed = True
        elif re.match(r"^manga_author:\s*TBD\s*$", stripped):
            lines[i] = f"manga_author: {_yaml_quote(author)}\n"; changed = True
        elif stripped and not line.startswith((" ", "\t")) and in_localized:
            in_localized = False
    if changed:
        path.write_text("".join(lines), encoding="utf-8")
    return changed


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--brand", help="Restrict to one brand_id")
    ap.add_argument("--limit", type=int, help="Process at most N series")
    ap.add_argument("--no-write", action="store_true", help="Generate but do not edit YAML (review only)")
    args = ap.parse_args()

    brands = (_load_yaml(CANONICAL_BRANDS) or {}).get("brands", {})
    plans: list[dict] = []
    for p in sorted(SERIES_DIR.glob("*.yaml")):
        sp = _load_yaml(p) or {}
        plans.append({
            "path": p, "brand_id": sp.get("brand_id", ""), "genre": sp.get("genre", ""),
            "demographic": sp.get("demographic", "general"), "series_id": sp.get("series_id", p.stem),
            "series_index": sp.get("series_id", p.stem).split("__")[-1],
            "title_is_tbd": str(sp.get("title", "")).strip().upper() == "TBD",
        })

    by_brand: dict[str, list[dict]] = defaultdict(list)
    for r in plans:
        by_brand[r["brand_id"]].append(r)
    for b, lst in by_brand.items():
        assign_topics(brands.get(b, {}), lst)

    todo = [r for r in plans if (not args.brand or r["brand_id"] == args.brand)]
    todo.sort(key=lambda r: (r["brand_id"], r["genre"], r["series_index"]))
    if args.limit:
        todo = todo[: args.limit]

    used_global: set[str] = set()
    used_by_brand: dict[str, set[str]] = defaultdict(set)
    occ_counter: dict[tuple[str, str], int] = defaultdict(int)
    review_rows: list[dict] = []
    filled = skipped = 0
    t0 = time.time()
    for n, r in enumerate(todo, 1):
        if not r["title_is_tbd"]:
            skipped += 1
            continue
        gt = (r["genre"], r["_topic"])
        occ = occ_counter[gt]
        occ_counter[gt] += 1
        title = gen_title(r["brand_id"], r["genre"], r["_topic"], occ,
                          used_global, used_by_brand[r["brand_id"]])
        used_global.add(title)
        used_by_brand[r["brand_id"]].add(title)
        author = generate_display_name(genre=r["genre"], locale="ko_KR",
                                       brand_id=r["brand_id"], topic=r["_topic"],
                                       demographic=r["demographic"])
        wrote = False
        if not args.no_write:
            wrote = apply_edits(r["path"], title=title, topic=r["_topic"], author=author)
        filled += 1
        review_rows.append({"brand_id": r["brand_id"], "genre": r["genre"],
                            "series_id": r["series_id"], "topic": r["_topic"],
                            "title_ko": title, "manga_author": author, "written": wrote})

    if review_rows:
        REVIEW_OUT.parent.mkdir(parents=True, exist_ok=True)
        with open(REVIEW_OUT, "w", encoding="utf-8", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=list(review_rows[0].keys()))
            w.writeheader(); w.writerows(review_rows)
        print(f"review sidecar → {REVIEW_OUT.relative_to(ROOT)}")
    print(f"DONE filled={filled} skipped={skipped} "
          f"in {time.time()-t0:.1f}s  (Claude-authored ko_KR, no LLM/API)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
